### ISSUE TITLE
登录qq后显示前登录存在安全风险，请使用常用设备或通过手机号登录

### ISSUE THREAD

**Issue by zglwry** [DreamVoid/MiraiMC#121]
### 问题描述

qq验证完成输入指令后显示  登录存在安全风险，请使用常用设备或通过手机号登录

### 复现方法

qq滑动验证输入ticket，回车后出现

### 服务端类型

Sponge

### 服务端版本

Spigot-1.18.1

### MiraiMC 插件版本

2.9.2

### 服务端日志

```text
[18:10:15] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] 登录新的机器人账号: 430477084, 协议: ANDROID_PHONE
[18:10:15] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[18:10:17] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[18:10:17] [Thread-25/WARN]: [MiraiMC] 当前登录的QQ（430477084）需要滑动验证码验证
[18:10:17] [Thread-25/WARN]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[18:10:17] [Thread-25/WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=430477084&sid=9036686848277666057&cap_cd=Gc4rfxOwHEy1msdRllvASnss67OdE0DOabdyUMymRRxUR9NM6EJmig**&clientype=1&apptype=2
[18:10:17] [Thread-25/WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify slidercaptcha 430477084 <ticket>
[18:10:17] [Thread-25/WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify slidercaptchacancel 430477084
[18:10:17] [Thread-25/WARN]: [MiraiMC] 如需帮助，请参阅: https://wiki.miraimc.dreamvoid.ml/troubleshoot/verify-guide#slide-captcha
[18:11:10] [Server thread/INFO]: 已将ticket提交到服务器
[18:11:10] [DefaultDispatcher-worker-1/WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(430477084), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265) ~[mirai-core-all-2.10.0.jar:2.10.0]
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-all-2.10.0.jar:2.10.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [mirai-core-all-2.10.0.jar:2.10.0]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [mirai-core-all-2.10.0.jar:2.10.0]
[18:11:10] [Craft Scheduler Thread - 0/WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(430477084), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
[18:11:10] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Bot cancelled: Bot closed
```

**Comment by DreamVoid** [comment]
见常见问题解答
