### ISSUE TITLE
qchat指令无法使用导致控制台发不了消息

### ISSUE THREAD

**Issue by devsong42** [DreamVoid/MiraiMC#148]
### 问题描述

配置文件中已打开控制台发消息

报错`qchat test
[15:02:03 INFO]: 已发送QQ群聊天消息！
[15:02:03 WARN]: [MiraiMC] Plugin Chat2QQ v1.5 generated an exception while executing task 309
java.lang.NullPointerException: Cannot invoke "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.sendGroupMessage(String, long, String)" because "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.INSTANCE" is null
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$0(BukkitPlugin.java:94) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$1(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.run(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-333]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-333]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`
配置文件`# 游戏内配置
# 此部分配置只会影响 Minecraft 服务器内的聊天
general:
  # 是否允许bStats统计
  allow-bStats: true

  # 是否必须使用命令才能向QQ群发送聊天消息
  require-command-to-chat: false

  # 使用命令时是否同时向服务器内发送聊天消息
  command-also-broadcast-to-chat: true

  # 可用的世界，玩家只有在下面列出的世界中聊天才会被发送到QQ群
  available-worlds:
    - world
    - world_nether
    - world_the_end

  # 是否将上面的列表用作黑名单，即玩家在上面列出的世界聊天不会发送到QQ群
  available-worlds-use-as-blacklist: false

  # QQ群消息广播到游戏内聊天的格式（可以使用样式代码）
  # 变量：
  # %groupname% - 群名称
  # %groupid% - 群号
  # %nick% - 发送者群名片
  # %qq% - 发送者QQ号
  # %message% - 消息内容
  in-game-chat-format: "&6[%groupname%/%groupid%] &a%nick%(%qq%)&r: %message%"

  # 是否允许控制台使用聊天命令
  allow-console-chat: true

  # 如果作为控制台发送到QQ群的聊天消息，控制台要叫什么名字
  console-name: "控制台"

  # 游戏聊天前缀（聊天需要带有指定前缀才能发送到QQ群）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 当群名片不存在时是否尝试获取昵称
  use-nick-if-namecard-null: true

  # 启用 MiraiMC 内置的QQ绑定
  use-miraimc-bind: true

  # 已绑定玩家向服务器发送聊天消息的格式
  # 如果玩家没有绑定，消息格式仍按照上方设置的格式发送
  # 内置变量仍然可以使用
  bind-chat-format: "&6[QQ]&r %vault_prefix%%player_name%%vault_suffix%: %message%"

# 机器人配置
# 此部分配置只会影响到QQ群的聊天
bot:
  # 指定使用的QQ号，只有这个QQ号接收到的群消息才会被处理
  # 请至少设置一个
  bot-accounts:
    - 2101776717

  # 指定接收指定群的群消息，只有这个群接收到的消息才会被处理
  # 请至少设置一个
  group-ids:
    - 1006153259

  # 群聊天前缀（聊天需要带有指定前缀才能发送到服务器）
  requite-special-word-prefix:
    #启用这个功能
    enabled: false

    # 聊天前缀（可设置多个，群聊天只有带下面的前缀之一才会发送到服务器）
    prefix:
      - "#"

  # 服务器消息发送到QQ群的格式（可以使用PlaceholderAPI变量）
  # 自带变量：
  # %player% - 玩家显示昵称
  # %message% - 消息内容
  group-chat-format: "[EMS] %player%: %message%"

  # 是否发送玩家进服退服消息
  send-player-join-quit-message: true

  # 进服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-join-message: "%player% 抟扶摇而入服务器"

  # 退服消息
  # 自带变量：
  # %player% - 玩家显示昵称
  player-quit-message: "%player% 飞出了服务器，并说：“我一定会回来的！”"
`

### 复现方法

1. 装载Chat2QQ插件后输入qchat指令（玩家输和控制台都一样）

### 服务端类型

Bukkit

### 服务端版本

Paper-1.18.2

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
qchat test
[15:02:03 INFO]: 已发送QQ群聊天消息！
[15:02:03 WARN]: [MiraiMC] Plugin Chat2QQ v1.5 generated an exception while executing task 309
java.lang.NullPointerException: Cannot invoke "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.sendGroupMessage(String, long, String)" because "me.dreamvoid.miraimc.internal.httpapi.MiraiHttpAPI.INSTANCE" is null
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$0(BukkitPlugin.java:94) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.lambda$run$1(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at me.dreamvoid.chat2qq.bukkit.BukkitPlugin$1.run(BukkitPlugin.java:92) ~[Chat2QQ-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.18.2.jar:git-Paper-333]
        at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.18.2.jar:git-Paper-333]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.18.2.jar:git-Paper-333]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by devsong42** [comment]
补充：玩家使用指令可以发出消息，控制台不可以，但报错都是一样的

**Comment by DreamVoid** [comment]
排版过于杂乱，无法正常阅读
