### ISSUE TITLE
Bukkit版本的Mirai在登录机器人时出现报错从而无法登录

### ISSUE THREAD

**Issue by xiaobao4909** [DreamVoid/MiraiMC#149]
### 问题描述

我在用Bukkit版MiraiMC登录机器人时 报出此错误 Bungee版而无此错误 希望尽快解决

[17:14:00 WARN]: [MiraiMC] null
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
        at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
        Caused by: java.nio.channels.UnresolvedAddressException
                at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
                at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
                at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]

### 复现方法

1.在登录机器人是触发Bug

### 服务端类型

Bukkit

### 服务端版本

1.8.8

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
Loading libraries, please wait...
[17:13:53 INFO]: Starting minecraft server version 1.8.8
[17:13:53 INFO]: Loading properties
[17:13:53 INFO]: Default game type: ADVENTURE
[17:13:53 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[17:13:53 INFO]: Debug logging is disabled
[17:13:53 INFO]: Server Ping Player Sample Count: 12

[17:13:53 INFO]: Using 4 threads for Netty based IO
[17:13:54 INFO]: Generating keypair
[17:13:54 INFO]: Starting Minecraft server on 127.0.0.1:10000
[17:13:54 INFO]: Using default channel type
[17:13:54 INFO]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[17:13:54 INFO]: Set PluginClassLoader as parallel capable
[17:13:54 INFO]: [ProtectWorld] Loading ProtectWorld v17.728
[17:13:54 INFO]: [SafeLogin] Loading SafeLogin v1.1.0
[17:13:54 INFO]: [PlaceholderAPI] Loading PlaceholderAPI v2.11.1
[17:13:54 INFO]: [AntiFallDamage] Loading AntiFallDamage v1.5
[17:13:54 INFO]: [MiraiMC] Loading MiraiMC v1.6.1
[17:13:54 WARN]: [MiraiMC] Default system encoding may have misread config.yml from plugin jar
[17:13:55 INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[17:13:55 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.0-M2.2.jar
[17:13:55 INFO]: [MiraiMC] Loading library mirai-core-all-2.11.0-M2.2.jar
[17:13:55 INFO]: [Vault] Loading Vault v1.7.3-b131
[17:13:55 INFO]: [ProtocolLib] Loading ProtocolLib v4.8.0
[17:13:56 INFO]: [SuperLobby] Loading SuperLobby v4.3.9
[17:13:56 INFO]: [LagAssist] Loading LagAssist v2.28.0
[17:13:56 INFO]: [Citizens] Loading Citizens v2.0.24-SNAPSHOT (build 1605)
[17:13:56 INFO]: [AAC5] Loading AAC5 v5.2.0
[17:13:56 INFO]: [AuthMe] Loading AuthMe v5.6.0-beta2-b2453
[17:13:56 INFO]: [CommandNPC] Loading CommandNPC v1.9.1
[17:13:56 INFO]: [Vault] Enabling Vault v1.7.3-b131
[17:13:56 INFO]: [Vault] [Permission] SuperPermissions loaded as backup permission system.
[17:13:56 INFO]: [Vault] Enabled Version 1.7.3-b131
[17:13:56 INFO]: [ProtocolLib] Enabling ProtocolLib v4.8.0
[17:13:56 INFO]: [ProtocolLib] Started structure compiler thread.
[17:13:56 INFO]: [AAC5] Enabling AAC5 v5.2.0
[17:13:57 ERROR]: Error occurred while enabling AAC5 v5.2.0 (Is it up to date?)
java.lang.AbstractMethodError: null
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.kc.a(kc.java:8) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.jI.a(jI.java:28) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.jI.<init>(jI.java:140) ~[?:?]
        at me.konsolas.aac.jI.a(jI.java:78) ~[?:?]
        at me.konsolas.aac.nd.a(Unknown Source) ~[?:?]
        at me.konsolas.aac.AAC.onEnable(AAC.java:83) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Server.jar:git-Spigot-21fe707-741a1bd]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:199) [Server.jar:git-Spigot-21fe707-741a1bd]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[17:13:57 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[17:13:57 WARN]: The server will make no attempt to authenticate usernames. Beware.
[17:13:57 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[17:13:57 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[17:13:57 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[17:13:57 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[17:13:57 INFO]: Preparing level "Login"
[17:13:57 INFO]: -------- World Settings For [Login] --------
[17:13:57 INFO]: Arrow Despawn Rate: 300
[17:13:57 INFO]: View Distance: 4
[17:13:57 INFO]: Item Merge Radius: 4.1
[17:13:57 INFO]: Item Despawn Rate: 4000
[17:13:57 INFO]: Chunks to Grow per Tick: 650
[17:13:57 INFO]: Clear tick list: false
[17:13:57 INFO]: Experience Merge Radius: 6.2
[17:13:57 INFO]: Zombie Aggressive Towards Villager: true
[17:13:57 INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[17:13:57 INFO]: Nerfing mobs spawned from spawners: true
[17:13:57 INFO]: Anti X-Ray: true
[17:13:57 INFO]:        Engine Mode: 1
[17:13:57 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[17:13:57 INFO]:        Replace Blocks: [1, 5]
[17:13:57 INFO]: Mob Spawn Range: 4
[17:13:57 INFO]: Entity Activation Range: An 16 / Mo 14 / Mi 12
[17:13:57 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[17:13:57 INFO]: Cactus Growth Modifier: 100%
[17:13:57 INFO]: Cane Growth Modifier: 100%
[17:13:57 INFO]: Melon Growth Modifier: 100%
[17:13:57 INFO]: Mushroom Growth Modifier: 100%
[17:13:57 INFO]: Pumpkin Growth Modifier: 100%
[17:13:57 INFO]: Sapling Growth Modifier: 100%
[17:13:57 INFO]: Wheat Growth Modifier: 100%
[17:13:57 INFO]: NetherWart Growth Modifier: 100%
[17:13:57 INFO]: Structure Info Saving: true
[17:13:57 INFO]: Hopper Transfer: 10 Hopper Check: 8 Hopper Amount: 1
[17:13:57 INFO]: Sending up to 10 chunks per packet
[17:13:57 INFO]: Random Lighting Updates: false
[17:13:57 INFO]: Max Entity Collisions: 2
[17:13:57 INFO]: Max TNT Explosions: 100
[17:13:57 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[17:13:57 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[17:13:57 INFO]: Preparing start region for level 0 (Seed: 0)
[17:13:58 INFO]: [ProtectWorld] Enabling ProtectWorld v17.728
[17:13:58 WARN]: [ProtectWorld] Default system encoding may have misread config.yml from plugin jar
[17:13:58 INFO]: [特殊世界保护] > 已运行 定制+Q962389099
[17:13:58 INFO]: [SafeLogin] Enabling SafeLogin v1.1.0
[17:13:58 WARN]: [SafeLogin] Default system encoding may have misread config.yml from plugin jar
[17:13:58 INFO]: [SafeLogin] 插件已加载.

[17:13:58 INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.11.1
[17:13:58 INFO]: [PlaceholderAPI] Fetching available expansion information...
[17:13:58 INFO]: [AntiFallDamage] Enabling AntiFallDamage v1.5
[17:13:58 INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[17:13:58 INFO]: [MiraiMC] Mirai working dir: default
[17:13:58 INFO]: [MiraiMC] Starting Mirai-Events listener.
[17:13:58 INFO]: [MiraiMC] Loading auto-login file.
[17:13:58 INFO]: [MiraiMC] Registering commands.
[17:13:58 INFO]: [MiraiMC] Registering events.
[17:13:58 INFO]: [MiraiMC] Initializing SQLite database.
[17:13:58 INFO]: [MiraiMC] Initializing bStats metrics.
[17:13:58 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[17:13:58 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[17:13:58 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[17:13:58 INFO]: [SuperLobby] Enabling SuperLobby v4.3.9
[17:13:58 INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[17:13:58 INFO]:    _____                       _           _     _

[17:13:58 INFO]:   / ____|                     | |         | |   | |

[17:13:58 INFO]:  | (___  _   _ _ __   ___ _ __| |     ___ | |__ | |__  _   _

[17:13:58 INFO]:   \___ \| | | | '_ \ / _ \ '__| |    / _ \| '_ \| '_ \| | | |

[17:13:58 INFO]:   ____) | |_| | |_) |  __/ |  | |___| (_) | |_) | |_) | |_| |

[17:13:58 INFO]:  |_____/ \__,_| .__/ \___|_|  |______\___/|_.__/|_.__/ \__, |

[17:13:58 INFO]:               | |                                       __/ |

[17:13:58 INFO]:               |_|                                      |___/

[17:13:58 INFO]:

[17:13:58 INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[17:13:58 INFO]: [SuperLobby] Deluxe Version: V4.3.9

[17:13:58 INFO]: [SuperLobby] Plugin Create by PedroJM96.

[17:13:58 INFO]: [SuperLobby] Loading configuration...

[17:13:58 INFO]: [SuperLobby] Load config.yml

[17:13:58 INFO]: [SuperLobby] config.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load messages_EN.yml

[17:13:58 INFO]: [SuperLobby] messages_EN.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load spawn.yml

[17:13:58 INFO]: [SuperLobby] spawn.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load chat.yml

[17:13:58 INFO]: [SuperLobby] chat.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load infocommands.yml

[17:13:58 INFO]: [SuperLobby] infocommands.yml loaded.

[17:13:58 INFO]: [SuperLobby] Register info command /help

[17:13:58 INFO]: [SuperLobby] Load customevents.yml

[17:13:58 INFO]: [SuperLobby] customevents.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load items.yml

[17:13:58 INFO]: [SuperLobby] items.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load menus.yml

[17:13:58 INFO]: [SuperLobby] menus.yml loaded.

[17:13:58 INFO]: [SuperLobby] Register command menu /menu

[17:13:58 INFO]: [SuperLobby] Register command menu /game

[17:13:58 INFO]: [SuperLobby] Register command menu /profile

[17:13:58 INFO]: [SuperLobby] Register command menu /shop

[17:13:58 INFO]: [SuperLobby] Load board.yml

[17:13:58 INFO]: [SuperLobby] board.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load announcer.yml

[17:13:58 INFO]: [SuperLobby] announcer.yml loaded.

[17:13:58 INFO]: [SuperLobby] Load firstjoin.yml

[17:13:58 INFO]: [SuperLobby] firstjoin.yml loaded.

[17:13:58 INFO]: [SuperLobby] Register commands...

[17:13:58 INFO]: [SuperLobby] Register main command superlobby

[17:13:58 INFO]: [SuperLobby] Register sub-command setspawn

[17:13:58 INFO]: [SuperLobby] Register sub-command setspawnpermission

[17:13:58 INFO]: [SuperLobby] Register sub-command remspawn

[17:13:58 INFO]: [SuperLobby] Register sub-command reload

[17:13:58 INFO]: [SuperLobby] Register sub-command help

[17:13:58 INFO]: [SuperLobby] Register sub-command openmenu

[17:13:58 INFO]: [SuperLobby] Hooked Vault Permissions

[17:13:58 INFO]: [SuperLobby] Hooked ProtocolLib

[17:13:58 INFO]: [SuperLobby] Hooked PlaceholderAPI

[17:13:58 INFO]: [SuperLobby] A total of 4 menus were loaded.

[17:13:58 INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

[17:13:58 INFO]: [LagAssist] Enabling LagAssist v2.28.0
[17:13:58 INFO]: §2§lLag§f§lAssist §e? §fEnabling Systems:
[17:13:58 INFO]:     §e[§a?§e] §fEconomy manager
[17:13:58 INFO]:     §e[§a?§e] §fSmart Mob Tools.
[17:13:58 INFO]:     §e[§a?§e] §fMicroFeatures.
[17:13:58 INFO]:     §e[§a?§e] §fHopper Manager.
[17:13:58 INFO]:     §e[§a?§e] §fRedstone Culler.
[17:13:58 INFO]:     §e[§a?§e] §fPhysics-Tweaker.
[17:13:58 INFO]:     §e[§a?§e] §fLag Monitor.
[17:13:58 INFO]:     §e[§a?§e] §fMapVisualizer.
[17:13:58 INFO]:     §e[§a?§e] §fChunk Analyser.
[17:13:58 INFO]:     §e[§a?§e] §fChunk Limiter.
[17:13:58 INFO]:     §e[§a?§e] §fStatsAnalyse.
[17:13:58 INFO]:     §e[§a?§e] §fSpawner Manager.
[17:13:58 INFO]:     §e[§a?§e] §fGUI.
[17:13:58 INFO]:     §e[§a?§e] §fInjecting PacketListener.
[17:13:58 INFO]:     §e[§a?§e] §fAPI Tools.
[17:13:58 INFO]: [Citizens] Enabling Citizens v2.0.24-SNAPSHOT (build 1605)
[17:13:58 ERROR]: [Citizens] Missing preferred location bundle.
[17:13:58 INFO]: [Citizens] Could not fetch NMS field modifiers: [[modifiers.
[17:13:58 INFO]: [AuthMe] Enabling AuthMe v5.6.0-beta2-b2453
[17:13:59 INFO]: [AuthMe] SQLite Setup finished
[17:13:59 INFO]: [AuthMe] Hooked into Vault!
[17:13:59 WARN]: [AuthMe] Failed to load GeoLiteAPI database [InvalidDatabaseException]: Could not find a MaxMind DB metadata marker in this file (GeoLite2-Country.mmdb). Is this a valid MaxMind DB file?
[17:13:59 WARN]: [AuthMe] Failed to read welcome.txt file: [MalformedInputException]: Input length = 1
[17:13:59 WARN]: [AuthMe] Failed to compile pattern '[a-zA-Z0-9_- -.]*' - defaulting to allowing everything
[17:13:59 INFO]: [AuthMe] AuthMe 5.6.0-beta2 build n.2453 successfully enabled!
[17:13:59 INFO]: [CommandNPC] Enabling CommandNPC v1.9.1
[17:13:59 INFO]: [CommandNPC] Vault compatible economy not found! Economy support for CommandNPC has been disabled.

[17:13:59 INFO]: [CommandNPC] Initiating Database

[17:13:59 INFO]: [CommandNPC] Injecting command info into Citizens.

[17:13:59 INFO]: [CommandNPC] Setting up BungeeCord

[17:13:59 INFO]: [CommandNPC] Loading commands complete!

[17:13:59 INFO]: [CommandNPC] CommandNPC successfully loaded!

[17:13:59 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:13:59 INFO]: Done (1.706s)! For help, type "help" or "?"
[17:13:59 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[17:13:59 INFO]: [MiraiMC] Checking update...
[17:13:59 INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 656880754 Protocol: ANDROID_PAD
[17:13:59 INFO]: [MiraiMC] 登录新的机器人账号: 656880754, 协议: ANDROID_PAD
[17:13:59 INFO]: [SuperLobby] An update was found! for SuperLobby. Please update to recieve latest version. download: https://www.spigotmc.org/resources/20400

[17:13:59 INFO]: [Citizens] Loaded 2 NPCs.
[17:13:59 INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[17:13:59 INFO]: [Vault] Checking for Updates ...
[17:13:59 INFO]: 0 placeholder hook(s) registered!

[17:14:00 INFO]: §2§lLag§f§lAssist §e? §fYou are up to date with LagAssist.
[17:14:00 WARN]: [MiraiMC] null
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
        at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
        Caused by: java.nio.channels.UnresolvedAddressException
                at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
                at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
                at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
[17:14:20 INFO]: [Vault] There was an issue attempting to check for the latest version.
[17:14:20 INFO]: [Vault] No new version available
[17:14:23 INFO]: [MiraiMC] You are using the latest version!
>miraimc
[17:17:15 INFO]: This server is running MiraiMC version 1.6.1 by DreamVoid

[17:17:15 INFO]: For help, type /miraimc help

>
```

### 额外说明

JDK17.2
WINserver2019

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by xiaobao4909** [comment]
JDK8
JDK11测试过均无法登录

**Comment by xiaobao4909** [comment]
JDK16经测试也无法登录

**Comment by DreamVoid** [comment]
自行检查服务器网络是否正常

**Comment by xiaobao4909** [comment]
正常的啊 是要开放什么端口吗

**Comment by xiaobao4909** [comment]
群组可以登录 就Bukkit不能登录 还能是网的问题吗
