### ISSUE TITLE
登录失败刷屏报错

### ISSUE THREAD

**Issue by MCchenxi** [DreamVoid/MiraiMC#150]
### 问题描述

插件加载无报错登录账号过了几秒就开始刷屏报错

### 复现方法

输入 /mirai login 账号 密码登录之后就开始疯狂刷报错

### 服务端类型

Bukkit

### 服务端版本

spigot-1.12.2

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
[00:33:04] [Server thread/INFO]: [0;37;1m[ [0;32;1m系统 [0;37;1m] [0;32;1m地面上的垃圾将会在 [0;37;1m60 [0;32;1m秒后被清理..[m
[08:26:57] [Server thread/INFO]: This server is running MiraiMC version 1.6.1 by DreamVoid[m
[08:26:57] [Server thread/INFO]: For help, type /mirai help[m
[08:27:02] [Server thread/INFO]: [0;31;1m无效的参数！用法: /mirai login <账号> <密码> [协议][m
[08:31:50] [Craft Scheduler Thread - 546/INFO]: [MiraiMC] 登录新的机器人账号: 2823054956, 协议: ANDROID_PHONE
[08:32:55] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[08:32:55] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[08:32:57] [Server thread/INFO]: Unknown command. Type "/help" for help.[m
[08:33:02] [Server thread/INFO]: This server is running MiraiMC version 1.6.1 by DreamVoid[m
[08:33:02] [Server thread/INFO]: For help, type /miraimc help[m
[08:33:05] [DefaultDispatcher-worker-1/WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:123)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.getDefaultInitialPublicKey(ECDH.kt:132)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.AccountSecretsImpl(AccountSecretsManager.kt:146)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:154)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
[08:33:05] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: Caused by: java.util.jar.JarException: file:/D:/CXMC/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.11.0-M2.2.jar has unsigned entries - net/mamoe/mirai/internal/MiraiImpl$downloadMultiMsgTransmit$$inlined$read$1.class
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:510)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:371)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JarVerifier.verify(JarVerifier.java:297)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
[08:33:06] [DefaultDispatcher-worker-1/WARN]: 	... 29 more
[08:33:07] [Server thread/INFO]: [0;33;22m[21mMiraiMC[m [0;36;1m插件帮助菜单[m
[08:33:07] [Server thread/INFO]: [0;33;22m/miraimc bind:[m 玩家绑定菜单[m
[08:33:07] [Server thread/INFO]: [0;33;22m/miraimc reload:[m 重新加载插件[m
[08:33:07] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[08:33:10] [DefaultDispatcher-worker-1/ERROR]: [MiraiMC] Failed to fetch ECDH public key from server, using default key instead
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
	at io.ktor.utils.io.bits.MemoryJvmKt.sliceSafe(MemoryJvm.kt:211) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.utils.io.bits.Memory.slice-SK3TCg8(MemoryJvm.kt:47) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.utils.io.charsets.CharsetJVMKt.encodeImpl(CharsetJVM.kt:356) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.utils.io.charsets.EncodingKt.encodeToImpl(Encoding.kt:204) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.utils.io.charsets.EncodingKt.encode(Encoding.kt:62) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.utils.io.charsets.EncodingKt.encode$default(Encoding.kt:57) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.CodecsKt.encodeURLParameter(Codecs.kt:123) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:68) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default(_Collections.kt:3341) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:108) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:90) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.URLUtilsKt.appendUrlFullPath(URLUtils.kt:101) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.URLUtilsKt.getFullPath(URLUtils.kt:79) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.http.Url.toString(URLBuilder.kt:169) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:183) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:71) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
[08:33:17] [nioEventLoopGroup-2-2/ERROR]: [MiraiMC] Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {353=[B@1866f345}
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368) ~[mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.11.0-M2.2.jar:2.11.0-M2.2]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_331]
[08:33:17] [DefaultDispatcher-worker-1/WARN]: [MiraiMC] null
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {353=[B@1866f345}
	at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188) ~[?:?]
	at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368) ~[?:?]
	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) ~[?:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[spigot-1.12.2.jar:git-Spigot-e8ded36-acbc348]
	at java.lang.Thread.run(Unknown Source) ~[?:1.8.0_331]
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
https://github.com/mamoe/mirai/issues/1649
