### ISSUE TITLE
Bukkit版无法登录 网络连接正常

### ISSUE THREAD

**Issue by xiaobao4909** [DreamVoid/MiraiMC#151]
### 问题描述

网络连接正常 群组服可以登录 Bukkit就是不能登录

### 复现方法

1. 登陆机器人

### 服务端类型

Bukkit

### 服务端版本

1.8.8

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
Loading libraries, please wait...
[12:59:16 INFO]: Starting minecraft server version 1.8.8
[12:59:16 INFO]: Loading properties
[12:59:16 INFO]: Default game type: ADVENTURE
[12:59:16 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-741a1bd (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[12:59:16 INFO]: Debug logging is disabled
[12:59:16 INFO]: Server Ping Player Sample Count: 12

[12:59:16 INFO]: Using 4 threads for Netty based IO
[12:59:16 INFO]: Generating keypair
[12:59:16 INFO]: Starting Minecraft server on 127.0.0.1:10000
[12:59:16 INFO]: Using default channel type
[12:59:16 INFO]: Your platform does not provide complete low-level API for accessing direct buffers reliably. Unless explicitly requested, heap buffer will always be preferred to avoid potential system unstability.
[12:59:17 INFO]: Set PluginClassLoader as parallel capable
[12:59:17 INFO]: [MiraiMC] Loading MiraiMC v1.6.1
[12:59:17 WARN]: [MiraiMC] Default system encoding may have misread config.yml from plugin jar
[12:59:18 INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[12:59:18 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.0-M2.2.jar
[12:59:18 INFO]: [MiraiMC] Loading library mirai-core-all-2.11.0-M2.2.jar
[12:59:18 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[12:59:18 WARN]: The server will make no attempt to authenticate usernames. Beware.
[12:59:18 WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[12:59:18 WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[12:59:18 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[12:59:18 INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[12:59:18 INFO]: Preparing level "Login"
[12:59:18 INFO]: -------- World Settings For [Login] --------
[12:59:18 INFO]: Arrow Despawn Rate: 300
[12:59:18 INFO]: Allow Zombie Pigmen to spawn from portal blocks: false
[12:59:18 INFO]: Item Despawn Rate: 4000
[12:59:18 INFO]: Item Merge Radius: 4.1
[12:59:18 INFO]: Mob Spawn Range: 4
[12:59:18 INFO]: Anti X-Ray: true
[12:59:18 INFO]:        Engine Mode: 1
[12:59:18 INFO]:        Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[12:59:18 INFO]:        Replace Blocks: [1, 5]
[12:59:18 INFO]: Nerfing mobs spawned from spawners: true
[12:59:18 INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[12:59:18 INFO]: Cactus Growth Modifier: 100%
[12:59:18 INFO]: Cane Growth Modifier: 100%
[12:59:18 INFO]: Melon Growth Modifier: 100%
[12:59:18 INFO]: Mushroom Growth Modifier: 100%
[12:59:18 INFO]: Pumpkin Growth Modifier: 100%
[12:59:18 INFO]: Sapling Growth Modifier: 100%
[12:59:18 INFO]: Wheat Growth Modifier: 100%
[12:59:18 INFO]: NetherWart Growth Modifier: 100%
[12:59:18 INFO]: Entity Activation Range: An 16 / Mo 14 / Mi 12
[12:59:18 INFO]: Sending up to 10 chunks per packet
[12:59:18 INFO]: Random Lighting Updates: false
[12:59:18 INFO]: Max Entity Collisions: 2
[12:59:18 INFO]: Hopper Transfer: 10 Hopper Check: 8 Hopper Amount: 1
[12:59:18 INFO]: Structure Info Saving: true
[12:59:18 INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617
[12:59:18 INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[12:59:18 INFO]: Max TNT Explosions: 100
[12:59:18 INFO]: View Distance: 4
[12:59:18 INFO]: Chunks to Grow per Tick: 650
[12:59:18 INFO]: Clear tick list: false
[12:59:18 INFO]: Experience Merge Radius: 6.2
[12:59:18 INFO]: Zombie Aggressive Towards Villager: true
[12:59:18 INFO]: Preparing start region for level 0 (Seed: 0)
[12:59:19 INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[12:59:19 INFO]: [MiraiMC] Mirai working dir: default
[12:59:19 INFO]: [MiraiMC] Starting Mirai-Events listener.
[12:59:19 INFO]: [MiraiMC] Loading auto-login file.
[12:59:19 INFO]: [MiraiMC] Registering commands.
[12:59:19 INFO]: [MiraiMC] Registering events.
[12:59:19 INFO]: [MiraiMC] Initializing SQLite database.
[12:59:19 INFO]: [MiraiMC] Initializing bStats metrics.
[12:59:19 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[12:59:19 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[12:59:19 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[12:59:19 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:59:19 INFO]: Done (1.020s)! For help, type "help" or "?"
[12:59:19 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[12:59:19 INFO]: [MiraiMC] Checking update...
[12:59:20 INFO]: [MiraiMC] You are using the latest version!
>mirai login 656880754 xiaobao4909
[12:59:43 INFO]: [MiraiMC] 登录新的机器人账号: 656880754, 协议: ANDROID_PHONE
[12:59:44 WARN]: [MiraiMC] null
java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
        at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling
        Caused by: java.nio.channels.UnresolvedAddressException
                at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
                at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816) ~[?:?]
                at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:?]
                at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[Server.jar:git-Spigot-21fe707-741a1bd]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
>
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by xiaobao4909** [comment]
怎么解决啊 我网络正常啊
