### ISSUE TITLE
关于插件编码问题

### ISSUE THREAD

**Issue by 1160706050** [DreamVoid/MiraiMC#156]
### 问题描述

![image](https://user-images.githubusercontent.com/37466008/172542862-1b399d40-796b-4281-9587-1c193fe0efa9.png)

MiraiMC应该是使用ANSI编码进行编写。

建议改为使用UTF-8编码

### 复现方法

Windows 平台 加载Minecraft服务端MiraiMC插件乱码

### 服务端类型

Bukkit

### 服务端版本

Spigot 1.19

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
[14:00:11] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[14:00:11] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[14:00:11] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[14:00:11] [Server thread/INFO]: [MiraiMC] Loading auto-login file.
[14:00:11] [Server thread/INFO]: [MiraiMC] Registering commands.
[14:00:11] [Server thread/INFO]: [MiraiMC] Registering events.
[14:00:11] [Server thread/INFO]: [MiraiMC] Initializing SQLite database.
[14:00:11] [Server thread/INFO]: [MiraiMC] Initializing bStats metrics.
[14:00:11] [Server thread/WARN]: [MiraiMC] 纭繚鎮ㄦ鍦ㄤ娇鐢ㄥ紑婧愮殑MiraiMC鎻掍欢锛屾湭鐭ユ潵婧愮殑鎻掍欢鍙兘浼氱洍鍙栨偍鐨勮处鍙凤紒
[14:00:11] [Server thread/WARN]: [MiraiMC] 璇峰缁堜粠Github鎴栦綔鑰呮寚瀹氱殑鍏朵粬閫斿緞涓嬭浇鎻掍欢: https://github.com/DreamVoid/MiraiMC
[14:00:11] [Server thread/INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[14:00:11] [Server thread/INFO]: [McZoo] Enabling MiraiMC-McZoo v1.0-SNAPSHOT
[14:00:11] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[14:00:11] [Server thread/INFO]: Done (11.318s)! For help, type "help"
[14:00:11] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] Checking update...
[14:00:11] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[14:00:12] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] You are using the latest version!
>plugins
[14:00:19] [Server thread/INFO]: Plugins (2): MiraiMC, MiraiMC-McZoo
>mirai
[14:00:25] [Server thread/INFO]: This server is running MiraiMC version 1.6.1 by DreamVoid
[14:00:25] [Server thread/INFO]: For help, type /mirai help
>mirai help
[14:00:27] [Server thread/INFO]: MiraiMC 鏈哄櫒浜哄府鍔╄彍鍗
[14:00:27] [Server thread/INFO]: /mirai login <璐﹀彿> <瀵嗙爜> [鍗忚]: 鐧诲綍涓€涓満鍣ㄤ汉
[14:00:27] [Server thread/INFO]: /mirai logout <璐﹀彿>: 閫€鍑轰竴涓満鍣ㄤ汉
[14:00:27] [Server thread/INFO]: /mirai list: 鏌ョ湅褰撳墠瀛樺湪鐨勬満鍣ㄤ汉
[14:00:27] [Server thread/INFO]: /mirai sendfriendmessage <璐﹀彿> <濂藉弸> <娑堟伅>: 鍚戞寚瀹氬ソ鍙嬪彂閫佺鑱婃秷鎭
[14:00:27] [Server thread/INFO]: /mirai sendgroupmessage <璐﹀彿> <缇ゅ彿> <娑堟伅>: 鍚戞寚瀹氱兢鍙戦€佺兢鑱婃秷鎭
[14:00:27] [Server thread/INFO]: /mirai sendfriendnudge <璐﹀彿> <濂藉弸>: 鍚戞寚瀹氬ソ鍙嬪彂閫佹埑涓€鎴
[14:00:27] [Server thread/INFO]: /mirai checkonline <璐﹀彿>: 妫€鏌ユ寚瀹氱殑鏈哄櫒浜烘槸鍚﹀湪绾
[14:00:27] [Server thread/INFO]: /mirai autologin add <璐﹀彿> <瀵嗙爜> [鍗忚]: 娣诲姞涓€涓嚜鍔ㄧ櫥褰曡处鍙
[14:00:27] [Server thread/INFO]: /mirai autologin list: 鏌ョ湅鑷姩鐧诲綍璐﹀彿鍒楄〃
[14:00:27] [Server thread/INFO]: /mirai autologin remove <璐﹀彿>: 鍒犻櫎涓€涓嚜鍔ㄧ櫥褰曡处鍙
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by 1160706050** [comment]
> https://github.com/DreamVoid/MiraiMC/blob/d935ae86800d806818c3de4086b6d431b1b0cbd2/pom.xml#L60
> 
> 
> 是你的终端用错编码了

好的，谢谢！我已解决，在终端添加chcp 65001改为utf-8编码了

**Comment by 1160706050** [comment]
> https://github.com/DreamVoid/MiraiMC/blob/d935ae86800d806818c3de4086b6d431b1b0cbd2/pom.xml#L60
> 
> 
> 是你的终端用错编码了

我还有一个错误需要您看一下，视乎是关于JceStruct

报错如下：

[02:53:14] [Server thread/INFO]: Done (9.116s)! For help, type "help"
[02:53:14] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] Checking update...
[02:53:14] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[02:53:14] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 1720107609 Protocol: ANDROID_PHONE
[02:53:14] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] 登录新的机器人账号: 1720107609, 协议: ANDROID_PHONE
[02:53:16] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Server list: 180.102.191.97:8080, 183.47.98.25:8080, 42.81.194.99:443, 42.81.184.206:443, msfwifi.3g.qq.com:8080, 183.47.99.24:443, 123.151.54.194:80, 183.47.102.193:14000, 222.94.109.123:443, 180.101.246.26:80.
[02:53:18] [DefaultDispatcher-worker-2/WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:181)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:230)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:225)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:107)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:122)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$startState$2.invokeSuspend(NettyNetworkHandler.kt:274)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[02:53:18] [DefaultDispatcher-worker-2/WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/D:/Game/Minecraft/Server/Spigot%20Test/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.11.1.jar is not signed.
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
[02:53:18] [DefaultDispatcher-worker-2/WARN]:   ... 39 more
