### ISSUE TITLE
NukkitX 1.0加载1.6.1失败

### ISSUE THREAD

**Issue by FrydenSoul** [DreamVoid/MiraiMC#161]
### 问题描述

加载MiraiMC 1.6.1及相关依赖插件报错

### 复现方法

1. 启动服务端

### 服务端类型

Nukkit

### 服务端版本

Nukkit git-735c8b2 API 1.0.14 协议版本527

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
16:47:58 [INFO ] Loading nukkit.yml ...
16:47:59 [INFO ] Loading server.properties ...            16:47:59 [INFO ] 将 中文(简体) (chs) 设置为基本语言
16:47:59 [INFO ] 正在启动 Minecraft: BE v1.19.0           16:47:59 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
16:47:59 [INFO ] 正在于 0.0.0.0:19132 启动服务器          16:47:59 [INFO ] 此服务器正在运行 Nukkit git-735c8b2 版本 "" (API 1.0.14)                                           16:47:59 [INFO ] Nukkit 根据 GPL 许可发行
16:47:59 [INFO ] Loading runtime items...                 16:48:00 [INFO ] Loading recipes...                       16:48:00 [INFO ] Loaded 1509 recipes.
16:48:00 [INFO ] 成功加载 0 个资源包
16:48:00 [WARN ] Failed to find a usable hardware address from the network interfaces; using random bytes: 42:ed:0c:aa:e5:ec:66:4a
16:48:00 [INFO ] 读取 WatchDog v1.0.0 中
16:48:00 [INFO ] 读取 MiraiMC v1.6.1 中
16:48:00 [WARN ] [MiraiMC] Unable to download mirai core from remote server(java.net.UnknownHostException: maven.aliyun.com), try to use local core.
16:48:00 [WARN ] [MiraiMC] An error occurred while loading plugin.
> java.net.UnknownHostException: maven.aliyun.com
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
        at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
        at java.net.URL.openStream(URL.java:1045)
        at me.dreamvoid.miraimc.internal.MiraiLoader.downloadFile(MiraiLoader.java:178)
        at me.dreamvoid.miraimc.internal.MiraiLoader.getLibraryVersionMaven(MiraiLoader.java:146)
        at me.dreamvoid.miraimc.internal.MiraiLoader.loadMiraiCore(MiraiLoader.java:27)
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onLoad(NukkitPlugin.java:34)
        at cn.nukkit.plugin.JavaPluginLoader.initPlugin(JavaPluginLoader.java:109)
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:57)
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:269)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124)
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120)
        at cn.nukkit.Server.<init>(Server.java:505)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
16:48:00 [INFO ] 读取 MobPlugin v1.21.6 中
16:48:00 [INFO ] 读取 VanillaCommandBlock v1.0.0 中
16:48:00 [INFO ] 读取 VanillaCommands v1.0.1 中
16:48:00 [INFO ] 读取 Link2QQ v1.1 中
16:48:00 [INFO ] 读取 Chat2QQ v1.5 中
16:48:00 [INFO ] 开启 MobPlugin v1.21.6 中
16:48:01 [INFO ] 开启 VanillaCommandBlock v1.0.0 中
16:48:01 [INFO ] 准备世界 "world" 中
16:48:01 [INFO ] Preparing start region for level "world"
16:48:01 [INFO ] 准备世界 "nether" 中
16:48:01 [INFO ] Preparing start region for level "nether"
16:48:01 [INFO ] 开启 WatchDog v1.0.0 中
16:48:01 [INFO ] [WatchDog] Loading.....
16:48:01 [INFO ] [WatchDog] WATCHDOG FREE VERSION v1.1.0
16:48:01 [INFO ] [WatchDog] Connect the server...
> java.io.IOException: Cannot run program "sudo": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
        at net.fap.watchdog.WatchDog.getLinuxCPUSerial(我 爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你义中国化最新成果是党党领导中国特色社会主.java:4688)
        at net.fap.watchdog.WatchDog.onEnable(我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你义中国化最新成果是党党领导中国特色社会主.java:17857)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436)
        at cn.nukkit.Server.enablePlugin(Server.java:750)
        at cn.nukkit.Server.enablePlugins(Server.java:739)
        at cn.nukkit.Server.<init>(Server.java:582)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more
16:48:01 [INFO ] [WatchDog] [CLIENT] -> Linux ServerID:
> java.io.IOException: Cannot run program "sudo": error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at java.lang.Runtime.exec(Runtime.java:450)
        at java.lang.Runtime.exec(Runtime.java:347)
        at net.fap.watchdog.WatchDog.getLinuxCPUSerial(我 爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你义中国化最新成果是党党领导中国特色社会主.java:4688)
        at net.fap.watchdog.WatchDog.onEnable(我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你我爱你义中国化最新成果是党党领导中国特色社会主.java:25838)
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89)
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117)
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436)
        at cn.nukkit.Server.enablePlugin(Server.java:750)
        at cn.nukkit.Server.enablePlugins(Server.java:739)
        at cn.nukkit.Server.<init>(Server.java:582)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:247)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 12 more
16:48:01 [INFO ] [WatchDog] Loading WatchDog Config
16:48:01 [WARN ] [WatchDog] Load Module WatchDogSystem v1.0.9
16:48:01 [WARN ] [WatchDog] Load Module BanWave v1.0.0
16:48:01 [INFO ] [WatchDog] Load WatchDog Entity v1.0.0
16:48:01 [WARN ] [WatchDog] Load Module Moving v1.1.5
16:48:01 [WARN ] [WatchDog] Load Module Player v1.0.3 [10]
16:48:01 [WARN ] [WatchDog] Load Module Combat v1.0.7
16:48:01 [WARN ] [WatchDog] Load Module AutoBan v0.0.1
16:48:01 [WARN ] [WatchDog] Register blocks Minecraft:BE 1.16.20
16:48:01 [INFO ] 开启 MiraiMC v1.6.1 中
16:48:01 [INFO ] [MiraiMC] Mirai working dir: default
16:48:01 [INFO ] [MiraiMC] Starting Mirai-Events listener.
16:48:01 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NullPointerException
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NullPointerException
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:55) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
16:48:01 [INFO ] 关闭 MiraiMC v1.6.1 中
16:48:01 [INFO ] [MiraiMC] Stopping bot event listener.
16:48:01 [ERROR] Throwing
java.lang.NullPointerException: null
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onDisable(NukkitPlugin.java:126) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:510) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:442) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
16:48:01 [INFO ] 开启 VanillaCommands v1.0.1 中
16:48:01 [INFO ] 开启 Link2QQ v1.1 中
16:48:01 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/Message
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/Message
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_152]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:632) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:620) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvent(PluginManager.java:612) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvents(PluginManager.java:597) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at me.dreamvoid.link2qq.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:29) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.message.data.Message
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_152]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:632) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:620) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvent(PluginManager.java:612) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvents(PluginManager.java:597) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at me.dreamvoid.link2qq.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:29) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
16:48:01 [INFO ] 关闭 Link2QQ v1.1 中
16:48:01 [INFO ] 开启 Chat2QQ v1.5 中
16:48:01 [ERROR] Throwing
java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/Message
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/message/data/Message
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_152]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:632) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:620) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvent(PluginManager.java:612) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvents(PluginManager.java:597) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at me.dreamvoid.chat2qq.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:29) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.message.data.Message
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:44) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:28) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_152]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_152]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_152]
        at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_152]
        at cn.nukkit.plugin.PluginManager.getRegistrationClass(PluginManager.java:632) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.getEventListeners(PluginManager.java:620) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvent(PluginManager.java:612) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.registerEvents(PluginManager.java:597) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at me.dreamvoid.chat2qq.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:29) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
16:48:01 [INFO ] 关闭 Chat2QQ v1.5 中
16:48:01 [INFO ] 启动 GS4 状态监听器
16:48:01 [INFO ] 将 Query 端口设置为 19132
16:48:01 [INFO ] Query 运行于 0.0.0.0:19132
16:48:01 [INFO ] 默认游戏模式：生存模式
16:48:01 [INFO ] 启动完成 (2.597s)！如需帮助，请输入 "help" 或 "?"
> plugins
16:48:04 [INFO ] 插件 (7)：WatchDog v1.0.0, MiraiMC v1.6.1, MobPlugin v1.21.6, VanillaCommandBlock v1.0.0, VanillaCommands v1.0.1, Link2QQ v1.1, Chat2QQ v1.5
> ver
16:48:11 [INFO ] 此服务器正在运行 Nukkit git-735c8b2 「」API 版本 1.0.14 的 Minecraft: BE v1.19.0 (协议版本 527)
```

### 额外说明

使用依赖于MiraiMC的插件:
Link2QQ Chat2QQ

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
检查服务器的网络连接。插件无法连接到阿里云的maven仓库下载mirai core。

**Comment by FrydenSoul** [comment]
已解决，原因为公网服务失效，服务器在内网运行。
