### ISSUE TITLE
今天（2022.6.18）插件出现了不能正常启动的问题

### ISSUE THREAD

**Issue by KaridaLee** [DreamVoid/MiraiMC#162]
### 问题描述

今天早上服务器自动重启的时候插件还能正常使用，今天晚上服务器重启了就显示两条报错，我尝试在Github在下载最新版本，还是出现那两条报错，在此之前我已经删除了配置文件文件夹，重新生成还是出现了那种问题，但是配置文件正常生成，为了排除是我电脑的问题我用了其他设备，都出现了这种问题，我也试过只装这一个插件，也出现报错，我想问一下处理办法是什么，或者是内部问题？

### 复现方法

1.重启就会出现问题，无论什么版本，试过BC端，bukkit端都一样

### 服务端类型

Bukkit

### 服务端版本

PurPur-1.18.2

### MiraiMC 插件版本

1.6.1正式版

### 服务端日志

```text
[22:28:12 INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[22:28:12 INFO]: [MiraiMC] Mirai working dir: default
[22:28:12 INFO]: [MiraiMC] Starting Mirai-Events listener.
[22:28:12 ERROR]: Error occurred while enabling MiraiMC v1.6.1 (Is it up to date?)
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:86) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:56) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[22:28:12 INFO]: [MiraiMC] Disabling MiraiMC v1.6.1
[22:28:12 INFO]: [MiraiMC] Stopping bot event listener.
[22:28:12 ERROR]: Error occurred while disabling MiraiMC v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:165) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:134) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### 额外说明

Java版本是17.0.2，只是突然出现这个问题，以前都没有出现过类似问题

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by FrydenSoul** [comment]
我两小时前突然开始出现这个问题
版本 Nukkit git-735c8b2,API 1.0.14
`22:52:05 [INFO ] 开启 MiraiMC v1.6.1 中
22:52:05 [INFO ] [MiraiMC] Mirai working dir: default
22:52:05 [INFO ] [MiraiMC] Starting Mirai-Events listener.
22:52:05 [ERROR] Throwing
java.lang.RuntimeException: java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]
Caused by: java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[?:?]
        at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[?:?]
        at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[?:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[?:?]
        at me.dreamvoid.miraimc.nukkit.MiraiEvent.startListenEvent(MiraiEvent.java:91) ~[?:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:55) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[nukkit-1.0-SNAPSHOT.jar:?]
        ... 4 more
22:52:05 [INFO ] 关闭 MiraiMC v1.6.1 中
22:52:05 [INFO ] [MiraiMC] Stopping bot event listener.
22:52:05 [ERROR] Throwing
java.lang.NullPointerException: null
        at me.dreamvoid.miraimc.nukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:170) ~[?:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onDisable(NukkitPlugin.java:126) ~[?:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:91) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:132) ~[nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:510) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:442) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:750) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:739) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Server.<init>(Server.java:582) [nukkit-1.0-SNAPSHOT.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [nukkit-1.0-SNAPSHOT.jar:?]`

**Comment by poikcue** [comment]
`[23:07:53] [Server thread/ERROR]: Error occurred while enabling MiraiMC v1.6.1 (Is it up to date?)
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
	at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:86) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:56) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[23:07:53] [Server thread/INFO]: [MiraiMC] Disabling MiraiMC v1.6.1
[23:07:53] [Server thread/INFO]: [MiraiMC] Stopping bot event listener.
[23:07:53] [Server thread/ERROR]: Error occurred while disabling MiraiMC v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:165) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:134) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]`

这是我的报错。我也有类似问题，不知道是不是我写的事

**Comment by poikcue** [comment]
这个确实是插件的问题。
![image](https://user-images.githubusercontent.com/65440607/174445340-06834f7e-13a3-44f3-a61a-227f9654a0c2.png)
这是我刚才本地专门为这个事情创建的服务器。全新。
[latest.log](https://github.com/DreamVoid/MiraiMC/files/8933870/latest.log)
这里是最后一次的日志。
插件文件夹内只有miraimc，配置文件没有动，没有第三方插件。

**Comment by seyink** [comment]
我也突然遇到了这个问题，我尝试升级降级插件版本删掉配置文件重新生成还是没有办法使用，之前一直在用没有任何问题，最近也没有修改过这个插件的配置。
[02:05:00 INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[02:05:00 INFO]: [MiraiMC] Mirai working dir: default
[02:05:00 INFO]: [MiraiMC] Starting Mirai-Events listener.
[02:05:00 ERROR]: Error occurred while enabling MiraiMC v1.6.1 (Is it up to date?)
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:86) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:56) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:05:00 INFO]: [MiraiMC] Disabling MiraiMC v1.6.1
[02:05:00 INFO]: [MiraiMC] Stopping bot event listener.
[02:05:00 ERROR]: Error occurred while disabling MiraiMC v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:165) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:134) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:538) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:501) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:562) ~[paper-1.18.1.jar:git-Paper-216]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:476) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:736) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1211) ~[paper-1.18.1.jar:git-Paper-216]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-216]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by FrydenSoul** [comment]
@DreamVoid 这个issue为什么无效啊

**Comment by PrideIII** [comment]
me too...请问有解决方法了吗?

**Comment by CCBlueX666** [comment]
我也是有这个问题了

**Comment by CCBlueX666** [comment]
@DreamVoid 为什么issue被关闭了，既然大家都遇到了这个问题

**Comment by CCBlueX666** [comment]
我也是一模一样的报错，尝试了使用action里最新版也没用

**Comment by CCBlueX666** [comment]
@DreamVoid 为什么这个issue无效了呢，能否说明一下

**Comment by DiamBlog** [comment]
我也是一样的报错
![Uploading Screenshot_20220619-085210_JuiceSSH.png…]()

**Comment by KaridaLee** [comment]
@DreamVoid 给个回复好吗，这个问题是大范围的那种，我们这种普通玩家真的没办法解决

**Comment by DiamBlog** [comment]
@DreamVoid，已经不止一个服务器反应出现这样的问题了，麻烦看一下谢谢
![Screenshot_20220619-085210_JuiceSSH](https://user-images.githubusercontent.com/71549402/174461957-f718c0dd-9e5d-4ba5-8306-7943ee20d882.png)

**Comment by DiamBlog** [comment]
> @DreamVoid 给个回复好吗，这个问题是大范围的那种，我们这种普通玩家真的没办法解决

你尝试重发issue吧，你先阅读注意事项，按规定发issue

**Comment by KaridaLee** [comment]
> > @DreamVoid 给个回复好吗，这个问题是大范围的那种，我们这种普通玩家真的没办法解决
> 
> 你尝试重发issue吧，你先阅读注意事项，按规定发issue

好吧，我重新发一次

**Comment by DreamVoid** [comment]
> @DreamVoid 这个issue为什么无效啊

# 你说呢
