### ISSUE TITLE
关于近期发生大范围插件不能成功启动的问题反馈

### ISSUE THREAD

**Issue by KaridaLee** [DreamVoid/MiraiMC#163]
### 问题描述

近两天插件在启动的时候都显示错误，我尝试在Github在下载最新或者旧版本，还是出现那两条报错，在此之前我已经删除了配置文件文件夹，重新生成还是出现了那种问题，但是配置文件正常生成，为了排除是我电脑的问题我用了其他设备，都出现了这种问题，我也试过只装这一个插件，也出现报错，我想问一下处理办法是什么，或者是内部问题？

### 复现方法

1. 加载插件就会出现问题

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1628 (MC 1.18.2*)

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
[09:19:49 INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[09:19:49 INFO]: [MiraiMC] Verifying mirai-core-all-2.12.0-RC.jar
[09:19:50 INFO]: [MiraiMC] Loading library mirai-core-all-2.12.0-RC.jar
[09:19:53 INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[09:19:53 INFO]: [MiraiMC] Mirai working dir: default
[09:19:53 INFO]: [MiraiMC] Starting Mirai-Events listener.
[09:19:54 ERROR]: Error occurred while enabling MiraiMC v1.6.1 (Is it up to date?)
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
        at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:86) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:56) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
[09:19:54 INFO]: [MiraiMC] Disabling MiraiMC v1.6.1
[09:19:54 INFO]: [MiraiMC] Stopping bot event listener.
[09:19:54 ERROR]: Error occurred while disabling MiraiMC v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
        at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:165) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:134) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:669) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1179) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:320) ~[purpur-1.18.2.jar:git-Purpur-1628]
        at java.lang.Thread.run(Unknown Source) ~[?:?]
```

### 额外说明

这种问题是大范围的，很多服主都表示出现了这种问题，而且所有版本都没用，BC Nukkit Bukkit都是一样的报错，但是配置文件都能被加载，对不起我漠视了版规重新发了一遍，但是希望作者能重视起来，最好能给一条回复，让我们知道插件的修复进展或者问题所在

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
# 关于你们到现在没有一个人按照我的要求开issue这件事

**Comment by KaridaLee** [comment]
> # 关于你们到现在没有一个人按照我的要求开issue这件事

没事，是要您能了解到这个问题就行了，希望尽快修复吧
