### ISSUE TITLE
无法正常启动MiraiMC

### ISSUE THREAD

**Issue by poikcue** [DreamVoid/MiraiMC#164]
### 问题描述

（试着按格式开一个Issue）
没有调过配置文件。全是默认的配置文件。
在服务器上用了使用MiraiMC的API的插件，但是把它禁用后也同样。
下列日志是我自己本地为这个Issue专门测试用的服务器。

### 复现方法

1. 把MiraiMC-Bukkit.jar拖入plugins
2. 正常启动服务器
3. 启动中报错
4. 报错后自动禁用MiraiMC

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1632 (MC: 1.18.2）

### MiraiMC 插件版本

1.6.1

### 服务端日志

```text
[08:19:14] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[08:19:18] [Worker-Main-2/INFO]: Loaded 7 recipes
[08:19:21] [Server thread/INFO]: Starting minecraft server version 1.18.2
[08:19:21] [Server thread/INFO]: Loading properties
[08:19:21] [Server thread/INFO]: This server is running Purpur version git-Purpur-1632 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: dc4a29b on HEAD)
[08:19:21] [Server thread/INFO]: Server Ping Player Sample Count: 12
[08:19:21] [Server thread/INFO]: Using 4 threads for Netty based IO
[08:19:21] [Server thread/WARN]: [Pufferfish] To improve performance, timings have been disabled by default
[08:19:21] [Server thread/WARN]: [Pufferfish] You can still use timings by using /timings on, but they will not start on server startup unless you set timings.really-enabled to true in paper.yml
[08:19:21] [Server thread/WARN]: [Pufferfish] If you would like to disable this message, either set timings.really-enabled to true or timings.enabled to false.
[08:19:22] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[08:19:22] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[08:19:22] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[08:19:22] [Server thread/WARN]: [Pufferfish] Debug: Java: 18.0.1, test run: true
[08:19:22] [Server thread/INFO]: Default game type: SURVIVAL
[08:19:22] [Server thread/INFO]: Generating keypair
[08:19:22] [Server thread/INFO]: Starting Minecraft server on *:25565
[08:19:22] [Server thread/INFO]: Using default channel type
[08:19:22] [Server thread/INFO]: Paper: Using Java 11 compression from Velocity.
[08:19:22] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[08:19:23] [Server thread/INFO]: [MiraiMC] Loading MiraiMC v1.6.1
[08:19:25] [Server thread/INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[08:19:25] [Server thread/INFO]: [MiraiMC] Verifying mirai-core-all-2.12.0-RC.jar
[08:19:26] [Server thread/INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.12.0-RC.jar
[08:19:26] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[08:19:26] [Server thread/INFO]: Preparing level "world"
[08:19:28] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[08:19:29] [Server thread/INFO]: Time elapsed: 467 ms
[08:19:29] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[08:19:29] [Server thread/INFO]: Time elapsed: 218 ms
[08:19:29] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[08:19:29] [Server thread/INFO]: Time elapsed: 188 ms
[08:19:29] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.6.1
[08:19:29] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[08:19:29] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[08:19:30] [Server thread/ERROR]: Error occurred while enabling MiraiMC v1.6.1 (Is it up to date?)
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
	at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:92) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:57) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:19:30] [Server thread/INFO]: [MiraiMC] Disabling MiraiMC v1.6.1
[08:19:30] [Server thread/INFO]: [MiraiMC] Stopping bot event listener.
[08:19:30] [Server thread/ERROR]: Error occurred while disabling MiraiMC v1.6.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:171) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:136) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[08:19:30] [Server thread/INFO]: Running delayed init tasks
[08:19:30] [Server thread/INFO]: Done (9.323s)! For help, type "help"
[08:19:30] [Server thread/INFO]: Timings Reset
```

### 额外说明

昨天下午2点多的时候还能用。昨天晚上约7点（左右）就有人提交了Issue，也应该就是事情发生的时间。

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by poikcue** [comment]
按照格式重新开了一个Issue。不知道对不对

**Comment by KaridaLee** [comment]
我那个Issue估计是日志没有上传完全，刚刚开了个新端想复制所有的日志QwQ

**Comment by DreamVoid** [comment]
昨天mirai发了2.12.0-RC，把好多事件都干掉了，试着把版本换成2.11.0

**Comment by DiamBlog** [comment]
> 昨天mirai发了2.12.0-RC，把好多事件都干掉了，试着把版本换成2.11.0

好的，谢谢，希望能快速解决

**Comment by KaridaLee** [comment]
@DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧

**Comment by CCBlueX666** [comment]
> @DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧

我把自动更新打开来了，然后lib版本也是2.12.0了，但是依然报错
<img width="333" alt="image" src="https://user-images.githubusercontent.com/60721270/174463075-2991e520-b39b-485e-a2eb-995e2c20380e.png">

**Comment by KaridaLee** [comment]
> > @DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧
> 
> 我把自动更新打开来了，然后lib版本也是2.12.0了，但是依然报错 <img alt="image" width="333" src="https://user-images.githubusercontent.com/60721270/174463075-2991e520-b39b-485e-a2eb-995e2c20380e.png">

我尝试了，这种方法不行，我也在尝试怎么取消启动更新

**Comment by CCBlueX666** [comment]
> > > @DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧
> > 
> > 
> > 我把自动更新打开来了，然后lib版本也是2.12.0了，但是依然报错 <img alt="image" width="333" src="https://user-images.githubusercontent.com/60721270/174463075-2991e520-b39b-485e-a2eb-995e2c20380e.png">
> 
> 我尝试了，这种方法不行，我也在尝试怎么取消启动更新

配置文件里有一个选项，我尝试更改为false过，但是还是不行
<img width="531" alt="image" src="https://user-images.githubusercontent.com/60721270/174463121-8af4f8c3-f54f-4164-86bf-fcea3bdc8aa2.png">

**Comment by KaridaLee** [comment]
> > @DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧
> 
> 我把自动更新打开来了，然后lib版本也是2.12.0了，但是依然报错 <img alt="image" width="333" src="https://user-images.githubusercontent.com/60721270/174463075-2991e520-b39b-485e-a2eb-995e2c20380e.png">

我问题解决了，吧配置文件里的mirai-core-version改成2.11.1然后安装对应版本的就行了

**Comment by CCBlueX666** [comment]
> > > @DreamVoid 那请问一下我想禁用他的自动更新只需要把 check_Update 关掉就好了吧
> > 
> > 
> > 我把自动更新打开来了，然后lib版本也是2.12.0了，但是依然报错 <img alt="image" width="333" src="https://user-images.githubusercontent.com/60721270/174463075-2991e520-b39b-485e-a2eb-995e2c20380e.png">
> 
> 我问题解决了，吧配置文件里的mirai-core-version改成2.11.1然后安装对应版本的就行了

哇塞，我的也解决了，谢谢

**Comment by CCBlueX666** [comment]
但是这样好像会一直刷另外一个报错，我现在先使用Console Spam Fix阻止了报错
<img width="984" alt="image" src="https://user-images.githubusercontent.com/60721270/174463336-986d5644-30d0-4c13-9753-a1ab34d9f243.png">

**Comment by KaridaLee** [comment]
> 但是这样好像会一直刷另外一个报错，我现在先使用Console Spam Fix阻止了报错 <img alt="image" width="984" src="https://user-images.githubusercontent.com/60721270/174463336-986d5644-30d0-4c13-9753-a1ab34d9f243.png">

这个报错挺正常的，以前也偶尔有，在处理QQ群事件的时候

**Comment by CCBlueX666** [comment]
> > 但是这样好像会一直刷另外一个报错，我现在先使用Console Spam Fix阻止了报错 <img alt="image" width="984" src="https://user-images.githubusercontent.com/60721270/174463336-986d5644-30d0-4c13-9753-a1ab34d9f243.png">
> 
> 这个报错挺正常的，以前也偶尔有，在处理QQ群事件的时候

明白了谢谢

**Comment by DreamVoid** [comment]
稍后发布1.6.2将修复此问题

**Comment by DiamBlog** [comment]
> 稍后发布1.7-pre1将修复此问题

谢谢解决

**Comment by maque-zzh** [comment]
麻烦问下 lib版本如何替换为2.11.1 谢谢

**Comment by DiamBlog** [comment]
> 但是这样好像会一直刷另外一个报错，我现在先使用Console Spam Fix阻止了报错 <img alt="image" width="984" src="https://user-images.githubusercontent.com/60721270/174463336-986d5644-30d0-4c13-9753-a1ab34d9f243.png">

# 请问怎么止住这个报错，我现在无法接受QQ群内消息

**Comment by violets007** [comment]
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/20490066/174852136-b229f8f1-a896-41c0-8a6e-b97d15a8bebc.png">

**Comment by DiamBlog** [comment]
# 这两天mirai-core-version=stable的似乎又出现这个问题，只能改回2.11.1
