### ISSUE TITLE
依然无法加载MiraiMC

### ISSUE THREAD

**Issue by poikcue** [DreamVoid/MiraiMC#170]
### 问题描述

早上提交了一个非常相似的问题，最后发布了1.7pre1。
但是，这个版本现在似乎还是不能用。
全新服务端，重新生成的配置文件并下载mirai，依旧报错。

### 复现方法

1. 找一个全新的服务端
2. 把MiraiMC-Bukkit.jar放Plugins里（最新构建）
3. 启动

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1632 (MC: 1.18.2）

### MiraiMC 插件版本

1.7-pre1最新构建

### 服务端日志

```text
[13:56:18] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:56:20] [Worker-Main-1/INFO]: Loaded 7 recipes
[13:56:21] [Server thread/INFO]: Starting minecraft server version 1.18.2
[13:56:21] [Server thread/INFO]: Loading properties
[13:56:22] [Server thread/INFO]: This server is running Purpur version git-Purpur-1632 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT) (Git: dc4a29b on HEAD)
[13:56:22] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:56:22] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:56:22] [Server thread/WARN]: [Pufferfish] To improve performance, timings have been disabled by default
[13:56:22] [Server thread/WARN]: [Pufferfish] You can still use timings by using /timings on, but they will not start on server startup unless you set timings.really-enabled to true in paper.yml
[13:56:22] [Server thread/WARN]: [Pufferfish] If you would like to disable this message, either set timings.really-enabled to true or timings.enabled to false.
[13:56:22] [Server thread/WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[13:56:22] [Server thread/WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[13:56:22] [Server thread/WARN]: [Pufferfish] If you have already added this flag, then SIMD operations are not supported on your JVM or CPU.
[13:56:22] [Server thread/WARN]: [Pufferfish] Debug: Java: 18.0.1, test run: true
[13:56:22] [Server thread/INFO]: Default game type: SURVIVAL
[13:56:22] [Server thread/INFO]: Generating keypair
[13:56:22] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:56:22] [Server thread/INFO]: Using default channel type
[13:56:22] [Server thread/INFO]: Paper: Using Java 11 compression from Velocity.
[13:56:22] [Server thread/INFO]: Paper: Using Java cipher from Velocity.
[13:56:23] [Server thread/INFO]: [MiraiMC] Loading MiraiMC v1.7-pre1
[13:56:40] [Server thread/INFO]: [MiraiMC] Verifying mirai-core-all-2.11.0.jar
[13:56:41] [Server thread/INFO]: [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/2.11.0/mirai-core-all-2.11.0-all.jar
[13:56:47] [Server thread/INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.11.0.jar
[13:56:47] [Server thread/WARN]: [MiraiMC] Unable to download mirai core from remote server(java.io.FileNotFoundException: plugins\MiraiMC\cache\core-ver (系统找不到指定的路径。)), try to use local core.
[13:56:47] [Server thread/WARN]: [MiraiMC] Unable to use local core.
[13:56:47] [Server thread/WARN]: [MiraiMC] An error occurred while loading plugin.
[13:56:47] [Server thread/WARN]: java.io.FileNotFoundException: plugins\MiraiMC\cache\core-ver (系统找不到指定的路径。)
[13:56:47] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open0(Native Method)
[13:56:47] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:293)
[13:56:47] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
[13:56:47] [Server thread/WARN]: 	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:184)
[13:56:47] [Server thread/WARN]: 	at java.base/java.io.FileWriter.<init>(FileWriter.java:98)
[13:56:47] [Server thread/WARN]: 	at MiraiMC-Bukkit.jar//me.dreamvoid.miraimc.internal.classloader.MiraiLoader.loadMiraiCore(MiraiLoader.java:82)
[13:56:47] [Server thread/WARN]: 	at MiraiMC-Bukkit.jar//me.dreamvoid.miraimc.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:32)
[13:56:47] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424)
[13:56:47] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:323)
[13:56:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1180)
[13:56:47] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[13:56:47] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[13:56:47] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:56:47] [Server thread/INFO]: Preparing level "world"
[13:56:48] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:56:49] [Server thread/INFO]: Time elapsed: 261 ms
[13:56:49] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[13:56:49] [Server thread/INFO]: Time elapsed: 98 ms
[13:56:49] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[13:56:49] [Server thread/INFO]: Time elapsed: 161 ms
[13:56:49] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.7-pre1
[13:56:49] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[13:56:49] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[13:56:49] [Server thread/ERROR]: Error occurred while enabling MiraiMC v1.7-pre1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent()" because "this.MiraiEvent" is null
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:59) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:670) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:352) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1180) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:56:49] [Server thread/INFO]: [MiraiMC] Disabling MiraiMC v1.7-pre1
[13:56:49] [Server thread/INFO]: [MiraiMC] Closing all bots
[13:56:49] [Server thread/INFO]: [MiraiMC] All tasks done. Thanks for use MiraiMC!
[13:56:49] [Server thread/INFO]: Running delayed init tasks
[13:56:49] [Server thread/INFO]: Done (27.822s)! For help, type "help"
[13:56:49] [Server thread/INFO]: Timings Reset
```

### 额外说明

删除插件配置文件夹（~/plugins/MiraiMC）后问题依旧存在。
无论是windows本地服务器还是linux服务器都不好使。

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by KaridaLee** [comment]
1.6.1修改一下配置文件就好了呀

**Comment by CCBlueX666** [comment]
> 1.6.1修改一下配置文件就好了呀

他这里已经用1.7的pre了，日志当中写的是系统找不到指定的路径。应该是其他问题导致

**Comment by DreamVoid** [comment]
已修复
