### ISSUE TITLE
发送报错仍然存在

### ISSUE THREAD

**Issue by CCBlueX666** [DreamVoid/MiraiMC#171]
### 问题描述

[此issue](https://github.com/DreamVoid/MiraiMC/issues/169)中报错仍然存在，且一致
此问题在[e88d75的Actions构建](https://github.com/DreamVoid/MiraiMC/actions/runs/2522915221)后仍然存在
at me.dreamvoid.miraimc.bukkit.event.message.postsend.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?]
at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePostSendEvent.(MiraiGroupMessagePostSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]
与
at me.dreamvoid.miraimc.bukkit.event.message.presend.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:20) ~[MiraiMC-Bukkit.jar:?]
at me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessagePreSendEvent.(MiraiGroupMessagePreSendEvent.java:13) ~[MiraiMC-Bukkit.jar:?]

### 复现方法

1. 请查看第169号issue

### 服务端类型

Bukkit

### 服务端版本

git-Paper-379 (MC: 1.18.2)

### MiraiMC 插件版本

1.7-pre1

### 服务端日志

```text
见额外说明
（这是一份在e88d75号的构建后重新出现的日志）
```

### 额外说明

[latest.log](https://github.com/DreamVoid/MiraiMC/files/8934839/latest.log)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://wiki.miraimc.dreamvoid.ml/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by devsong42** [comment]
那只是源代码的更新啊，你自己构建的？

**Comment by CCBlueX666** [comment]
> 那只是源代码的更新啊，你自己构建的？

https://github.com/DreamVoid/MiraiMC/actions/runs/2522915221

**Comment by DreamVoid** [comment]
已修复

**Comment by CCBlueX666** [comment]
感谢
