### ISSUE TITLE
无法通过外部mirai-http-api登录miraimc

### ISSUE THREAD

**Issue by Shapaper** [DreamVoid/MiraiMC#199]
### 问题描述

![image](https://user-images.githubusercontent.com/88654772/178109276-0e3e71e0-ddcf-43be-9efb-91d4d4c87585.png)
![image](https://user-images.githubusercontent.com/88654772/178109280-ae5412f8-c70e-4beb-a884-4dbc35aa6f1f.png)
我的理解是：mirai login QQ号 API密钥[非QQ密码]
然而miraimc似乎将API密钥识别成密码了

**设置API url：**
![image](https://user-images.githubusercontent.com/88654772/178109366-1ac4f862-164d-4a3a-a1ff-c917ff25b43f.png)
**输入指令**
![image](https://user-images.githubusercontent.com/88654772/178109394-bf5f005e-487e-4f00-87f9-a38f6faf9a33.png)
![image](https://user-images.githubusercontent.com/88654772/178109401-23cfff21-12a4-40a1-8c57-a39c7d134250.png)
会报错

### 复现方法

1. 打开mirai的http-api功能
2.通过mirai login登录外部mirai

### 服务端类型

Bukkit

### 服务端版本

1.16.5

### MiraiMC 插件版本

1.7-rc2

### 服务端日志

```text
如  问题描述  中的图
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
如果你不想看到这个issue被直接关闭，那么补齐服务器日志

**Comment by Shapaper** [comment]
[22:42:03] [Server thread/INFO]: Shapaper issued server command: /mirai login 2735389528 KEY[api的key] HTTPAPI
[22:42:04] [Craft Scheduler Thread - 1732/WARN]: [MiraiMC] Plugin MiraiMC v1.7-rc2 generated an exception while executing task 1444350
me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl)
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56) ~[?:?]
        at me.dreamvoid.miraimc.internal.Utils$Http.post(Utils.java:114) ~[?:?]
        at me.dreamvoid.miraimc.httpapi.MiraiHttpAPI.verify(MiraiHttpAPI.java:30) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:63) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.16.5.jar:3028-Spigot-79d53c2-7eb3564]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.16.5.jar:3028-Spigot-79d53c2-7eb3564]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl
        at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[spigot-1.16.5.jar:3028-Spigot-79d53c2-7eb3564]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:96) ~[spigot-1.16.5.jar:3028-Spigot-79d53c2-7eb3564]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020) ~[?:?]
        ... 16 more
