### ISSUE TITLE
自动登录相关问题

### ISSUE THREAD

**Issue by ThrRip** [DreamVoid/MiraiMC#20]
<strong>问题描述</strong>

使用 `/mirai autologin add <账号> <密码>` 添加的自动登录的机器人，无法在下一次服务端重启后自动启动，并抛出如“服务器日志”部分所示的错误。
如果不添加自动登录的机器人，启动时则不会出现错误。手动登录也可以正常使用。
本人不是 Java 开发者，所以不知道错误产生的原因及解决方案，还请项目创建者多多指教。

<strong>复现方法</strong>
1. 加入 MiraiMC 插件，启动服务端
2. 使用 `/mirai autologin add <账号> <密码>` 指令添加自动登录的机器人
3. 重启服务端，启动时即可看到错误

<strong>版本类型</strong>

* Minecraft 服务端版本：Spigot 1.17
* MiraiMC 插件版本：1.3.1

<strong>服务器日志</strong>
```
...（其他插件的日志）
[02:06:24] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] [AutoLogin] Starting auto-bot task.
[02:06:24] [Craft Scheduler Thread - 1/WARN]: [MiraiMC] Plugin MiraiMC v1.3.1 generated an exception while executing task 14
>java.lang.ClassCastException: class java.lang.Long cannot be cast to class java.lang.Integer (java.lang.Long and java.lang.Integer are in module java.base of loader 'bootstrap')
at me.dreamvoid.miraimc.bukkit.MiraiAutoLogin.lambda$doStartUpAutoLogin$0(MiraiAutoLogin.java:79) ~[?:?]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.17.jar:3170-Spigot-a483d2c-ec116f6]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
...（其他插件的日志）
```

**Comment by DreamVoid** [comment]
1.3.2 已发布，请使用此版本

**Comment by ThrRip** [comment]
您好，1.3.2 版本已经可以正常使用自动登录，感谢修复！
