### ISSUE TITLE
Waterfall似乎无法载入

### ISSUE THREAD

**Issue by xANoyU** [DreamVoid/MiraiMC#200]
### 问题描述

Waterfall似乎无法载入，服务端启动过程中报错并禁用了MiraiMC

### 复现方法

1. 加入MiraiMC-Bungee.jar到plugins文件夹
2. 启动服务器
3. 启动过程报错
4. 自动禁用MiraiMC

### 服务端类型

BungeeCord

### 服务端版本

Waterfall-1.19-495

### MiraiMC 插件版本

因为载入不了输入了也没东西

### 服务端日志

```text
[16:03:19] [main/INFO]: Using mbed TLS based native cipher.
[16:03:19] [main/INFO]: Using zlib based native compressor.
[16:03:19] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495
[16:03:19] [main/INFO]: Not on Windows, attempting to use enhanced EpollEventLoop
[16:03:19] [main/INFO]: Epoll is working, utilising it!
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules/cmd_alert.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules/cmd_find.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules/cmd_list.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules/cmd_send.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules/cmd_server.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules/reconnect_yaml.jar, provider=JenkinsModuleSource())
[16:03:19] [main/INFO]: Loaded plugin PistonMOTD version 5.0.1 by AlexProgrammerDE
[16:03:19] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:19] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:20] [main/INFO] [MiraiMC]: Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[16:03:20] [main/INFO] [MiraiMC]: Verifying mirai-core-all-2.12.0.jar
[16:03:20] [main/INFO] [MiraiMC]: Loading library mirai-core-all-2.12.0.jar
[16:03:20] [main/INFO]: Loaded plugin MiraiMC version 1.6.1 by DreamVoid
[16:03:20] [main/INFO]: Loaded plugin BungeeKick version 1.2 by Vik1395
[16:03:20] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:20] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:20] [main/INFO]: Loading library org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31
[16:03:20] [main/INFO]: Loading library org.jetbrains.kotlin:kotlin-stdlib:1.5.31
[16:03:20] [main/INFO]: Loading library org.jetbrains:annotations:13.0
[16:03:20] [main/INFO]: Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31
[16:03:20] [main/INFO]: Loading library org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31
[16:03:21] [main/INFO]: Loading library com.typesafe:config:1.4.1
[16:03:21] [main/INFO]: Loading library com.electronwill.night-config:core:3.6.5
[16:03:21] [main/INFO]: Loading library com.electronwill.night-config:toml:3.6.5
[16:03:21] [main/INFO]: Loading library com.electronwill.night-config:json:3.6.5
[16:03:21] [main/INFO]: Loading library com.electronwill.night-config:hocon:3.6.5
[16:03:21] [main/INFO]: Loading library com.zaxxer:HikariCP:4.0.3
[16:03:21] [main/INFO]: Loading library org.slf4j:slf4j-api:2.0.0-alpha7
[16:03:21] [main/INFO]: Loading library com.mongodb:MongoDB:3.12.2
[16:03:21] [main/INFO]: Loading library net.kyori:examination-api:1.3.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-key:4.11.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-api:4.11.0
[16:03:21] [main/INFO]: Loading library net.kyori:examination-string:1.3.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-platform-bungeecord:4.1.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-text-serializer-gson:4.10.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-text-serializer-legacy:4.10.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-text-serializer-bungeecord:4.1.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-platform-api:4.1.0
[16:03:21] [main/INFO]: Loading library net.kyori:adventure-platform-facet:4.1.0
[16:03:22] [main/INFO]: 
[16:03:22] [main/INFO]: 正在加载 TrChat... git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495
[16:03:22] [main/INFO]: 
[16:03:22] [main/INFO]: [TrChat] 已支持 Bungee 通讯.
[16:03:22] [main/INFO]: Loaded plugin TrChat version 2.0.0-PRE-15 by Arasple, ItsFlicker
[16:03:22] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:22] [main/INFO]: Loaded plugin BungeeServerManager version 1.1.3-SNAPSHOT by Teg
[16:03:22] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:22] [main/INFO]: Loaded plugin BungeeTabListPlus version 3.5.1 by CodeCrafter47
[16:03:22] [main/WARN]: Forced host server pvp is not defined
[16:03:22] [main/INFO] [PistonMOTD]:   _____  _       _                 __  __   ____  _______  _____  
[16:03:22] [main/INFO] [PistonMOTD]:  |  __ \(_)     | |               |  \/  | / __ \|__   __||  __ \ 
[16:03:22] [main/INFO] [PistonMOTD]:  | |__) |_  ___ | |_  ___   _ __  | \  / || |  | |  | |   | |  | |
[16:03:22] [main/INFO] [PistonMOTD]:  |  ___/| |/ __|| __|/ _ \ | '_ \ | |\/| || |  | |  | |   | |  | |
[16:03:22] [main/INFO] [PistonMOTD]:  | |    | |\__ \| |_| (_) || | | || |  | || |__| |  | |   | |__| |
[16:03:22] [main/INFO] [PistonMOTD]:  |_|    |_||___/ \__|\___/ |_| |_||_|  |_| \____/   |_|   |_____/ 
[16:03:22] [main/INFO] [PistonMOTD]: 
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mLoading config[0m
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mRegistering placeholders[0m
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mLooking for hooks[0m
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mRegistering listeners[0m
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mRegistering command[0m
[16:03:22] [main/INFO] [PistonMOTD]: [0;36mChecking for a newer version[0m
[16:03:24] [main/INFO] [PistonMOTD]: [0;36mYou're up to date![0m
[16:03:24] [main/INFO] [PistonMOTD]: [0;36mLoading metrics[0m
[16:03:24] [main/INFO] [PistonMOTD]: [0;36mDone! :D[0m
[16:03:24] [main/INFO]: Enabled plugin PistonMOTD version 5.0.1 by AlexProgrammerDE
[16:03:24] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO] [MiraiMC]: Mirai working dir: default
[16:03:24] [main/INFO] [MiraiMC]: Starting Mirai-Events listener.
[16:03:24] [main/WARN]: Exception encountered when loading plugin: MiraiMC
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.event.InternalGlobalEventChannelProvider
	at net.mamoe.mirai.utils.ActualsKt.loadService(Actuals.kt:40) ~[?:?]
	at net.mamoe.mirai.utils.ActualsKt.loadService$default(Actuals.kt:35) ~[?:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:31) ~[?:?]
	at net.mamoe.mirai.event.GlobalEventChannel$instance$2.invoke(GlobalEventChannel.kt:30) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at net.mamoe.mirai.event.GlobalEventChannel.getInstance(GlobalEventChannel.kt:30) ~[?:?]
	at net.mamoe.mirai.event.GlobalEventChannel.createListener(GlobalEventChannel.kt:44) ~[?:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:630) ~[?:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:622) ~[?:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[?:?]
	at me.dreamvoid.miraimc.bungee.MiraiEvent.startListenEvent(MiraiEvent.java:86) ~[?:?]
	at me.dreamvoid.miraimc.bungee.BungeePlugin.onEnable(BungeePlugin.java:53) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[Waterfall-1.19-495.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[Waterfall-1.19-495.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[Waterfall-1.19-495.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[Waterfall-1.19-495.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:546fa12:495]
[16:03:24] [main/INFO]: Enabled plugin BungeeKick version 1.2 by Vik1395
[16:03:24] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO]: [TrChat] 聊天 | 成功载入 1 个聊天频道... [1 Ms]
[16:03:24] [main/INFO]: [TrChat] 信息 | 加载完毕. TrChat v2.0.0-PRE-15 现已启用, 敬请使用.
[16:03:24] [main/INFO]: Enabled plugin TrChat version 2.0.0-PRE-15 by Arasple, ItsFlicker
[16:03:24] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO]: Enabled plugin BungeeServerManager version 1.1.3-SNAPSHOT by Teg
[16:03:24] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.19-R0.1-SNAPSHOT:546fa12:495 by WaterfallMC
[16:03:24] [main/INFO]: Enabled plugin BungeeTabListPlus version 3.5.1 by CodeCrafter47
[16:03:24] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:9000
[16:03:26] [TrChat Pool Thread #1/INFO]: [TrChat] 你正在运行最新版的 TrChat.
```

### 额外说明

使用Ubuntu 20.04
openjdk version "1.8.0_312"
确认加入的插件是“MiraiMC-Bungee.jar”

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by xANoyU** [comment]
完了, 这个Issue的Labels不知道怎么修改
