### ISSUE TITLE
paper1.8无法登录

### ISSUE THREAD

**Issue by cnluminous** [DreamVoid/MiraiMC#21]
<strong>问题描述</strong>

输入/mirai login 账号 密码后无任何反应
输入/mirai list时报错

<strong>复现方法</strong>

1. 输入/mirai login 账号 密码----无任何反应
2. 输入/mirai list --------报错

<strong>版本类型</strong>

* Minecraft 服务端版本：paper1.8.8-443
* MiraiMC 插件版本：1.3.1

java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)
系统环境:windows11 21H2版本
操作系统版本:22000.100

<strong>服务器日志</strong>

```
[22:09:34 INFO]: 当前在线的机器人: 
[22:09:34 WARN]: Unexpected exception while parsing console command "mirai list" org.bukkit.command.CommandException: Unhandled exception executing command 'mirai' in plugin MiraiMC v1.3.1 at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~
[patched.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~
[patched.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched.jar:git-PaperSpigot-"4c7641d"] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchServerCommand(CraftServer.java:629) 
[patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.DedicatedServer.aO(DedicatedServer.java:416) 
[patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:379) 
[patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) 
[patched.jar:git-PaperSpigot-"4c7641d"] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) 
[patched.jar:git-PaperSpigot-"4c7641d"] at java.lang.Thread.run(Unknown Source) [?:1.8.0_291] Caused by: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:238) ~[?:?] at me.dreamvoid.miraimc.bukkit.CommandProcessor.onCommand(CommandProcessor.java:115) ~[?:?] at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched.jar:git-PaperSpigot-"4c7641d"] ... 8 more
```

**Comment by DreamVoid** [comment]
请尝试重新启动服务端后进行登录，目前会有几率出现登录进程无法启动的情况，为Mirai核心问题。
