### ISSUE TITLE
在Nukkit服务器上运行的空指针异常报错

### ISSUE THREAD

**Issue by yuyu3417** [DreamVoid/MiraiMC#216]
### 问题描述

我使用的是Nukkit 1.19.10  Mirai版本是1.7最新版本，打开服务器后显示一下空指针异常报错
``

### 复现方法

1. 在开启服务器加载插件的时候就出现问题

### 服务端类型

Nukkit

### 服务端版本

1.19.10

### MiraiMC 插件版本

1.7

### 服务端日志

```text
container@pterodactyl~ 服务器状态为 启动...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
/entrypoint.sh: line 8: ip: command not found
container@P73R~ java -version
openjdk version "1.8.0_332"
OpenJDK Runtime Environment Corretto-8.332.08.1 (build 1.8.0_332-b08)
OpenJDK 64-Bit Server VM Corretto-8.332.08.1 (build 25.332-b08, mixed mode)
container@20034~ java -Xms128M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar
22:35:14 [INFO ] Loading nukkit.yml ...
22:35:15 [INFO ] Loading server.properties ...
22:35:15 [INFO ] 将 中文(简体) (chs) 设置为基本语言
22:35:15 [INFO ] 正在启动 Minecraft: BE v1.19.10
22:35:15 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
22:35:15 [ERROR] Throwing
java.lang.NullPointerException: null
        at cn.nukkit.permission.BanEntry.<init>(BanEntry.java:28) ~[server.jar:?]
        at cn.nukkit.permission.BanEntry.fromMap(BanEntry.java:84) ~[server.jar:?]
        at cn.nukkit.permission.BanList.load(BanList.java:112) ~[server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:431) ~[server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
22:35:15 [INFO ] Stopping other threads
container@pterodactyl~ 服务器状态为 关机...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

### 额外说明

请联系我QQ：3417236355
备注一下Mirai MC

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
不认为你使用的是正常的nukkitx核心，请尝试使用最新官方核心
