### ISSUE TITLE
登录机器人时出现异常

### ISSUE THREAD

**Issue by mihuo3567** [DreamVoid/MiraiMC#217]
### 问题描述

正常登录之后提示登录机器人时出现异常

### 复现方法

1. /mirai login登录
2. 过滑块获得ticket
3. 报错

### 服务端类型

Bukkit

### 服务端版本

paper-1.16.5

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[19:54:54 WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(111), code=237, title=安全提醒, message=当前登录存 在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[?:?]
[19:54:54 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(111), code=237, title=安全提醒, message=当前登录存在安全风险，请使用常用设备或通过手机号登录。, errorInfo=)
[19:54:54 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by lightumcc** [comment]
https://github.com/DreamVoid/MiraiMC/discussions/210
