### ISSUE TITLE
插件不能向群内发送任何消息

### ISSUE THREAD

**Issue by DiamBlog** [DreamVoid/MiraiMC#223]
### 问题描述

今日服务器重启之后，发现机器人无法向群内发生任何相关消息。
1.玩家进退游戏 2.游戏内聊天 都不能正常发群
日志见下
---
经过测试发现，miraimc插件相对正常加载，控制台能看到群内消息日志，使用Chat2QQ和XiaoheiQSManger插件能够将消息转发到群内。
--
# 总而言之，QQ机器人无法向QQ群内发送任何消息，但是能接受到群内消息

### 复现方法

1. 启动服务器，之后出现问题

### 服务端类型

Bukkit

### 服务端版本

Paper-1.19.1

### MiraiMC 插件版本

1.7

### 服务端日志

```text
使用Chat2QQ和XiaoheiQSManger插件，玩家进出游戏时，报错相似
共同点为:java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
以及以下

这是Chat2QQ玩家退出游戏的报错
[03:51:13 WARN]: [MiraiMC] Plugin Chat2QQ v1.6 generated an exception while executing task 257824
java.lang.IllegalStateException: Send message failed: MessageSvcPbSendMsg.Response.Failed(resultType=46, errorCode=0, errorMessage=)
        at net.mamoe.mirai.internal.contact.SendMessageHandler.sendMessagePacket(SendMessageHandler.kt:191) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.contact.SendMessageHandler$sendMessagePacket$1.invokeSuspend(SendMessageHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1412) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryFinalizeSimpleState(JobSupport.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:856) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.JobSupport.makeCompleting$kotlinx_coroutines_core(JobSupport.kt:806) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CompletableDeferredImpl.complete(CompletableDeferred.kt:92) ~[MiraiMC-Bukkit.jar:?]                                                             at net.mamoe.mirai.internal.network.handler.NetworkHandlerSupport.collectReceived$mirai_core(NetworkHandlerSupport.kt:79) ~[MiraiMC-Bukkit.jar:?]                     at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:193) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 额外说明

使用Chat2QQ和XiaoheiQSManger插件，玩家进出游戏时，报错相似

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DiamBlog** [comment]
https://github.com/mamoe/mirai/issues/2127
