### ISSUE TITLE
使用Httpapi无法连接外部MCL

### ISSUE THREAD

**Issue by Mxmilu666** [DreamVoid/MiraiMC#224]
### 问题描述

1.无法连接外部MCL
2.配置文件仅调过httpapi模式

### 复现方法

1. 启动客户端
2. 控制台输入mirai login <机器人账号> <连接密钥> HTTPAPI

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1566 (MC: 1.18.1)

### MiraiMC 插件版本

MiraiMC version 1.7

### 服务端日志

```text
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-LTS) Host: Windows Server 2022 10.0 (amd64)
Loading libraries, please wait...
[17:43:21 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[17:43:22 INFO]: Reloading ResourceManager: Default, bukkit
[17:43:22 INFO]: Loaded 7 recipes
[17:43:24 INFO]: Starting minecraft server version 1.18.1
[17:43:24 WARN]: ****************************
[17:43:24 WARN]: YOU ARE RUNNING THIS SERVER AS AN ADMINISTRATIVE OR ROOT USER. THIS IS NOT ADVISED.
[17:43:24 WARN]: YOU ARE OPENING YOURSELF UP TO POTENTIAL RISKS WHEN DOING THIS.
[17:43:24 WARN]: FOR MORE INFORMATION, SEE https://madelinemiller.dev/blog/root-minecraft-server/
[17:43:24 WARN]: ****************************
[17:43:24 INFO]: Loading properties
[17:43:24 INFO]: This server is running Purpur version git-Purpur-1566 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 133b3e1 on HEAD)
[17:43:24 INFO]: Server Ping Player Sample Count: 12
[17:43:24 INFO]: Using 4 threads for Netty based IO
[17:43:24 WARN]: [Pufferfish] To improve performance, timings have been disabled by default
[17:43:24 WARN]: [Pufferfish] You can still use timings by using /timings on, but they will not start on server startup unless you set timings.really-enabled to true in paper.yml
[17:43:24 WARN]: [Pufferfish] If you would like to disable this message, either set timings.really-enabled to true or timings.enabled to false.
[17:43:24 WARN]: [Pufferfish] SIMD operations are available for your server, but are not configured!
[17:43:24 WARN]: [Pufferfish] To enable additional optimizations, add "--add-modules=jdk.incubator.vector" to your startup flags, BEFORE the "-jar".
[17:43:24 INFO]: Default game type: SURVIVAL
[17:43:24 INFO]: Generating keypair
[17:43:24 INFO]: Starting Minecraft server on *:11451
[17:43:24 INFO]: Using default channel type
[17:43:25 INFO]: Paper: Using Java 11 compression from Velocity.
[17:43:25 INFO]: Paper: Using Java cipher from Velocity.
[17:43:25 INFO]: [MiraiMC] Loading MiraiMC v1.7
[17:43:28 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.1.jar
[17:43:29 INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.11.1.jar
[17:43:29 INFO]: Server permissions file permissions.yml is empty, ignoring it
[17:43:29 INFO]: Preparing level "world"
[17:43:30 INFO]: Preparing start region for dimension minecraft:overworld
[17:43:31 INFO]: Time elapsed: 311 ms
[17:43:31 INFO]: Preparing start region for dimension minecraft:the_nether
[17:43:31 INFO]: Time elapsed: 129 ms
[17:43:31 INFO]: Preparing start region for dimension minecraft:the_end
[17:43:31 INFO]: Time elapsed: 217 ms
[17:43:31 INFO]: [MiraiMC] Enabling MiraiMC v1.7
[17:43:31 INFO]: [MiraiMC] Mirai working dir: default
[17:43:31 INFO]: [MiraiMC] Starting Mirai-Events listener.
[17:43:31 INFO]: [MiraiMC] Loading auto-login file.
[17:43:31 INFO]: [MiraiMC] Registering commands.
[17:43:31 INFO]: [MiraiMC] Registering events.
[17:43:31 INFO]: [MiraiMC] Initializing SQLite database.
[17:43:31 INFO]: [MiraiMC] Initializing bStats metrics.
[17:43:31 INFO]: [MiraiMC] Initializing HttpAPI async task.
[17:43:31 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[17:43:31 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[17:43:31 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[17:43:32 INFO]: Running delayed init tasks
[17:43:32 INFO]: Done (7.668s)! For help, type "help"
[17:43:32 INFO]: Timings Reset
[17:43:32 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[17:43:32 INFO]: [MiraiMC] Checking update...
[17:43:32 INFO]: [MiraiMC] You are using the latest version!
[17:43:34 INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[17:43:34 INFO]: [MiraiMC] 2.12.0仍然存在一些问题，暂时不使用2.12.0
[17:43:34 INFO]: [MiraiMC] =======================================
> mirai login [QQ] [密钥] HTTPAPI
[17:43:38 WARN]: [MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 8
me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogConfigurationException: java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl (Caused by java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl)
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1158) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory$2.run(LogFactory.java:960) ~[MiraiMC-Bukkit.jar:?]
        at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.newFactory(LogFactory.java:957) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.getFactory(LogFactory.java:624) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.getLog(LogFactory.java:655) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.conn.ssl.DefaultHostnameVerifier.<init>(DefaultHostnameVerifier.java:82) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.impl.client.HttpClientBuilder.build(HttpClientBuilder.java:966) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.libraries.org.apache.http.impl.client.HttpClients.createDefault(HttpClients.java:56) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.internal.Utils$Http.post(Utils.java:125) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.httpapi.MiraiHttpAPI.verify(MiraiHttpAPI.java:30) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:63) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at org.bukkit.craftbukkit.v1_18_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.18.1.jar:git-Purpur-1566]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: me.dreamvoid.miraimc.libraries.org.apache.commons.logging.impl.LogFactoryImpl
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.dreamvoid.miraimc.libraries.org.apache.commons.logging.LogFactory.createFactory(LogFactory.java:1020) ~[MiraiMC-Bukkit.jar:?]
        ... 17 more
```

### 额外说明

JAVA版本:Java 17 (OpenJDK 64-Bit Server VM 17.0.2+8-LTS) 
系统版本:Windows Server 2022 10.0 (amd64)
仅只有这一个插件

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [x] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
稍后可更新开发版使用
