### ISSUE TITLE
机器人无法登录

### ISSUE THREAD

**Issue by Owenlaoxiong** [DreamVoid/MiraiMC#228]
### 问题描述

机器人无法登陆
报错如下：
[13:14:34 WARN]: Caused by: java.util.jar.JarException: file:/C:/Users/Administr
ator/Desktop/Owen%20Bedwars%20Network/登录服/plugins/MiraiMC/MiraiBot/libs/mirai
-core-all-2.12.1.jar has unsigned entries - net/mamoe/mirai/internal/MiraiImpl$g
etGroupVoiceDownloadUrl$1.class
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.
java:510)
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:
371)
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verify(JarVerifier.java:297)

[13:14:34 WARN]:        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurit
y.java:164)
[13:14:34 WARN]:        at javax.crypto.JceSecurity.getVerificationResult(JceSec
urity.java:190)
[13:14:34 WARN]:        at javax.crypto.JceSecurity.getInstance(JceSecurity.java
:102)
[13:14:34 WARN]:        ... 62 more
[13:14:34 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Parent job is Cancelling
[13:14:34 INFO]: [MiraiMC] Bot cancelled: Bot closed

### 复现方法

1. /mirai login QQ号 密码（后两者就不写了）

### 服务端类型

Bukkit

### 服务端版本

spigot-1.8.8

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[13:14:34 WARN]: Caused by: java.util.jar.JarException: file:/C:/Users/Administr
ator/Desktop/Owen%20Bedwars%20Network/登录服/plugins/MiraiMC/MiraiBot/libs/mirai
-core-all-2.12.1.jar has unsigned entries - net/mamoe/mirai/internal/MiraiImpl$g
etGroupVoiceDownloadUrl$1.class
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.
java:510)
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:
371)
[13:14:34 WARN]:        at javax.crypto.JarVerifier.verify(JarVerifier.java:297)

[13:14:34 WARN]:        at javax.crypto.JceSecurity.verifyProviderJar(JceSecurit
y.java:164)
[13:14:34 WARN]:        at javax.crypto.JceSecurity.getVerificationResult(JceSec
urity.java:190)
[13:14:34 WARN]:        at javax.crypto.JceSecurity.getInstance(JceSecurity.java
:102)
[13:14:34 WARN]:        ... 62 more
[13:14:34 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Parent job is Cancelling
[13:14:34 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by lightumcc** [comment]
大哥，日志传完整诶
