### ISSUE TITLE
与Whitelist4QQ共同使用时无法正确触发PlayerJoinEvent

### ISSUE THREAD

**Issue by K85** [DreamVoid/MiraiMC#233]
### 问题描述

MiraiQQ可以正常登录QQ，但无法与Whitelist4QQ共同使用。

### 复现方法

a player join.

### 服务端类型

Bukkit

### 服务端版本

This server is running Paper version git-Paper-81 (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: 86f87ba) You are running the latest version Previous version: git-Paper-78 (MC: 1.19)

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[19:24:47 ERROR]: Could not pass event AsyncPlayerPreLoginEvent to Whitelist4QQ v1.1
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "me.dreamvoid.miraimc.internal.Utils.connection" is null
        at me.dreamvoid.miraimc.api.MiraiMC.getBind(MiraiMC.java:383) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.whitelist4qq.bukkit.BukkitPlugin$PlayerLogin.onPlayerJoin(BukkitPlugin.java:118) ~[Whitelist4QQ.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor30.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$LoginHandler.fireEvents(ServerLoginPacketListenerImpl.java:456) ~[?:?]
        at net.minecraft.server.network.ServerLoginPacketListenerImpl$1.run(ServerLoginPacketListenerImpl.java:337) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[19:24:49 ERROR]: Could not pass event PlayerJoinEvent to Whitelist4QQ v1.1
java.lang.NullPointerException: Cannot invoke "java.sql.Connection.createStatement()" because "me.dreamvoid.miraimc.internal.Utils.connection" is null
        at me.dreamvoid.miraimc.api.MiraiMC.getBind(MiraiMC.java:383) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.whitelist4qq.bukkit.BukkitPlugin$PlayerJoin.onPlayerJoined(BukkitPlugin.java:169) ~[Whitelist4QQ.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor31.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:git-Paper-81]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:670) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.players.PlayerList.postChunkLoadJoin(PlayerList.java:365) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.players.PlayerList.lambda$placeNewPlayer$1(PlayerList.java:307) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:326) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:568) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:232) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1582) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1415) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
```


### 额外说明

OS: Linux Centors 8
Java: OpenJDK17

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by K85** [comment]
已自行解决该问题。
