### ISSUE TITLE
无法加载MiraiMC

### ISSUE THREAD

**Issue by TaoXiaoBai** [DreamVoid/MiraiMC#242]
### 问题描述

使用类似PlugMan的插件加载插件时，无法成功加载

### 复现方法

1. 下载插件放入plugins
2. 载入插件
3. 报错

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1632 (MC: 1.18.2)

### MiraiMC 插件版本

1.7

### 服务端日志

```text
完整的日志超出65536的限制了，所以放到下面的粘贴板里了
https://netcut.cn/1gcllt86q
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [ ] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
尝试更新最新开发版

**Comment by TaoXiaoBai** [comment]
> 试用更新开发最新版
下载最新开发版直接尝试载入依旧报错

<details>
<summary>Details</summary>

[16:52:04 INFO]: TaoXiaoBai issued server command: /su rp MiraiMC -f
[16:52:06 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.1.jar
[16:52:06 INFO]: [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/2.11.1/mirai-core-all-2.11.1-all.jar
[16:52:06 INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.11.1.jar
[16:52:06 WARN]: [MiraiMC] An error occurred while loading plugin.
[16:52:06 WARN]: java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
[16:52:06 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235)
[16:52:06 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:128)
[16:52:06 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105)
[16:52:06 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[16:52:06 WARN]:        at MiraiMC-Bukkit.jar//me.dreamvoid.miraimc.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:43)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.loadPluginDescriptions(BukkitPluginManager.java:96)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:78)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:211)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:188)
[16:52:06 WARN]:        at ServerUtils-Bukkit-3.5.1.jar//net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116)
[16:52:06 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172)
[16:52:06 WARN]:        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906)
[16:52:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2390)
[16:52:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2201)
[16:52:06 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2182)
[16:52:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46)
[16:52:06 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6)
[16:52:06 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[16:52:06 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[16:52:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[16:52:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1427)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[16:52:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1404)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1397)
[16:52:06 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1475)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1247)
[16:52:06 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321)
[16:52:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[16:52:06 INFO]: [MiraiMC] Enabling MiraiMC v1.7
[16:52:06 ERROR]: Error occurred while enabling MiraiMC v1.7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:128) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:375) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:55) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:192) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:219) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:188) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:52:06 INFO]: [MiraiMC] Disabling MiraiMC v1.7
[16:52:06 INFO]: [MiraiMC] Closing all bots
[16:52:06 ERROR]: Error occurred while disabling MiraiMC v1.7 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "org.bukkit.plugin.java.JavaPlugin.getDescription()" because "loader.plugin" is null
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:235) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:128) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:200) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:110) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:170) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:401) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:376) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at net.frankheijden.serverutils.bukkit.managers.BukkitPluginManager.enableOrderedPlugins(BukkitPluginManager.java:192) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.enablePlugins(AbstractPluginManager.java:105) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.managers.AbstractPluginManager.reloadPlugins(AbstractPluginManager.java:219) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.common.commands.CommandServerUtils.handleReloadPlugin(CommandServerUtils.java:243) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:123) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.CommandManager.executeCommand(CommandManager.java:188) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at net.frankheijden.serverutils.dependencies.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[ServerUtils-Bukkit-3.5.1.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2390) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2201) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleChat(ServerGamePacketListenerImpl.java:2182) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.handle(ServerboundChatPacket.java:46) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundChatPacket.a(ServerboundChatPacket.java:6) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1427) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1404) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1397) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1475) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

</details>

**Comment by DreamVoid** [comment]
不要使用plugman

**Comment by TaoXiaoBai** [comment]
> 不要使用plugman

还是不行 
log;https://netcut.cn/1gcllt86q

**Comment by DreamVoid** [comment]
请检查你使用的Java是否为OpenJ9或其他第三方JVM，或者，尝试重新安装无修改的Java

**Comment by TaoXiaoBai** [comment]
> 请检查你使用的Java是否为OpenJ9或其他第三方JVM，或者，尝试重新安装无修改的Java

用的是GraalVM，是这个jvm不能用吗？

**Comment by DreamVoid** [comment]
> > 请检查你使用的Java是否为OpenJ9或其他第三方JVM，或者，尝试重新安装无修改的Java
> 
> 用的是GraalVM，是这个jvm不能用吗？

至少我不让我这是个主流的JVM

**Comment by XiaMoHuaHuo-CN** [comment]
mirai对第三方JVM并不友好，请使用甲骨文的Java
