### ISSUE TITLE
qq机器人登陆问题

### ISSUE THREAD

**Issue by htc-01** [DreamVoid/MiraiMC#257]
### 问题描述

以前一切正常，就在刚刚，登陆不上去了
显示这个：登录机器人时出现异常，原因: Error(bot=Bot(2507973134), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )

### 复现方法

1. 启动插件时就这样了

### 服务端类型

Bukkit

### 服务端版本

Paper-1.18.1

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[15:45:29] [ServerMain/WARN]: Failed to update counter. Error code: 0x800007D5
[15:45:29] [ServerMain/WARN]: Disabling further attempts to query Paging File.
[15:45:35] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:45:36] [ServerMain/INFO]: Reloading ResourceManager: Default, bukkit
[15:45:38] [Worker-Main-17/INFO]: Loaded 7 recipes
[15:45:43] [Server thread/INFO]: Starting minecraft server version 1.18.1
[15:45:43] [Server thread/INFO]: Loading properties
[15:45:43] [Server thread/INFO]: This server is running CraftBukkit version 3443-Spigot-699290c-2c1e499 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
[15:45:44] [Server thread/INFO]: Debug logging is disabled
[15:45:44] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:45:44] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:45:44] [Server thread/INFO]: Default game type: SURVIVAL
[15:45:44] [Server thread/INFO]: Generating keypair
[15:45:44] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:45:44] [Server thread/INFO]: Using default channel type
[15:45:46] [Server thread/INFO]: [MiraiMC] Loading MiraiMC v1.7
[15:45:51] [Server thread/WARN]: [MiraiMC] Failed to get https://api.miraimc.dreamvoid.me/, reason: java.net.SocketTimeoutException: Connect timed out
[15:45:56] [Server thread/WARN]: [MiraiMC] Failed to get https://api.miraimc.dreamvoid.ml/, reason: java.net.SocketTimeoutException: Connect timed out
[15:46:00] [Server thread/INFO]: [MiraiMC] Verifying mirai-core-all-2.11.1.jar
[15:46:00] [Server thread/INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.11.1.jar
[15:46:00] [Server thread/INFO]: [MiraiMC] Loading Link2QQ v1.1
[15:46:00] [Server thread/INFO]: [MiraiMC] Loading Chat2QQ v1.6
[15:46:00] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[15:46:00] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[15:46:00] [Server thread/WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[15:46:00] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[15:46:00] [Server thread/INFO]: Preparing level "world"
[15:46:01] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[15:46:02] [Worker-Main-18/INFO]: Preparing spawn area: 0%
[15:46:02] [Worker-Main-16/INFO]: Preparing spawn area: 0%
[15:46:02] [Worker-Main-16/INFO]: Preparing spawn area: 0%
[15:46:03] [Worker-Main-18/INFO]: Preparing spawn area: 0%
[15:46:03] [Worker-Main-15/INFO]: Preparing spawn area: 0%
[15:46:04] [Worker-Main-12/INFO]: Preparing spawn area: 3%
[15:46:04] [Worker-Main-14/INFO]: Preparing spawn area: 14%
[15:46:05] [Worker-Main-15/INFO]: Preparing spawn area: 45%
[15:46:05] [Worker-Main-15/INFO]: Preparing spawn area: 69%
[15:46:06] [Worker-Main-12/INFO]: Preparing spawn area: 93%
[15:46:06] [Server thread/INFO]: Time elapsed: 4740 ms
[15:46:06] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[15:46:07] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[15:46:07] [Worker-Main-24/INFO]: Preparing spawn area: 0%
[15:46:07] [Worker-Main-21/INFO]: Preparing spawn area: 0%
[15:46:08] [Worker-Main-16/INFO]: Preparing spawn area: 1%
[15:46:08] [Worker-Main-21/INFO]: Preparing spawn area: 1%
[15:46:09] [Worker-Main-14/INFO]: Preparing spawn area: 24%
[15:46:09] [Worker-Main-22/INFO]: Preparing spawn area: 50%
[15:46:10] [Worker-Main-15/INFO]: Preparing spawn area: 79%
[15:46:10] [Server thread/INFO]: Time elapsed: 3734 ms
[15:46:10] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[15:46:11] [Worker-Main-14/INFO]: Preparing spawn area: 0%
[15:46:11] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[15:46:11] [Worker-Main-22/INFO]: Preparing spawn area: 0%
[15:46:11] [Worker-Main-21/INFO]: Preparing spawn area: 2%
[15:46:12] [Worker-Main-21/INFO]: Preparing spawn area: 12%
[15:46:12] [Worker-Main-12/INFO]: Preparing spawn area: 51%
[15:46:13] [Worker-Main-12/INFO]: Preparing spawn area: 80%
[15:46:13] [Server thread/INFO]: Time elapsed: 3204 ms
[15:46:13] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.7
[15:46:13] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[15:46:13] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[15:46:13] [Server thread/INFO]: [MiraiMC] Loading auto-login file.
[15:46:13] [Server thread/INFO]: [MiraiMC] Registering commands.
[15:46:13] [Server thread/INFO]: [MiraiMC] Registering events.
[15:46:13] [Server thread/INFO]: [MiraiMC] Initializing SQLite database.
[15:46:13] [Server thread/INFO]: [MiraiMC] Initializing bStats metrics.
[15:46:13] [Server thread/WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[15:46:13] [Server thread/WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[15:46:13] [Server thread/INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[15:46:13] [Server thread/INFO]: [MiraiMC] Enabling Link2QQ v1.1
[15:46:13] [Server thread/WARN]: [MiraiMC] "Link2QQ v1.1" has registered a listener for me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent on method "public void me.dreamvoid.link2qq.bukkit.BukkitPlugin.onGroupMessageReceive(me.dreamvoid.miraimc.bukkit.event.MiraiGroupMessageEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [DreamVoid].
[15:46:13] [Server thread/WARN]: [MiraiMC] "Link2QQ v1.1" has registered a listener for me.dreamvoid.miraimc.bukkit.event.MiraiFriendMessageEvent on method "public void me.dreamvoid.link2qq.bukkit.BukkitPlugin.onFriendMessageReceive(me.dreamvoid.miraimc.bukkit.event.MiraiFriendMessageEvent)", but the event is Deprecated. "Server performance will be affected"; please notify the authors [DreamVoid].
[15:46:13] [Server thread/INFO]: [MiraiMC] Enabling Chat2QQ v1.6
[15:46:13] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[15:46:13] [Server thread/INFO]: Done (12.876s)! For help, type "help"
[15:46:13] [Server thread/INFO]: Starting remote control listener
[15:46:13] [Server thread/WARN]: No rcon password set in server.properties, rcon disabled!
[15:46:13] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] Checking update...
[15:46:13] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[15:46:13] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] You are using the latest version!
[15:46:13] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 2507973134 Protocol: ANDROID_PHONE
[15:46:13] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] 登录新的机器人账号: 2507973134, 协议: ANDROID_PHONE
[15:46:15] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Server list: 116.130.229.21:80, 59.83.207.254:80, msfwifi.3g.qq.com:8080, 157.148.54.73:14000, 116.130.229.126:8080, 163.177.30.248:80, 112.80.130.195:443, 220.194.118.224:80, 116.130.229.208:80.
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] 腾讯已开始使用主动发送验证码的设备锁验证形式。
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] 如有用户遇到此类验证码或发现无论如何都无法通过设备锁验证，
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] 请前往GitHub开新issue，我将尽快提供支持。
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] 另外，暂时不要使用mirai 2.12.0，插件暂时没有进行适配。
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] 请先使用2.11.1核心。
[15:46:15] [Craft Scheduler Thread - 1/INFO]: [MiraiMC] =======================================
[15:46:16] [DefaultDispatcher-worker-1/WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:123)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.getDefaultInitialPublicKey(ECDH.kt:132)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.AccountSecretsImpl(AccountSecretsManager.kt:146)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:154)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:107)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:122)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$startState$2.invokeSuspend(NettyNetworkHandler.kt:274)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/D:/mc_server01/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.11.1.jar is not signed.
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
[15:46:16] [DefaultDispatcher-worker-1/WARN]: 	... 29 more
[15:46:16] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[15:46:17] [DefaultDispatcher-worker-1/INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[15:46:17] [DefaultDispatcher-worker-1/WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2507973134), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284) ~[mirai-core-all-2.11.1.jar:2.11.1]
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-all-2.11.1.jar:2.11.1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [mirai-core-all-2.11.1.jar:2.11.1]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [mirai-core-all-2.11.1.jar:2.11.1]
[15:46:17] [Craft Scheduler Thread - 0/WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(2507973134), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo= )
[15:46:17] [nioEventLoopGroup-2-2/INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

系统是windows server2019，使用的是java17，使用了link2qq和chat2qq
这些是使用的插件
![image](https://user-images.githubusercontent.com/77454549/197471444-5b0a771b-11c2-4d17-bc5a-e8493fe1959d.png)
![image](https://user-images.githubusercontent.com/77454549/197471529-7d85f87f-283d-4169-84fe-b953c19425d9.png)

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
请确认机器人QQ号状态正常，已绑定手机号，且没有被风控。
