### ISSUE TITLE
”禁止登录“ ”当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试“

### ISSUE THREAD

**Issue by AmaranthineGate** [DreamVoid/MiraiMC#26]
<strong>问题描述</strong>

登陆出现错误
提示禁止登录, 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。tips=若频繁出现, 请尝试开启设备锁

<strong>复现方法</strong>

1. 使用滑块登陆
2. 进行登陆

<strong>版本类型</strong>
mohist-1.12.2-243-server
MiraiMC 1.3.2
* Minecraft 服务端版本：
* MiraiMC 插件版本：

<strong>服务器日志</strong>

```

[21:59:58] [Craft Scheduler Thread - 10/INFO] [Mohist]: [MiraiMC] 登录新的机器人账号: 1850616764, 协议: ANDROID_PHONE
[21:59:59] [Craft Scheduler Thread - 10/INFO] []: [92m2021-08-07 21:59:59 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.[0m
[21:59:59] [Craft Scheduler Thread - 10/INFO] []: [92m2021-08-07 21:59:59 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.[0m
[22:00:04] [DefaultDispatcher-worker-1/TRACE] [Mohist]: [MiraiMC] [BotSessionSyncer] No server list cached.
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:105)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:230)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:123)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.getDefaultInitialPublicKey(ECDH.kt:132)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.context.AccountSecretsKt.AccountSecretsImpl(AccountSecrets.kt:102)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:45)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:37)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:25)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:29)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:81)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:95)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:269)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: Caused by: java.util.jar.JarException: file:/D:/Game/Mohist-243/plugins/MiraiMC-release.jar has unsigned entries - net/mamoe/mirai/internal/network/impl/netty/NettyChannelException.class
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:502)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:363)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JarVerifier.verify(JarVerifier.java:289)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:164)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:190)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	at javax.crypto.JceSecurity.getInstance(JceSecurity.java:102)
[22:00:06] [DefaultDispatcher-worker-1/WARN] []: 	... 29 more
[22:00:06] [DefaultDispatcher-worker-1/INFO] [Mohist]: [MiraiMC] [ECDHInitialPublicKeyUpdater] ECDH key is invalid, start to fetch ecdh public key from server.
[22:00:08] [DefaultDispatcher-worker-1/INFO] [Mohist]: [MiraiMC] [ECDHInitialPublicKeyUpdater] Successfully fetched ecdh public key from server.
[22:00:09] [DefaultDispatcher-worker-1/TRACE] [Mohist]: [MiraiMC] Send: wtlogin.login
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] 当前登录的QQ（1850616764）需要滑动验证码验证
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=1850616764&sid=3184719595937108457&cap_cd=NJXsAwzFUohMDuoFldY1vIB7kifQ53XCYRjcAksxOL_6st-AGoQLpA**&clientype=1&apptype=2
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] 验证完成后，请输入指令 /miraiverify slidercaptcha 1850616764 <ticket>
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify slidercaptchacancel 1850616764
[22:00:09] [Thread-26/WARN] [Mohist]: [MiraiMC] 如需帮助，请参阅: https://github.com/DreamVoid/MiraiMC
[22:00:09] [DefaultDispatcher-worker-1/TRACE] [Mohist]: [MiraiMC] Recv: wtlogin.login
[22:00:48] [Server thread/INFO] []: 已将ticket提交到服务器
[22:00:48] [DefaultDispatcher-worker-3/TRACE] [Mohist]: [MiraiMC] Send: wtlogin.login
[22:00:48] [DefaultDispatcher-worker-3/TRACE] [Mohist]: [MiraiMC] Recv: wtlogin.login
[22:00:48] [DefaultDispatcher-worker-3/WARN] [Mohist]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1850616764), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:249) ~[MiraiMC-release.jar:?]
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-release.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [MiraiMC-release.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [MiraiMC-release.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [MiraiMC-release.jar:?]
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1850616764), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:249)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[22:00:48] [Craft Scheduler Thread - 10/WARN] []: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[22:00:48] [DefaultDispatcher-worker-2/INFO] [Mohist]: [MiraiMC] Bot cancelled: Bot closed

```

**Comment by DreamVoid** [comment]
腾讯风控，暂无有效解决方案。
请尝试在服务器上下载官方QQ登录机器人一段时间后再登录MiraiMC
