### ISSUE TITLE
任何QQ号无法登录

### ISSUE THREAD

**Issue by DiamBlog** [DreamVoid/MiraiMC#261]
### 问题描述

自10月23日前后起，本服务器机器人账号在服务器启动自动登录时显示"需要滑动验证"，按常规流程进行后，显示“当前QQ版本过低，无法登录”

#### 个人已经测试了多个QQ号，均相同错误无法登陆，基本排除QQ号风控问题
![IMG_20221030_001612](https://user-images.githubusercontent.com/71549402/198842338-3a511df7-e844-458f-b55e-c78eb15110d2.jpg)

### 复现方法

1. 启动服务器(插件被加载，开始自动登录)
2. (要求进行滑动验证) 按常规流程进行滑动验证
3. 输入命令miraiverify captcha xxxx [ticket]
4. 出现问题

### 服务端类型

Bukkit

### 服务端版本

PaperMC-1.19.2

### MiraiMC 插件版本

1.7

### 服务端日志

```text
[16:01:58 INFO]: 已将验证码提交到服务器
[16:01:58 WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(328858434), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[16:01:58 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(328858434), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登 录。点击进入下载页面, errorInfo=)
[16:01:58 INFO]: [MiraiMC] Bot cancelled: Bot closed
>
```

### 额外说明

从已经关闭的Issue看，已经有不止一人一个服务器出现了此问题

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Zhanan08** [comment]
一样的问题，希望尽快解决
