### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录

### ISSUE THREAD

**Issue by ApliNi** [DreamVoid/MiraiMC#264]
### 问题描述

使用默认配置. 
无法登录账号: `[MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot([QQ号]), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)`

### 复现方法

1. 使用 `/mirai login <账号> <密码>`登录账户
2. 在浏览器完成验证码, 从开发者工具中获取 ticket
3. 输入 `miraiverify captcha <账号> <ticket>`
4. 出现错误

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1825 (MC: 1.19.2)*

### MiraiMC 插件版本

This server is running MiraiMC version 1.7 by DreamVoid

### 服务端日志

```text
OpenJDK 64-Bit Server VM warning: JVM cannot use large page memory because it does not have enough privilege to lock pages in memory.
OpenJDK 64-Bit Server VM warning: UseAVX=3 is not supported on this CPU, setting it to UseAVX=2
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 17 (OpenJDK 64-Bit Server VM 17.0.3+7) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[16:06:33 INFO]: Building unoptimized datafixer
[16:06:34 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[16:06:37 INFO]: Loaded 7 recipes
[16:06:38 INFO]: Starting minecraft server version 1.19.2
[16:06:38 INFO]: Loading properties
[16:06:38 INFO]: This server is running Purpur version git-Purpur-1825 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: cf6b7c3 on HEAD)
[16:06:38 INFO]: Server Ping Player Sample Count: 0
[16:06:38 INFO]: Using 4 threads for Netty based IO
[16:06:38 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[16:06:39 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[16:06:39 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[16:06:39 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[16:06:39 INFO]: Default game type: SURVIVAL
[16:06:39 INFO]: Generating keypair
[16:06:39 INFO]: Starting Minecraft server on *:25565
[16:06:39 INFO]: Using default channel type
[16:06:39 INFO]: Paper: Using Java compression from Velocity.
[16:06:39 INFO]: Paper: Using Java cipher from Velocity.
[16:06:41 INFO]: [MiraiMC] Loading MiraiMC v1.7
[16:06:46 WARN]: [MiraiMC] Failed to get https://api.miraimc.dreamvoid.me/, reason: java.net.SocketTimeoutException: Connect timed out
[16:06:53 INFO]: [MiraiMC] Verifying mirai-core-all-2.11.1.jar
[16:06:54 INFO]: [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/2.11.1/mirai-core-all-2.11.1-all.jar
[16:07:01 INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.11.1.jar
[16:07:01 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[16:07:01 WARN]: The server will make no attempt to authenticate usernames. Beware.
[16:07:01 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[16:07:01 WARN]: You will not be offered any support as long as the server allows offline-mode players to join.
[16:07:01 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[16:07:01 INFO]: Preparing level "world"
[16:07:02 INFO]: [MiraiMC] Enabling MiraiMC v1.7
[16:07:02 INFO]: [MiraiMC] Mirai working dir: default
[16:07:02 INFO]: [MiraiMC] Starting Mirai-Events listener.
[16:07:02 INFO]: [MiraiMC] Loading auto-login file.
[16:07:02 INFO]: [MiraiMC] Registering commands.
[16:07:02 INFO]: [MiraiMC] Registering events.
[16:07:02 INFO]: [MiraiMC] Initializing SQLite database.
[16:07:02 INFO]: [MiraiMC] Initializing bStats metrics.
[16:07:02 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[16:07:02 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[16:07:02 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[16:07:02 INFO]: JMX monitoring enabled
[16:07:02 INFO]: Running delayed init tasks
[16:07:02 INFO]: Done (24.459s)! For help, type "help"
[16:07:02 INFO]: [MiraiMC] Checking update...
[16:07:02 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[16:07:02 INFO]: [MiraiMC] You are using the latest version!
[16:07:04 INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[16:07:04 INFO]: [MiraiMC] 腾讯已开始使用主动发送验证码的设备锁验证形式。
[16:07:04 INFO]: [MiraiMC] 如有用户遇到此类验证码或发现无论如何都无法通过设备锁验证，
[16:07:04 INFO]: [MiraiMC] 请前往GitHub开新issue，我将尽快提供支持。
[16:07:04 INFO]: [MiraiMC] 另外，暂时不要使用mirai 2.12.0，插件暂时没有进行适配。
[16:07:04 INFO]: [MiraiMC] 请先使用2.11.1核心。
[16:07:04 INFO]: [MiraiMC] =======================================
> mirai login [QQ号] [密码]
[16:07:21 INFO]: [MiraiMC] 登录新的机器人账号: [QQ号], 协议: ANDROID_PHONE
[16:07:22 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[16:07:22 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[16:07:22 WARN]: [MiraiMC] 当前登录的QQ（[QQ号]）需要滑动验证码验证
[16:07:22 WARN]: [MiraiMC] 请打开以下链接进行验证
[16:07:22 WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=[QQ号]&sid=3360816377553450683&cap_cd=Jq6odTWNgALtRulxHuZzA-g5rM3-P-JFlLNg_quxxq5pX4XdQFEyVQ**&clientype=1&apptype=2
[16:07:22 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify captcha [QQ号] <ticket>
[16:07:22 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel [QQ号]
[16:07:22 WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
> miraiverify captcha [QQ号] t031NbdK6Ryx_IOD29VFY5uKBjoEXrtP2S2XnPSh018Rokd3q3mHmoyBau9UmStznTsTBE_hBGMGycMYkfGOYeFjmQ-BJQw_72_vK7y0JYSP0EChkGrzFOd8k_PT1BQc-xwCcMdfn0r1M1TfHeU4L9mE2we_H7MeaxLzodLOVZgBF8VBe9VUtViy4ets43d0tyOUQtntvDsVOA*
[16:07:46 INFO]: 已将验证码提交到服务器
[16:07:46 WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot([QQ号]), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:284) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[16:07:46 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot([QQ号]), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[16:07:46 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

我尝试过在自己的电脑上登录, 添加启动参数 `-Dmirai.slider.captcha.supported`, 开启设备锁, 问题依旧. 

机器人账号可正常登录手机QQ, TIM和PC版TIM. 尝试过清空已登录设备, 问题依旧. 

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
临时解决方案，先使用mirai console loader登录一下机器人账号，然后把device.json复制到插件目录

**Comment by ApliNi** [comment]
> 临时解决方案，先使用mirai console loader登录一下机器人账号，然后把device.json复制到插件目录

谢谢, 复制 device.json 文件问题依旧. 复制整个 <QQ号> 目录登录成功.

**Comment by DiamBlog** [comment]
> > 临时解决方案，先使用mirai console loader登录一下机器人账号，然后把device.json复制到插件目录
> 
> 谢谢, 复制 device.json 文件问题依旧. 复制整个 <QQ号> 目录登录成功.
> 
> 1. 下载 [mirai console loader](https://github.com/iTXTech/mirai-console-loader).
> 2. 运行 mcl.cmd, 随后关闭.
> 3. 修改 config.json 中的3个版本号 `2.12.3` 为 `2.13.0`.
> 4. 运行 mcl.cmd.
> 5. 输入 `login <QQ号> <密码>`.
> 6. 根据弹出的窗口完成图形验证码和手机号验证.
> 7. 关闭 mirai console loader.
> 8. 复制 `bots/<QQ号>` 目录到服务器的 `MiraiMC/MiraiBot/bots/`.
> 9. 在服务器中使用 `/mirai login <QQ号> <密码>` 登录机器人.

使用此方法后机器人正常一天，之后偶然使用手机登录机器人导致其下线，之后重复此方法发现失效

**Comment by ApliNi** [comment]
> 使用此方法后机器人正常一天，之后偶然使用手机登录机器人导致其下线，之后重复此方法发现失效

如果只是挤下线，应该可以直接在服务器里使用登录指令重新登录

**Comment by DiamBlog** [comment]
> > 使用此方法后机器人正常一天，之后偶然使用手机登录机器人导致其下线，之后重复此方法发现失效
> 
> 如果只是挤下线，应该可以直接在服务器里使用登录指令重新登录

重新登陆后是要滑块，滑块之后又是版本过低

**Comment by xiantiao233** [comment]
使用本地mirai console loader登入正常，可以正常介绍消息
但切换本地服务端登入时
mirai login [QQ] [密码]
[10:56:50 INFO]: [MiraiMC] 登录新的机器人账号: [QQ], 协议: ANDROID_PHONE
[10:56:52 INFO]: [MiraiMC] Server list: 111.30.169.66:80, msfwifi.3g.qq.com:8080, 120.232.69.214:80, 120.232.130.74:8080, 36.155.213.231:14000, 36.155.248.239:80, 111.30.169.33:80, 120.232.69.213:443, 111.31.205.244:80, 111.31.200.210:14000.
[10:56:55 WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[10:56:55 WARN]:        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
[10:56:55 WARN]:        at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:191)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:181)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:230)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:225)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:107)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:122)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$startState$2.invokeSuspend(NettyNetworkHandler.kt:274)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
[10:56:55 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
[10:56:55 WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/D:/临时文件夹/miraimc/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.11.1.jar is not signed.
[10:56:55 WARN]:        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
[10:56:55 WARN]:        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
[10:56:55 WARN]:        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
[10:56:55 WARN]:        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
[10:56:55 WARN]:        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
[10:56:55 WARN]:        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
[10:56:55 WARN]:        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
[10:56:55 WARN]:        ... 39 more
[10:56:55 INFO]: [MiraiMC] Loaded account secrets from local cache.
[10:56:55 INFO]: [MiraiMC] ECDH key is valid.
[10:56:55 INFO]: [MiraiMC] Saved account secrets to local cache for fast login.
[10:56:55 INFO]: [MiraiMC] Server time updated, serverTime: 1668221813, diff: -2ms=-0.002s
[10:56:55 INFO]: [MiraiMC] Login successful.
[10:56:55 INFO]: [MiraiMC] Syncing friend message history...
[10:56:55 INFO]: [MiraiMC] Start loading stranger list...
[10:56:55 INFO]: [MiraiMC] Start loading friend list...
> 2022-11-12 10:56:56,141 Log4j2-AsyncAppenderEventDispatcher-1-Async ERROR An exception occurred processing Appender rewrite org.apache.logging.log4j.core.appender.AppenderLoggingException: java.lang.StackOverflowError
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:165)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:134)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:125)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:89)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatch(AsyncAppenderEventDispatcher.java:119)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.dispatchAll(AsyncAppenderEventDispatcher.java:81)
        at org.apache.logging.log4j.core.appender.AsyncAppenderEventDispatcher.run(AsyncAppenderEventDispatcher.java:63)
Caused by: java.lang.StackOverflowError
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateStacktrace(StacktraceDeobfuscator.java:63)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:37)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:43)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:43)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:43)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:43)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:40)
        at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:43)
        （循环300行）...
        at io.papermc.paper.

[10:56:55 INFO]: [MiraiMC] Bot cancelled: Bot closed
[10:56:55 WARN]: [MiraiMC] 登录机器人时出现异常，原因: 你的QQ号于09:59在【mirai】设备登录，当前设备已下线。如果这不是你 本人操作，那么你的QQ密码可能已经泄露，请尽快重新登录并修改密码

当时已经12：00了，但这个挤登入是9点的

如果在VPS登入 mirai console loader 
2022-11-12 11:05:33 E/console: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(671004109), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(671004109), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
>

**Comment by lianghuan88** [comment]
> > 临时解决方案，先使用mirai console loader登录一下机器人账号，然后把device.json复制到插件目录
> 
> 谢谢, 复制 device.json 文件问题依旧. 复制整个 <QQ号> 目录登录成功.
> 
> 1. 下载 [mirai console loader](https://github.com/iTXTech/mirai-console-loader).
> 2. 运行 mcl.cmd, 随后关闭.
> 3. 修改 config.json 中的3个版本号 `2.12.3` 为 `2.13.0`.
> 4. 运行 mcl.cmd.
> 5. 输入 `login <QQ号> <密码>`.
> 6. 根据弹出的窗口完成图形验证码和手机号验证.
> 7. 关闭 mirai console loader.
> 8. 复制 `bots/<QQ号>` 目录到服务器的 `MiraiMC/MiraiBot/bots/`.
> 9. 在服务器中使用 `/mirai login <QQ号> <密码>` 登录机器人

mirai console loader无法正常使用，尝试多个版本均为报 已升级请重新启动 这一提示。(java 17)

**Comment by ApliNi** [comment]
> 重新登陆后是要滑块，滑块之后又是版本过低

> mirai console loader无法正常使用，尝试多个版本均为报 已升级请重新启动 这一提示。(java 17)

尝试使用 2.1.2 版本的 mirai console loader, 我刚试过可以正常登录QQ. 不需要修改配置中的版本号.

**Comment by lianghuan88** [comment]
> > 重新登陆后是要滑块，滑块之后又是版本过低
> 
> > mirai console loader无法正常使用，尝试多个版本均为报 已升级请重新启动 这一提示。(java 17)
> 
> 尝试使用 [2.1.2 版本的 mirai console loader](https://github.com/iTXTech/mirai-console-loader/releases/tag/v2.1.2), 我刚试过可以正常登录QQ. 不需要修改配置中的版本号.

按照你的方法尝试了一遍，已成功登入，但是重启插件后继续出现此问题

**Comment by TUSITU123** [comment]
2.1.2版本的mirai console loader已经失效，也是提示当前QQ版本过低

**Comment by TUSITU123** [comment]
我试一下改配置文件吧

**Comment by TUSITU123** [comment]
改配置文件也不行

**Comment by MuSpring** [comment]
同样问题 无法解决

**Comment by 1713483284** [comment]
同样问题 无法解决 望请修复

**Comment by lanzhi6** [comment]
同样问题,希望能尽快修复

**Comment by jiangyin14** [comment]
同样问题，希望尽快修复

**Comment by qnmd1** [comment]
同样问题，望修复

**Comment by qnmd1** [comment]
在1.7mirai，spigot1.19.3有同样问题，希望作者能够修复或提出永久性解决方案，谢谢

**Comment by Unmeldy** [comment]
同样问题 希望尽快与最新版mirai核心适配 新出的功能解决了最近出现的限制

**Comment by DreamVoid** [comment]
最新开发版已修复（Bukkit）

**Comment by 1713483284** [comment]
> 最新开发版已修复（Bukkit）

大佬连夜修复辛苦了
但是有一个不幸的消息，就是没能完全修复
报错如下https://pastes.dev/QNZ0zO1nUJ
部署环境Mohist1.12最终版，Java-zulu1.8，系统linux，已反复测试多次均无法使用，MiraiMC插件为一小时前的最新开发版

**Comment by Unmeldy** [comment]
> > 最新开发版已修复（Bukkit）
> 
> 大佬连夜修复辛苦了 但是有一个不幸的消息，就是没能完全修复 日志如下https://pastes.dev/QNZ0zO1nUJ 部署环境Mohist1.12最终版，Java-zulu1.8，系统linux，已反复测试多次均无法使用，MiraiMC插件为一小时前的最新开发版

你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版

**Comment by Unmeldy** [comment]
> 你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版

你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版

**Comment by jiangyin14** [comment]
> > 你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版
> 
> 你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版


在https://github.com/DreamVoid/MiraiMC/actions/runs/3678274679
登录Github账号
点下边对应版本的Artifacts文件名即可下载

**Comment by Unmeldy** [comment]
> > > 你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版
> > 
> > 
> > 你好我想询问一下最新开发板在哪里下载呀 release里最近的是1.7正式版
> 
> 在https://github.com/DreamVoid/MiraiMC/actions/runs/3678274679 登录Github账号 点下边对应版本的Artifacts文件名即可下载

感谢

**Comment by Unmeldy** [comment]
> 最新开发版已修复（Bukkit）

https://pastes.dev/LQl5xCDgc1
出现了新的情况 下载不到核心？lib里是有的 报错后插件不可以使用

**Comment by jiangyin14** [comment]
大佬连夜修复辛苦了
但是有一个不幸的消息，就是没能完全修复
https://pastes.dev/YEJsvVX4GE

**Comment by Zhou-Shilin** [comment]
仍未修复

**Comment by ApliNi** [comment]
> 仍未修复

我几天前试过能正常使用，可能你遇到的问题不是这个

**Comment by Zhou-Shilin** [comment]
> > 仍未修复
> 
> 我几天前试过能正常使用，可能你遇到的问题不是这个

同样报错，qq版本过低 :(

**Comment by ApliNi** [comment]
> > > 仍未修复
> > 
> > 
> > 我几天前试过能正常使用，可能你遇到的问题不是这个
> 
> 同样报错，qq版本过低 :(

或许你需要重新打开一个问题并添加错误日志

**Comment by Zhou-Shilin** [comment]
> > > > 仍未修复
> > > 
> > > 
> > > 我几天前试过能正常使用，可能你遇到的问题不是这个
> > 
> > 
> > 同样报错，qq版本过低 :(
> 
> 或许你需要重新打开一个问题并添加错误日志

好的
