### ISSUE TITLE
能否尽快支持Mirai 2.13.0核心？

### ISSUE THREAD

**Issue by ColdeZhang** [DreamVoid/MiraiMC#267]
### 功能描述

Mirai 2.13.0开始支持短信解决设备锁问题

### 使用方法

[参考这个链接](https://mirai.mamoe.net/topic/1653/升级-mirai-至-2-13-0-rc-rc2-使用新的短信验证方法解决设备验证?lang=zh-CN)

### 额外说明

```
[22:13:12 WARN]: [MiraiMC] Plugin MiraiMC v1.7 generated an exception while executing task 482
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.IMirai
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:120) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:128) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:169) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:59) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-"77a50b9"]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-"77a50b9"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: java.lang.ExceptionInInitializerError
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.<clinit>(MessageProtocolFacade.kt) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:87) ~[MiraiMC-Bukkit.jar:?]
                at java.lang.Class.forName0(Native Method) ~[?:?]
                at java.lang.Class.forName(Class.java:375) ~[?:?]
                at net.mamoe.mirai.utils.ServicesKt.findCreateInstance(Services.kt:27) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:20) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:120) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:128) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:169) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:59) ~[MiraiMC-Bukkit.jar:?]
                at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.2.jar:git-Paper-"77a50b9"]
                at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.2.jar:git-Paper-"77a50b9"]
                at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.2.jar:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Caused by: java.lang.IllegalStateException: Failed to load services for MessageProtocol from your classpath. Check you ClassLoader environment and ensure services for 'net.mamoe.mirai.internal.message.protocol.MessageProtocol' can be loaded. This should not happen if you are using mirai under default JVM classloader or using Mirai Console.If so, please file an issue. If you are trying to load mirai manually from other classloader, e.g. in another plugin system like Minecraft, it's your responsibility to ensure the Java SPI works.
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:208) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.<init>(MessageProtocolFacade.kt:193) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<init>(MessageProtocolFacade.kt:162) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.<clinit>(MessageProtocolFacade.kt) ~[MiraiMC-Bukkit.jar:?]
                ... 21 more
```

_No response_

**Comment by CleMooling** [comment]
补充一下，现在Spigot端也会出现低版本报错，可能支持新核心可以解决
初步判断腾讯针对机器人框架进行了处理，将版本下限提升了导致这个问题（我的号已经不能在QQ HD版本登录）
另外希望支持扫码登录形式
