### ISSUE TITLE
登录显示null

### ISSUE THREAD

**Issue by tangjunyan2010** [DreamVoid/MiraiMC#279]
### 问题描述

/mirai login 334381196 231120 ANDROID_PHONE（密码不对哦）
显示null
![image](https://user-images.githubusercontent.com/107750621/208010439-7e9379f3-0310-46d5-bd83-4648ee3bb6af.png)

### 复现方法

1. 登陆不了

### 服务端类型

Bukkit

### 服务端版本

paper-1.8.8

### MiraiMC 插件版本

1.7

### 服务端日志

```text
.jar:git-PaperSpigot-445]
        at org.yaml.snakeyaml.Yaml.load(Yaml.java:369) ~[patched_1.8.8.jar:git-P
aperSpigot-445]
        at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlCo
nfiguration.java:55) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 21 more
[10:37:23 INFO]: [CoreLogging] Loading World & Settings - 'world' - Env: NORMAL
- Type: NORMAL & seed: 1654111368439418374
[10:37:23 INFO]: [CoreLogging] Loading World & Settings - 'world_nether' - Env:
NETHER - Type: NORMAL & seed: 1654111368439418374
[10:37:23 INFO]: [CoreLogging] Loading World & Settings - 'world_the_end' - Env:
 THE_END - Type: NORMAL & seed: 1654111368439418374
[10:37:23 ERROR]: Error occurred while enabling Multiverse-Core v4.3.1-SNAPSHOT-
b857 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/entity/Phantom
        at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.killDecision(
SimpleWorldPurger.java:152) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(Si
mpleWorldPurger.java:119) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(Si
mpleWorldPurger.java:197) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.SimpleWorldPurger.purgeWorld(Si
mpleWorldPurger.java:74) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.val
idateChange(MVWorld.java:286) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld$SpawningPropertyValidator.val
idateChange(MVWorld.java:260) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.serializationconfig.SerializationConfig.Serializatio
nConfig.validate(SerializationConfig.java:893) ~[Multiverse-Core-4.3.1-SNAPSHOT.
jar:?]
        at com.onarandombox.serializationconfig.SerializationConfig.Serializatio
nConfig.setPropertyValue(SerializationConfig.java:443) ~[Multiverse-Core-4.3.1-S
NAPSHOT.jar:?]
        at com.onarandombox.serializationconfig.SerializationConfig.Serializatio
nConfig.setPropertyValue(SerializationConfig.java:368) ~[Multiverse-Core-4.3.1-S
NAPSHOT.jar:?]
        at com.onarandombox.serializationconfig.SerializationConfig.Serializatio
nConfig.setPropertyValue(SerializationConfig.java:353) ~[Multiverse-Core-4.3.1-S
NAPSHOT.jar:?]
        at com.onarandombox.serializationconfig.SerializationConfig.Serializatio
nConfig.setPropertyValueUnchecked(SerializationConfig.java:736) ~[Multiverse-Cor
e-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.WorldProperties.setAllowAnimalSpawn(W
orldProperties.java:424) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld.setAllowAnimalSpawn(MVWorld.j
ava:767) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld.validateEntitySpawns(MVWorld.
java:195) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld.validateProperties(MVWorld.ja
va:205) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:94) ~[Mul
tiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MVWorld.<init>(MVWorld.java:59) ~[Mul
tiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManage
r.java:496) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldMana
ger.java:288) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.addWorld(WorldMana
ger.java:228) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.utils.WorldManager.loadDefaultWorlds(
WorldManager.java:717) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCor
e.java:312) ~[Multiverse-Core-4.3.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[p
atched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:481) [R
esidence5.0.0.1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [pa
tched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:332) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:407) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.jav
a:359) [patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.
java:318) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:4
08) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:3
72) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:3
27) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.jav
a:267) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:563) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.entity.Phantom
        ... 37 more
[10:37:23 INFO]: [Multiverse-Core] Disabling Multiverse-Core v4.3.1-SNAPSHOT-b85
7
[10:37:23 INFO]: [AuthMe] Multiverse-Core has been disabled: unhooking
[10:37:23 INFO]: [Residence] Found Vault using permissions plugin:LuckPerms

[10:37:23 INFO]: [Residence] Scanning for economy systems...

[10:37:23 INFO]: [Residence] Found Vault using economy system: XConomy

[10:37:24 INFO]: [Residence] Loading save data for world world...

[10:37:24 INFO]: [Residence] Loaded world data. (5 ms)

[10:37:24 INFO]: [Residence] Loading save data for world world_the_end...

[10:37:24 INFO]: [Residence] Loaded world_the_end data. (0 ms)

[10:37:24 INFO]: [Residence] Loading save data for world world_nether...

[10:37:24 INFO]: [Residence] Loaded world_nether data. (2 ms)

[10:37:24 INFO]: [Residence] Loading world data into memory...

[10:37:24 INFO]: [Residence] Loaded world data into memory. (1 ms) -> 0 residenc
es

[10:37:24 INFO]: [Residence] Loading world_the_end data into memory...

[10:37:24 INFO]: [Residence] Loaded world_the_end data into memory. (0 ms) -> 0
residences

[10:37:24 INFO]: [Residence] Loading world_nether data into memory...

[10:37:24 INFO]: [Residence] Loaded world_nether data into memory. (0 ms) -> 0 r
esidences

[10:37:24 INFO]: [Residence] WorldEdit NOT found!

[10:37:24 INFO]: [PlaceholderAPI] Successfully registered expansion: residence
[10:37:24 INFO]: [Residence] PlaceholderAPI hooked.

[10:37:24 INFO]: [Residence] PlaceholderAPI was found - Enabling capabilities.

[10:37:24 INFO]: [Residence] Enabled! Version 5.0.0.1 by Zrips

[10:37:25 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:37:25 INFO]: Done (24.885s)! For help, type "help" or "?"
[10:37:25 INFO]: Timings Reset
[10:37:25 INFO]: [Essentials] Essentials found a compatible payment resolution m
ethod: Vault Compatibility Layer (v1.7.3-b131)!
[10:37:25 INFO]: [ViaVersion] ViaVersion detected server version: 1.8.x (47)
[10:37:25 WARN]: [ViaVersion] This version of Minecraft is extremely outdated an
d support for it has reached its end of life. You will still be able to run Via
on this Minecraft version, but we are unlikely to provide any further fixes or h
elp with problems specific to legacy Minecraft versions. Please consider updatin
g to give your players a better experience and to avoid issues that have long be
en fixed.
[10:37:25 INFO]: [Essentials] §6正在获取版本信息...
[10:37:25 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[10:37:25 INFO]: [MiraiMC] Checking update...
[10:37:25 INFO]: [MiraiMC] You are using the latest version!
[10:37:25 INFO]: [AuthMe] Downloading GEO IP database, because the old database
is older than 30 days or doesn't exist
[10:37:25 WARN]: [AuthMe] No MaxMind credentials found in the configuration file
! GeoIp protections will be disabled.
[10:37:25 INFO]: [AuthMe] There is no newer GEO IP database uploaded to MaxMind.
 Using the old one for now.
[10:37:25 INFO]: [PlaceholderAPI] Placeholder expansion registration initializin
g...
[10:37:25 WARN]: [AuthMe] Could not download GeoLiteAPI database [FileNotFoundEx
ception]: plugins\AuthMe\GeoLite2-Country.mmdb (系统找不到指定的文件。)
[10:37:25 INFO]: [PlayerTitle] 检测到使用的公开版,限制称号上限100,感谢您的使用..
.

[10:37:25 INFO]: [PlayerTitle] 完整版无任何限制,请联系作者购买QQ:956812056

[10:37:25 INFO]: [PlayerTitle] 获取云汉化数据成功...

[10:37:26 INFO]: [PlayerTitle] 检测到最新版本:3.1.7更新内容:3.1.7

[10:37:26 WARN]: [Essentials] §4你正在运行的EssentialsX已过期§c219§4个开发版
本！
[10:37:26 WARN]: [Essentials] §4在此处下载：§chttps://essentialsx.net/download
s.html
[10:37:26 INFO]: [Citizens] 已载入 1 个NPC.
[10:37:26 INFO]: [ViaVersion] Finished mapping loading, shutting down loader exe
cutor!
[10:37:26 INFO]: [Vault] Checking for Updates ...
[10:37:26 INFO]: [SkinsRestorer] ----------------------------------------------

[10:37:26 INFO]: [SkinsRestorer]     +==================+

[10:37:26 INFO]: [SkinsRestorer]     |   SkinsRestorer  |

[10:37:26 INFO]: [SkinsRestorer]     |------------------|

[10:37:26 INFO]: [SkinsRestorer]     |  Standalone Mode |

[10:37:26 INFO]: [SkinsRestorer]     +==================+

[10:37:26 INFO]: [SkinsRestorer] ----------------------------------------------

[10:37:26 INFO]: [SkinsRestorer]     Current version: 14.2.3

[10:37:26 INFO]: [SkinsRestorer]     This is the latest version!

[10:37:26 INFO]: [SkinsRestorer] ----------------------------------------------

[10:37:26 INFO]: [XConomy] 发现新版本 2.19.5
[10:37:26 INFO]: [XConomy] https://www.spigotmc.org/resources/xconomy.75669/
[10:37:26 INFO]: [XConomy] https://www.mcbbs.net/thread-962904-1-1.html
[10:37:26 INFO]: _________________/ Residence \_________________
| 5.1.0.1 is now available! Your version: 5.0.0.1
----------------------------------------

[10:37:26 INFO]: No expansions were registered!

[10:37:26 INFO]: [PlaceholderAPI] An update for PlaceholderAPI (v2.11.2) is avai
lable at:
[10:37:26 INFO]: [PlaceholderAPI] https://www.spigotmc.org/resources/placeholder
api.6245/
[10:37:27 WARN]: [ViaVersion] There is a newer plugin version available: 4.5.1,
you're on: 4.4.0
[10:37:28 INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[10:37:28 INFO]: [MiraiMC] 1.7.1 已适配 mirai 2.12.0 及以上版本，
[10:37:28 INFO]: [MiraiMC] 请及时更新使用。
[10:37:28 INFO]: [MiraiMC] =======================================
[10:37:36 INFO]: [Vault] No new version available
[10:46:18 INFO]: UUID of player _11_4514 is 3f13aed1-5314-3623-ae75-7500f98b2c48

[10:46:20 INFO]: _11_4514[/127.0.0.1:56328] logged in with entity id 123 at ([wo
rld]-241.61200013115948, 70.0, 174.89789485907403)
[10:46:23 WARN]: [Essentials] Permissions lag notice with (LuckPermsHandler). Re
sponse took 71.186900ms. Summary: Getting prefix for _11_4514
[10:46:34 INFO]: [AuthMe] _11_4514 logged in 127.0.0.1
[10:46:40 INFO]: _11_4514 issued server command: /mirai login 334381196 Xqdzyhdy
0 ANDROID_PHONE
[10:46:40 INFO]: [MiraiMC] 登录新的机器人账号: 334381196, 协议: ANDROID_PHONE
[10:46:47 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.impl.netty.NettyChannelException: null
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.creat
eConnection$suspendImpl(NettyNetworkHandler.kt:116) ~[mirai-core-all-2.13.2.jar:
2.13.2]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$creat
eConnection$1.invokeSuspend(NettyNetworkHandler.kt) ~[mirai-core-all-2.13.2.jar:
2.13.2]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Contin
uationImpl.kt:33) [mirai-core-all-2.13.2.jar:2.13.2]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) [mirai-c
ore-all-2.13.2.jar:2.13.2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineS
cheduler.kt:570) [mirai-core-all-2.13.2.jar:2.13.2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(C
oroutineScheduler.kt:750) [mirai-core-all-2.13.2.jar:2.13.2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(Cor
outineScheduler.kt:677) [mirai-core-all-2.13.2.jar:2.13.2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(Coroutine
Scheduler.kt:664) [mirai-core-all-2.13.2.jar:2.13.2]
Caused by: java.nio.channels.UnresolvedAddressException
        at sun.nio.ch.Net.checkAddress(Net.java:149) ~[?:?]
        at sun.nio.ch.Net.checkAddress(Net.java:157) ~[?:?]
        at sun.nio.ch.SocketChannelImpl.checkRemote(SocketChannelImpl.java:816)
~[?:?]
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:839) ~[?:
?]
        at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChann
el.java:193) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(Abs
tractNioChannel.java:200) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultCh
annelPipeline.java:1029) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(Abstract
ChannelHandlerContext.java:496) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChanne
lHandlerContext.java:481) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboun
dHandlerAdapter.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(Abstract
ChannelHandlerContext.java:496) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChanne
lHandlerContext.java:481) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChanne
lHandlerContext.java:463) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipelin
e.java:849) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[
patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[patched_1.8.
8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
ThreadEventExecutor.java:380) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[patche
d_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThread
EventExecutor.java:116) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorato
r.run(DefaultThreadFactory.java:137) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:46:47 WARN]: [MiraiMC] Network selector received exception, closing bot. (Ne
ttyChannelException(message=null, cause=java.nio.channels.UnresolvedAddressExcep
tion))
[10:46:47 INFO]: [MiraiMC] Bot cancelled: Bot closed
[10:46:47 WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
>
```

### 额外说明

java 8
最新版

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
自行检查服务器网络

**Comment by tangjunyan2010** [comment]
tcp链接全部打开

**Comment by tangjunyan2010** [comment]
求助
