### ISSUE TITLE
无法登录，报错

### ISSUE THREAD

**Issue by xiaovoaix** [DreamVoid/MiraiMC#28]
服务器版本1.7.10 Uranium核心 模组服
MiraiMC版本1.3.2
Chat2qq版本1.2.2
报错内容如下：
[19:42:03 INFO]: [MiraiMC] 登录新的机器人账号: xxxxx, 协议: ANDROID_PHONE
[19:42:04 WARN]: Exception in thread "Craft Scheduler Thread - 0"
[19:42:04 WARN]: org.apache.commons.lang.UnhandledException: Plugin MiraiMC v1.3.2 generated an exception while executing task 3
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at io.ktor.client.HttpClientConfig.<clinit>(HttpClientConfig.kt)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
        at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:136)
        at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt:70)
        at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt)
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cc.uraniummc.util.NMSClassUtil.forName0(NMSClassUtil.java:51)
        at cc.uraniummc.util.NMSClassUtil.forName(NMSClassUtil.java:37)
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119)
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:161)
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94)
        at me.dreamvoid.miraimc.bukkit.CommandProcessor$1.run(CommandProcessor.java:59)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
和
[19:42:40 INFO]: [MiraiMC] 登录新的机器人账号: xxxxxxx, 协议: ANDROID_PHONE
[19:42:40 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[19:42:40 WARN]: org.apache.commons.lang.UnhandledException: Plugin MiraiMC v1.3.2 generated an exception while executing task 4
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.internal.MiraiImpl
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cc.uraniummc.util.NMSClassUtil.forName0(NMSClassUtil.java:51)
        at cc.uraniummc.util.NMSClassUtil.forName(NMSClassUtil.java:37)
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119)
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:161)
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94)
        at me.dreamvoid.miraimc.bukkit.CommandProcessor$1.run(CommandProcessor.java:59)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
第一个为初次登陆时弹出，第二个为多次登录弹出
求解

**Comment by xiaovoaix** [comment]
@DreamVoid

**Comment by DreamVoid** [comment]
见 #22
Kotlin相关报错一般为Mirai Core核心问题，我在测试环境和生产环境（我自己服务器）测试时均没有出现过此问题，因此我暂时找不到解决方案

**Comment by xiaovoaix** [comment]
行叭orz

**Comment by DreamVoid** [comment]
1.5版本准备修复

**Comment by DreamVoid** [comment]
不好意思，修不了，换别的端吧

**Comment by DreamVoid** [comment]
https://wiki.miraimc.dreamvoid.ml/troubleshoot/compatibility-report/cauldron

**Comment by xiaovoaix** [comment]
枯了，1.7.10就只有这一系列的核心好用啊orz
