### ISSUE TITLE
mirai login 账号无法添加

### ISSUE THREAD

**Issue by justLxy** [DreamVoid/MiraiMC#283]
### 问题描述

在我输入mirai login 账号 密码的时候报错，无法添加账号。

### 复现方法

1. mirai login 账号 密码

### 服务端类型

Bukkit

### 服务端版本

paper 1.16.5

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[10:57:20] [Craft Scheduler Thread - 40/INFO]: [MiraiMC] 登录新的机器人账号: 3045945, 协议: ANDROID_PHONE
[10:57:20] [Craft Scheduler Thread - 40/WARN]: [MiraiMC] Plugin MiraiMC v1.7.1 generated an exception while executing task 14712
java.util.ServiceConfigurationError: net.mamoe.mirai.IMirai: Provider net.mamoe.mirai.internal.MiraiImpl could not be instantiated
at java.util.ServiceLoader.fail(ServiceLoader.java:582) ~[?:?]
at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:804) ~[?:?]
at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722) ~[?:?]
at java.util.ServiceLoader$3.next(ServiceLoader.java:1395) ~[?:?]
at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:240) ~[org.kotlinlang-kotlin-stdlib-1.4.20.jar:1.4.20-release-308 (1.4.20)]
at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:18) ~[?:?]
at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[?:?]
at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[?:?]
at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[?:?]
at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:120) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:132) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:173) ~[?:?]
at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:63) ~[?:?]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.16.5.jar:git-Paper-794]
at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.5.jar:git-Paper-794]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Paper-794]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.NoSuchMethodError: 'int kotlin.text.CharsKt.digitToInt(char, int)'
at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.parseFromHexChunk(Conversions.kt:201) ~[?:?]
at net.mamoe.mirai.utils.MiraiUtils.parseFromHexChunk(Unknown Source) ~[?:?]
at net.mamoe.mirai.utils.MiraiUtils__ConversionsKt.hexToBytes(Conversions.kt:187) ~[?:?]
at net.mamoe.mirai.utils.MiraiUtils.hexToBytes(Unknown Source) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.encode.MessageEncoderPipelineImpl.(MessageEncoderPipeline.kt:83) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.(MessageProtocolFacade.kt:197) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacadeImpl.(MessageProtocolFacade.kt:193) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.(MessageProtocolFacade.kt:162) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade$INSTANCE.(MessageProtocolFacade.kt) ~[?:?]
at net.mamoe.mirai.internal.message.protocol.MessageProtocolFacade.(MessageProtocolFacade.kt) ~[?:?]
at net.mamoe.mirai.internal.MiraiImplKt._MiraiImpl_static_init(MiraiImpl.kt:25) ~[?:?]
at net.mamoe.mirai.internal.MiraiImpl.(MiraiImpl.kt:94) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780) ~[?:?]
... 18 more
```

### 额外说明

java 11, linux

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
仔细阅读issue表单的注意事项并认真填写所有内容，多次无效的spam issue将会被永久禁止在本仓库活动

**Comment by justLxy** [comment]
> 仔细阅读issue表单的注意事项并认真填写所有内容，多次无效的spam issue将会被永久禁止在本仓库活动

???
