### ISSUE TITLE
登录

### ISSUE THREAD

**Issue by Moki0** [DreamVoid/MiraiMC#296]
### 问题描述

登录机器人过程，输入miraiverify captcha 确认验证码后。收到信息 “已将验证码提交到服务器” 随后出现 “登录机器人时出现异常，原因: Timed out waiting for 5000 ms” 的错误
![image](https://user-images.githubusercontent.com/28671602/209447499-ce287d98-e259-4fca-acf0-6e7afea086b0.png)

### 复现方法

复现方法如上

### 服务端类型

Bukkit

### 服务端版本

Paper-1.19.2

### MiraiMC 插件版本

This server is running MiraiMC version 1.7.1 by DreamVoid

### 服务端日志

```text
> mirai login 
[02:21:16 INFO]: [MiraiMC] 登录新的机器人账号: , 协议: ANDROID_PHONE
[02:21:22 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[02:21:22 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[02:21:22 WARN]: [MiraiMC] 当前登录的QQ（）需要滑动验证码验证
[02:21:22 WARN]: [MiraiMC] 请打开以下链接进行验证
[02:21:22 WARN]: [MiraiMC] https:
[02:21:22 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify captcha <ticket>
[02:21:22 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel 
[02:21:22 WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
> miraiverify captcha 
[02:22:17 INFO]: 已将验证码提交到服务器
[02:22:27 WARN]: [MiraiMC] Exception in resumeConnection.
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:508) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108) ~[MiraiMC-Bukkit.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[02:22:27 WARN]: [MiraiMC] Network selector received exception, closing bot. (kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 5000 ms)
[02:22:27 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Timed out waiting for 5000 ms
[02:22:27 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by windxu233** [comment]
aaa
