### ISSUE TITLE
【邮件请求】新的附属插件：Report2QQ

### ISSUE THREAD

**Issue by DreamVoid** [DreamVoid/MiraiMC#30]
<strong>功能描述</strong>

服务器服主时常不在线，又有很多玩家没有加入服务器交流群。这时，有玩家想要报告其他玩家的行为就会非常麻烦。此时可以开发一款举报插件，让玩家在服务器内输入指令来举报其他玩家的所作所为

<strong>使用方法</strong>

1. 使用一款新的插件（初步取名为“Report2QQ”）；
2. 玩家键入指令、玩家名、玩家所做的事情并提交；
3. Bot端收到指令，并向指定的QQ号或群发送消息；
4. 管理人员私聊Bot某个前缀或事件ID外加事件的处理结果；
5. 玩家在线/下一次上线时，插件可以显示事件的处理结果。

**Comment by xiaovoaix** [comment]
挺好，不过那个无法修复的bug啥时候弄（雾），用不了这个真的很头疼啊，1.7能用的机器人貌似就这一个（悲）

**Comment by DreamVoid** [comment]
> 挺好，不过那个无法修复的bug啥时候弄（雾），用不了这个真的很头疼啊，1.7能用的机器人貌似就这一个（悲）

什么bug

**Comment by xiaovoaix** [comment]
#22 #28 
这个

**Comment by xiaovoaix** [comment]
需要完整日志的话也可以提供，不过应该没什么用orz

**Comment by xiaovoaix** [comment]
[latest.log](https://github.com/DreamVoid/MiraiMC/files/7193564/latest.log)

**Comment by xiaovoaix** [comment]
https://ws28.cn/f/6fualkyl2g5
这是测试服务端
插件版本1.4

**Comment by DreamVoid** [comment]
> #22 #28
> 这个

1.5开始mirai核心改为外部加载了，这个问题应该可以修复，你可以去 ci.dreamvoid.ml 下载开发版测试一下

**Comment by xiaovoaix** [comment]
> > #22 #28
> > 这个
> 
> 1.5开始mirai核心改为外部加载了，这个问题应该可以修复，你可以去[构建站](https://ci.dreamvoid.ml)下载开发版测试一下

还是不行，同样的报错，用的是dev-28

**Comment by xiaovoaix** [comment]
[14:43:41 INFO]: [MiraiMC] 登录新的机器人账号: xxxxxxxx, 协议: ANDROID_PHONE
[14:43:42 WARN]: Exception in thread "Craft Scheduler Thread - 1"
[14:43:42 WARN]: org.apache.commons.lang.UnhandledException: Plugin MiraiMC vdev-25 generated an exception while executing task 3
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
        at io.ktor.client.HttpClientConfig.<clinit>(HttpClientConfig.kt)
        at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41)
        at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:146)
        at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt:72)
        at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt)
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cc.uraniummc.util.NMSClassUtil.forName0(NMSClassUtil.java:51)
        at cc.uraniummc.util.NMSClassUtil.forName(NMSClassUtil.java:37)
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119)
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:174)
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:91)
        at me.dreamvoid.miraimc.bukkit.Commands$1.run(Commands.java:60)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
**===================================================**
[14:43:43 INFO]: [MiraiMC] 登录新的机器人账号: xxxxxx, 协议: ANDROID_PHONE
[14:43:43 WARN]: Exception in thread "Craft Scheduler Thread - 2"
[14:43:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin MiraiMC vdev-25 generated an exception while executing task 4
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.internal.MiraiImpl
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at cc.uraniummc.util.NMSClassUtil.forName0(NMSClassUtil.java:51)
        at cc.uraniummc.util.NMSClassUtil.forName(NMSClassUtil.java:37)
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18)
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347)
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43)
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119)
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:174)
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:91)
        at me.dreamvoid.miraimc.bukkit.Commands$1.run(Commands.java:60)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
