### ISSUE TITLE
MiraiMC现版本无法登录QQ账号

### ISSUE THREAD

**Issue by WHF-Nirvana** [DreamVoid/MiraiMC#307]
### 问题描述

MiraiMC现版本无法登录QQ账号，起初提示QQ版本过低，后提示当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。

### 复现方法

1. 安装插件
2. 启动服务端
3. 登录账号，协议选MACOS或默认

### 服务端类型

BungeeCord

### 服务端版本

waterfall-1.19-510

### MiraiMC 插件版本

This server is running MiraiMC version 1.7.1 by DreamVoid

### 服务端日志

```text
> mirai login 2378788625 Homo@114514 MACOS
[00:27:57 INFO]: CONSOLE executed command: /mirai login 23******25 Ho*******14 MACOS
[00:27:57 INFO] [MiraiMC]: 登录新的机器人账号: 23******25, 协议: MACOS
[00:27:58 INFO] [MiraiMC]: ECDH key is invalid, start to fetch ecdh public key from server.
[00:27:59 INFO] [MiraiMC]: Successfully fetched ecdh public key from server.
[00:27:59 WARN] [MiraiMC]: 当前登录的QQ（23******25）需要滑动验证码验证
[00:27:59 WARN] [MiraiMC]: 请打开以下链接进行验证
[00:27:59 WARN] [MiraiMC]: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2378788625&sid=4720154500037716240&cap_cd=bj_fDFARJ3rhP3Uoo037-BRNP3sPmY543Ah2hv9nNjtNysHHQnzeUg**&clientype=1&apptype=2
[00:27:59 WARN] [MiraiMC]: 验证完成后，请输入指令 /miraiverify captcha 2378788625 <ticket>
[00:27:59 WARN] [MiraiMC]: 如需取消登录，请输入指令 /miraiverify cancel 2378788625
[00:27:59 WARN] [MiraiMC]: 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
> miraiverify captcha 23******25 t03_dGEx9rxVLFRsfEcCDm0WZL8svbzHqgaMfPvFkSI-jQcQ1_cVZgAaUZ5zVApU8FBDpX8nTB7zKzSO9V1sHUKR5eCf6O8Y9I-UExWMXWrjHi9h1-u1iBNu4QEY2KUgUDGJ1_ltZcbccE*
[00:28:35 INFO]: CONSOLE executed command: /miraiverify captcha 2378788625 t03_dGEx9rxVLFRsfEcCDm0WZL8svbzHqgaMfPvFkSI-jQcQ1_cVZgAaUZ5zVApU8FBDpX8nTB7zKzSO9V1sHUKR5eCf6O8Y9I-UExWMXWrjHi9h1-u1iBNu4QEY2KUgUDGJ1_ltZcbccE*
[00:28:35 INFO]: 已将验证码提交到服务器
[00:28:35 WARN] [MiraiMC]: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2378788625), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[?:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2378788625), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[?:?]
        ... 9 more
[00:28:35 WARN] [MiraiMC]: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2378788625), code=237, title=安 全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=))
[00:28:35 WARN] [MiraiMC]: 登录机器人时出现异常，原因: Error(bot=Bot(2323******2525), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
[00:28:35 INFO] [MiraiMC]: Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by LiteCat0905** [comment]
这个在常见问题有案例了

**Comment by LiteCat0905** [comment]
6月7日更新
Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)

删除 device.json, 对于 mirai-console 位于 bots/**/ 内

**Comment by LiteCat0905** [comment]
临时解决方案来自：https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88

**Comment by WHF-Nirvana** [comment]
目前已经解决了。我等待了一段时间后再使用ANDROID_PHONE协议进行登录后正常登录。
