### ISSUE TITLE
登录提示“当前上网环境异常，请更换网络环境或在常用设备上登录 或稍后再试。”

### ISSUE THREAD

**Issue by XXTG666** [DreamVoid/MiraiMC#31]
<strong>问题描述</strong>

登录机器人提示“当前上网环境异常，请更换网络环境或在常用设备上登录 或稍后再试。”

<strong>复现方法</strong>

完成滑动验证码之后出现此提示

<strong>版本类型</strong>

* Minecraft 服务端版本：Spigot-1.17.1
* MiraiMC 插件版本：1.3.2

<strong>服务器日志</strong>

```
[17:33:42] [Craft Scheduler Thread - 0/INFO]: [MiraiMC] 登录新的机器人账号: 1***6, 协议: ANDROID_PHONE
[17:33:43] [Craft Scheduler Thread - 0/INFO]: 2021-08-15 17:33:43 I/Mirai: Mirai 正在使用桌面环境. 如遇到验证码将会弹出 对话框. 可添加 JVM 属性 `mirai.no-desktop` 以关闭.
[17:33:43] [Craft Scheduler Thread - 0/INFO]: 2021-08-15 17:33:43 I/Mirai: Mirai is using desktop. Captcha will be thrown by window popup. You can add `mirai.no-desktop` to JVM properties (-Dmirai.no-desktop) to disable it.
[17:33:52] [DefaultDispatcher-worker-3/WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:123)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt$defaultInitialPublicKey$2.invoke(ECDH.kt:132)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.utils.crypto.ECDHKt.getDefaultInitialPublicKey(ECDH.kt:132)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.context.AccountSecretsKt.AccountSecretsImpl(AccountSecrets.kt:102)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:45)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:37)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:25)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:29)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:29)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:81)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:95)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:269)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[17:33:52] [DefaultDispatcher-worker-3/WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/D:/桌面/mcmairl/plugins/MiraiMC-release.jar is not signed.
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:463)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:316)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:259)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:127)
[17:33:52] [DefaultDispatcher-worker-3/WARN]:   ... 29 more
[17:33:53] [DefaultDispatcher-worker-3/INFO]: [MiraiMC] [ECDHInitialPublicKeyUpdater] ECDH key is invalid, start to fetch ecdh public key from server.
[17:33:54] [DefaultDispatcher-worker-3/INFO]: [MiraiMC] [ECDHInitialPublicKeyUpdater] Successfully fetched ecdh public key from server.
[17:33:56] [Thread-16/WARN]: [MiraiMC] 当前登录的QQ（1***6）需要滑动验证码验证
[17:33:56] [Thread-16/WARN]: [MiraiMC] 请使用手机QQ打开以下链接进行验证
[17:33:56] [Thread-16/WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=1***6&sid=6770428396541894531&cap_cd=2OSFSU_1t0982kL7xLiAlZuADVUtizzSdNiCuZizHqfieSS7bc030w**&clientype=1&apptype=2
[17:33:56] [Thread-16/WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify slidercaptcha 1***6 <ticket>
[17:33:56] [Thread-16/WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify slidercaptchacancel 1***6
[17:33:56] [Thread-16/WARN]: [MiraiMC] 如需帮助，请参阅: https://github.com/DreamVoid/MiraiMC
>miraiverify slidercaptcha 1***6 t03wpuYztJ69md6w8DvtKFqhdu3Q-h6mOuuQuKkxLhMYd6qOvFLDAaZMj4cV6ZOE3Tw23iThAoqELbFUfX0iuLsCpOdLB3JakALJODxR6232LFFolEJqRwZ5khtVexMFsYY
[17:34:55] [Server thread/INFO]: 已将ticket提交到服务器
[17:34:55] [DefaultDispatcher-worker-4/WARN]: [MiraiMC] null
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1***6), code=237, title=禁止登录, message=当前上网环 境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:249) ~[MiraiMC-release.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-release.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [MiraiMC-release.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [MiraiMC-release.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [MiraiMC-release.jar:?]
[17:34:56] [Craft Scheduler Thread - 0/WARN]: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1***6), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若 频繁出现, 请尝试开启设备锁
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:249)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[17:34:56] [Craft Scheduler Thread - 0/WARN]:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[17:34:56] [DefaultDispatcher-worker-4/INFO]: [MiraiMC] Bot cancelled: Bot closed
```
注：我启动时加上了 -Dmirai.slider.captcha.supported  参数，并且在使用miraimc登录机器人之前已经在电脑上登录电脑端QQ，可以正常登录

**Comment by DreamVoid** [comment]
#26
