### ISSUE TITLE
MiraiMCQQ号无法正常登陆

### ISSUE THREAD

**Issue by pangzai82008** [DreamVoid/MiraiMC#313]
### 问题描述

使用过程中突然发生QQ号在群内无回应，重启服务器发现无法登陆QQ号

### 复现方法

1. 安装插件
2. 启动服务端
3. 正常登陆步骤，协议选ANDROID_PHONE和PAD会出现其余没测试
4. 输入滑动验证key之后出现异常

### 服务端类型

Bukkit

### 服务端版本

purpur-1.19.3

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[18:23:37] [Craft Scheduler Thread - 20 - Vault/INFO]: [Vault] No new version available
[18:23:39] [Craft Scheduler Thread - 12 - MiraiMC/INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[18:23:39] [Craft Scheduler Thread - 12 - MiraiMC/INFO]: [MiraiMC] 1.7.1 已适配 mirai 2.12.0 及以上版本，
[18:23:39] [Craft Scheduler Thread - 12 - MiraiMC/INFO]: [MiraiMC] 请及时更新使用。
[18:23:39] [Craft Scheduler Thread - 12 - MiraiMC/INFO]: [MiraiMC] =======================================
[18:25:43] [Craft Scheduler Thread - 23 - MiraiMC/INFO]: [MiraiMC] 登录新的机器人账号: 1249545099, 协议: ANDROID_PAD
[18:25:44] [DefaultDispatcher-worker-3/INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[18:25:45] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[18:25:46] [Thread-28/WARN]: [MiraiMC] 当前登录的QQ（1249545099）需要滑动验证码验证
[18:25:46] [Thread-28/WARN]: [MiraiMC] 请打开以下链接进行验证
[18:25:46] [Thread-28/WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=1249545099&sid=7219971533853414570&cap_cd=f5e2pxoAtRCEcNwCHt_-UD_vRqyVc9fchd5R2KEqXS4YfdLyPyNb9g**&clientype=1&apptype=2
[18:25:46] [Thread-28/WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify captcha 1249545099 <ticket>
[18:25:46] [Thread-28/WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel 1249545099
[18:25:46] [Thread-28/WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
[18:26:22] [Server thread/INFO]: 已将验证码提交到服务器
[18:26:22] [DefaultDispatcher-worker-2/WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1249545099), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1249545099), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        ... 9 more
[18:26:22] [DefaultDispatcher-worker-2/WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1249545099), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=))
[18:26:22] [Craft Scheduler Thread - 23 - MiraiMC/WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(1249545099), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)
[18:26:22] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Bot cancelled: Bot closed
miraimc
[18:31:52 INFO]: This server is running MiraiMC version 1.7.1 by DreamVoid
[18:31:52 INFO]: For help, type /miraimc help
>
```

### 额外说明

重置了插件配置，问题依然存在
在此之前一直是正常运行的

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by YuanyiZhezhi11** [comment]
请问mirai无法连接到服务器这个要怎么办

**Comment by pangzai82008** [comment]
啥也不说咋告诉你？

**Comment by YuanyiZhezhi11** [comment]
> 啥也不说咋告诉你？
> 

![IMG_20230118_205635.jpg](https://user-images.githubusercontent.com/114741580/213383306-62cba51b-16f9-4a19-ad64-19f709ff8258.jpg)额就是这样子，

**Comment by pangzai82008** [comment]
请复制日志文本

**Comment by pangzai82008** [comment]
插件配置问题

**Comment by YuanyiZhezhi11** [comment]
> 插件配置问题
> 

我现在要怎么做

**Comment by pangzai82008** [comment]
你这个是mirai吧

**Comment by pangzai82008** [comment]
这里是miraimc

**Comment by pangzai82008** [comment]
请移步至mirai的issue提问

**Comment by YuanyiZhezhi11** [comment]
好像没找到issue
