### ISSUE TITLE
无法正常登录QQ机器人

### ISSUE THREAD

**Issue by ChuMengCaft** [DreamVoid/MiraiMC#316]
### 问题描述

在登陆机器人时会报错，无法登录

### 复现方法

1.使用Mirai插件
2.输入/mirai login account password

### 服务端类型

Bukkit

### 服务端版本

paper-1.8.8

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
Loading libraries, please wait...
[18:35:08 信息]: 正在启动 Minecraft 服务器版本: 1.8.8
[18:35:08 信息]: 加载配置文件
[18:35:08 信息]: 默认的游戏类型: 生存
[18:35:08 信息]: This server is running CraftBukkit version git-PaperSpigot-445 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[18:35:08 信息]: 调试日志已禁用
[18:35:08 信息]: Spigot Timings: true - Verbose: true - Interval: 5m - Length: 60m
[18:35:08 信息]: Using 4 threads for Netty based IO
[18:35:08 信息]: Server Ping Player Sample Count: 12
[18:35:08 信息]: Data value allowed items:
[18:35:08 信息]: 生成钥匙对
[18:35:08 信息]: 启动 Minecraft 服务器于 *:25565
[18:35:08 信息]: 使用默认通道类型
[18:35:09 信息]: Set PluginClassLoader as parallel capable
[18:35:09 信息]: [MiraiMC] Loading MiraiMC v1.7.1
[18:35:09 警告]: [MiraiMC] Default system encoding may have misread config.yml from plugin jar
[18:35:12 信息]: [MiraiMC] Verifying mirai-core-all-2.13.3.jar
[18:35:13 信息]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.13.3.jar
[18:35:13 警告]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[18:35:13 警告]: The server will make no attempt to authenticate usernames. Beware.
[18:35:13 警告]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[18:35:13 警告]: To change this, set "online-mode" to "true" in the server.properties file.
[18:35:13 信息]: **** Beginning UUID conversion, this may take A LONG time ****
[18:35:13 信息]: 准备世界 "world"
[18:35:13 信息]: -------- 开始设置世界 [world] --------
[18:35:13 信息]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:35:13 信息]: 物品刷新率: 6000
[18:35:13 信息]: 物品合并半径: 2.5
[18:35:13 信息]: Arrow Despawn Rate: 1200
[18:35:13 信息]: 僵尸攻击村民: true
[18:35:13 信息]: View Distance: 10
[18:35:13 信息]: 仙人掌增长调节: 100%
[18:35:13 信息]: 甘蔗生长调节: 100%
[18:35:13 信息]: 西瓜增长调节: 100%
[18:35:13 信息]: 蘑菇生长调节: 100%
[18:35:13 信息]: 南瓜增长调节: 100%
[18:35:13 信息]: 树苗生长调节: 100%
[18:35:13 信息]: 小麦生长调节: 100%
[18:35:13 信息]: 地狱疣生长调节: 100%
[18:35:13 信息]: 实体跟踪范围: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:35:13 信息]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:35:13 信息]: 实体激活范围: An 32 / Mo 32 / Mi 16
[18:35:13 信息]: Nerfing mobs spawned from spawners: false
[18:35:13 信息]: 随机照明更新: false
[18:35:13 信息]: 结构信息保存: true
[18:35:13 信息]: Sending up to 10 chunks per packet
[18:35:13 信息]: 最大TNT爆炸: 100
[18:35:13 信息]: 怪物生成范围: 4
[18:35:13 信息]: Anti X-Ray: true
[18:35:13 信息]: Engine Mode: 1
[18:35:13 信息]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:35:13 信息]: Replace Blocks: [1, 5]
[18:35:13 信息]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[18:35:13 信息]: Max Entity Collisions: 8
[18:35:13 信息]: 经验合并半径: 3.0
[18:35:13 信息]: Chunks to Grow per Tick: 650
[18:35:13 信息]: Clear tick list: false
[18:35:13 信息]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:35:14 信息]: -------- 开始设置世界 [world] --------
[18:35:14 信息]: Water over lava flow speed: 5
[18:35:14 信息]: Max height for cactus growth 3. Max height for reed growth 3
[18:35:14 信息]: Fix TNT cannons: false
[18:35:14 信息]: Keep spawn chunk loaded: true
[18:35:14 信息]: Allow undead horse types to be leashed: false
[18:35:14 信息]: Remove invalid mob spawner tile entities: true
[18:35:14 信息]: Player blocking damage multiplier set to 0.5
[18:35:14 信息]: Squids will spawn between Y: 45.0 and Y: 63.0
[18:35:14 信息]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[18:35:14 信息]: World async lighting: false
[18:35:14 信息]: WorldServer TickNextTick cap set at 10000
[18:35:14 信息]: WorldServer TickNextTickList cap always processes redstone: false
[18:35:14 信息]: -------- 开始设置世界 [world_nether] --------
[18:35:14 信息]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:35:14 信息]: 物品刷新率: 6000
[18:35:14 信息]: 物品合并半径: 2.5
[18:35:14 信息]: Arrow Despawn Rate: 1200
[18:35:14 信息]: 僵尸攻击村民: true
[18:35:14 信息]: View Distance: 10
[18:35:14 信息]: 仙人掌增长调节: 100%
[18:35:14 信息]: 甘蔗生长调节: 100%
[18:35:14 信息]: Melon Growth Modifier: 100%
[18:35:14 信息]: 蘑菇生长调节: 100%
[18:35:14 信息]: 南瓜增长调节: 100%
[18:35:14 信息]: 树苗生长调节: 100%
[18:35:14 信息]: 小麦生长调节: 100%
[18:35:14 信息]: 地狱疣生长调节: 100%
[18:35:14 信息]: 实体跟踪范围: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:35:14 信息]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:35:14 信息]: 实体激活范围: An 32 / Mo 32 / Mi 16
[18:35:14 信息]: Nerfing mobs spawned from spawners: false
[18:35:14 信息]: 随机照明更新: false
[18:35:14 信息]: 结构信息保存: true
[18:35:14 信息]: Sending up to 10 chunks per packet
[18:35:14 信息]: 最大TNT爆炸: 100
[18:35:14 信息]: 怪物生成范围: 4
[18:35:14 信息]: Anti X-Ray: true
[18:35:14 信息]: Engine Mode: 1
[18:35:14 信息]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:35:14 信息]: Replace Blocks: [1, 5]
[18:35:14 信息]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[18:35:14 信息]: Max Entity Collisions: 8
[18:35:14 信息]: 经验合并半径: 3.0
[18:35:14 信息]: Chunks to Grow per Tick: 650
[18:35:14 信息]: Clear tick list: false
[18:35:14 信息]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:35:14 信息]: -------- 开始设置世界 [world_nether] --------
[18:35:14 信息]: Water over lava flow speed: 5
[18:35:14 信息]: Max height for cactus growth 3. Max height for reed growth 3
[18:35:14 信息]: Fix TNT cannons: false
[18:35:14 信息]: Keep spawn chunk loaded: true
[18:35:14 信息]: Allow undead horse types to be leashed: false
[18:35:14 信息]: Remove invalid mob spawner tile entities: true
[18:35:14 信息]: Player blocking damage multiplier set to 0.5
[18:35:14 信息]: Squids will spawn between Y: 45.0 and Y: 63.0
[18:35:14 信息]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[18:35:14 信息]: World async lighting: false
[18:35:14 信息]: WorldServer TickNextTick cap set at 10000
[18:35:14 信息]: WorldServer TickNextTickList cap always processes redstone: false
[18:35:14 信息]: -------- 开始设置世界 [world_the_end] --------
[18:35:14 信息]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:35:14 信息]: 物品刷新率: 6000
[18:35:14 信息]: 物品合并半径: 2.5
[18:35:14 信息]: Arrow Despawn Rate: 1200
[18:35:14 信息]: 僵尸攻击村民: true
[18:35:14 信息]: View Distance: 10
[18:35:14 信息]: 仙人掌增长调节: 100%
[18:35:14 信息]: 甘蔗生长调节: 100%
[18:35:14 信息]: 西瓜增长调节: 100%
[18:35:14 信息]: 蘑菇生长调节: 100%
[18:35:14 信息]: 南瓜增长调节: 100%
[18:35:14 信息]: 树苗生长调节: 100%
[18:35:14 信息]: 小麦生长调节: 100%
[18:35:14 信息]: 地狱疣生长调节: 100%
[18:35:14 信息]: 实体跟踪范围: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:35:14 信息]: Hopper Transfer: 8 Hopper Check: 8 Hopper Amount: 1
[18:35:14 信息]: 实体激活范围: An 32 / Mo 32 / Mi 16
[18:35:14 信息]: Nerfing mobs spawned from spawners: false
[18:35:14 信息]: 随机照明更新: false
[18:35:14 信息]: 结构信息保存: true
[18:35:14 信息]: Sending up to 10 chunks per packet
[18:35:14 信息]: 最大TNT爆炸: 100
[18:35:14 信息]: 怪物生成范围: 4
[18:35:14 信息]: Anti X-Ray: true
[18:35:14 信息]: Engine Mode: 1
[18:35:14 信息]: Hidden Blocks: [14, 15, 16, 21, 48, 49, 54, 56, 73, 74, 82, 129, 130]
[18:35:14 信息]: Replace Blocks: [1, 5]
[18:35:14 信息]: Custom Map Seeds: Village: 10387312 Feature: 14357617
[18:35:14 信息]: Max Entity Collisions: 8
[18:35:14 信息]: 经验合并半径: 3.0
[18:35:14 信息]: Chunks to Grow per Tick: 650
[18:35:14 信息]: Clear tick list: false
[18:35:14 信息]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:35:14 信息]: -------- 开始设置世界 [world_the_end] --------
[18:35:14 信息]: Water over lava flow speed: 5
[18:35:14 信息]: Max height for cactus growth 3. Max height for reed growth 3
[18:35:14 信息]: Fix TNT cannons: false
[18:35:14 信息]: Keep spawn chunk loaded: true
[18:35:14 信息]: Allow undead horse types to be leashed: false
[18:35:14 信息]: Remove invalid mob spawner tile entities: true
[18:35:14 信息]: Player blocking damage multiplier set to 0.5
[18:35:14 信息]: Squids will spawn between Y: 45.0 and Y: 63.0
[18:35:14 信息]: Living Entity Despawn Ranges: Soft: 32 Hard: 128
[18:35:14 信息]: World async lighting: false
[18:35:14 信息]: WorldServer TickNextTick cap set at 10000
[18:35:14 信息]: WorldServer TickNextTickList cap always processes redstone: false
[18:35:14 信息]: Preparing start region for level 0 (Seed: 8292574925429469477)
[18:35:15 信息]: 正在加载地图: 82%
[18:35:15 信息]: Preparing start region for level 1 (Seed: 8292574925429469477)
[18:35:16 信息]: Preparing start region for level 2 (Seed: 8292574925429469477)
[18:35:16 信息]: [MiraiMC] Enabling MiraiMC v1.7.1
[18:35:16 信息]: [MiraiMC] Mirai working dir: default
[18:35:16 信息]: [MiraiMC] Starting Mirai-Events listener.
[18:35:16 信息]: [MiraiMC] Loading auto-login file.
[18:35:16 信息]: [MiraiMC] Registering commands.
[18:35:16 信息]: [MiraiMC] Registering events.
[18:35:16 信息]: [MiraiMC] Initializing SQLite database.
[18:35:16 信息]: [MiraiMC] Initializing bStats metrics.
[18:35:16 警告]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[18:35:16 警告]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[18:35:16 信息]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[18:35:16 信息]: Server permissions file permissions.yml is empty, ignoring it
[18:35:17 信息]: 服务器启动完成 耗时(3.185s)! 如需帮助可输入 "help" 获取帮助 or "?"
[18:35:17 信息]: Timings Reset
[18:35:17 信息]: [MiraiMC] Checking update...
[18:35:17 信息]: [MiraiMC] [AutoLogin] Starting auto login task.
[18:35:17 信息]: [MiraiMC] You are using the latest version!
[18:35:18 信息]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[18:35:18 信息]: [MiraiMC] 1.7.1 已适配 mirai 2.12.0 及以上版本，
[18:35:18 信息]: [MiraiMC] 请及时更新使用。
[18:35:18 信息]: [MiraiMC] =======================================
[18:36:02 信息]: [MiraiMC] 登录新的机器人账号: , 协议: ANDROID_PHONE
[18:36:03 警告]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.impl.netty.NettyChannelException: null
at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler.createConnection$suspendImpl(NettyNetworkHandler.kt:116) ~[mirai-core-all-2.13.3.jar:2.13.3]
at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$createConnection$1.invokeSuspend(NettyNetworkHandler.kt) ~[mirai-core-all-2.13.3.jar:2.13.3]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.13.3.jar:2.13.3]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) [mirai-core-all-2.13.3.jar:2.13.3]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [mirai-core-all-2.13.3.jar:2.13.3]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.13.3.jar:2.13.3]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [mirai-core-all-2.13.3.jar:2.13.3]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [mirai-core-all-2.13.3.jar:2.13.3]
Caused by: java.nio.channels.UnresolvedAddressException
at sun.nio.ch.Net.checkAddress(Net.java:100) ~[?:1.8.0_351]
at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:620) ~[?:1.8.0_351]
at io.netty.channel.socket.nio.NioSocketChannel.doConnect(NioSocketChannel.java:193) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.connect(AbstractNioChannel.java:200) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.DefaultChannelPipeline$HeadContext.connect(DefaultChannelPipeline.java:1029) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.ChannelOutboundHandlerAdapter.connect(ChannelOutboundHandlerAdapter.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.invokeConnect(AbstractChannelHandlerContext.java:496) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:481) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannelHandlerContext.connect(AbstractChannelHandlerContext.java:463) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.DefaultChannelPipeline.connect(DefaultChannelPipeline.java:849) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.AbstractChannel.connect(AbstractChannel.java:199) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.bootstrap.Bootstrap$2.run(Bootstrap.java:165) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) ~[patched_1.8.8.jar:git-PaperSpigot-445]
at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_351]
[18:36:03 警告]: [MiraiMC] Network selector received exception, closing bot. (NettyChannelException(message=null, cause=java.nio.channels.UnresolvedAddressException))
[18:36:03 警告]: [MiraiMC] 登录机器人时出现异常，原因: null
[18:36:03 信息]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

Java版本：Java 8_351
依赖插件：PlaceholderAPI QQConnect
一开始是放在我的服务器上有问题插件比较多我发截取完整日志，然后我单独把Mirai拿出来使用服务端测试，会出现同样的报错

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
请检查服务器网络是否正常，你的服务器无法连接到腾讯服务器
