### ISSUE TITLE
登录时报Error[MiraiMC] Exception in decoding packet.

### ISSUE THREAD

**Issue by imexplorer111** [DreamVoid/MiraiMC#317]
### 问题描述

按照正常登录流程，配置文件等均未动过

### 复现方法

1. /mirai login [QQ] [password]
2. 滑动验证
3. 不安全设备验证
4. 报错

### 服务端类型

Bukkit

### 服务端版本

Purpur version git-Purpur-1428 (MC: 1.17.1)

### MiraiMC 插件版本

MiraiMC version 1.7.1

### 服务端日志

```text
> mirai login [隐藏QQ号] [隐藏密码]
[04:07:18 INFO]: [MiraiMC] 登录新的机器人账号: [隐藏QQ号], 协议: ANDROID_PHONE
[04:07:18 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[04:07:18 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[04:07:18 WARN]: [MiraiMC] 当前登录的QQ（[隐藏QQ号]）需要滑动验证码验证
[04:07:18 WARN]: [MiraiMC] 请打开以下链接进行验证
[04:07:18 WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=[隐藏QQ号]&sid=513792632758316662&cap_cd=Plht2RzpJ1WM69cQbtcWTu1IIrKUq-u3UVCU0ANXCNP7gfKWpDM42Q**&clientype=1&apptype=2
[04:07:18 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify captcha [隐藏QQ号] <ticket>
[04:07:18 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel [隐藏QQ号]
[04:07:18 WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
[04:07:27 INFO]: [保洁大妈]将在 60 秒内开始清理地面垃圾
[04:07:57 INFO]: [保洁大妈]将在 30 秒内开始清理地面垃圾
[04:08:17 INFO]: [保洁大妈]将在 10 秒内开始清理地面垃圾
[04:08:27 INFO]: [保洁大妈]地面掉落物清理完成，清理了 1 个掉落物。
> miraiverify captcha [隐藏QQ号] t03C5hgHG2AV-cDeAA1AfVAVa785GMr4nYFHjj7vuwUOGaUB1sMeJjZNpXVFY_e83J_yrTNOp7VkI8Wf8EiOjhbhv_8lsfvsEHdD8F_Qtcus5bORCoHRq5Wbnw2zFk15E3qyjU2gvaZt5s*
[04:08:29 INFO]: 已将验证码提交到服务器
[04:08:29 WARN]: [MiraiMC] 当前登录的QQ（[隐藏QQ号]）需要设备锁验证
[04:08:29 WARN]: [MiraiMC] 请打开以下链接进行验证
[04:08:29 WARN]: [MiraiMC] https://accounts.qq.com/safe/verify?_wv=2&_wwv=128&envfrom=double-check&uin=[隐藏QQ号]&sig=A5OnqXOATZya5ZDZj2uMdZ55F%2FBjot4VEhzVl36kR39f1gs79aGAWAS7FTRh52GI3CiDBYQ2H9zeNORJ%2BKi%2F2EY%2FVo8mGg16JwwNJyvAygw%3D
[04:08:29 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify unsafedevice [隐藏QQ号]
[04:08:29 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel [隐藏QQ号]
[04:08:29 WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#device-locker
> miraiverify unsafedevice [隐藏QQ号]
[04:09:58 INFO]: 已将验证请求提交到服务器
[04:09:58 ERROR]: [MiraiMC] Exception in decoding packet.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:09:58 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[patched_1.17.1.jar:git-Purpur-1428]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[patched_1.17.1.jar:git-Purpur-1428]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[04:09:58 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
[04:09:58 WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
[04:09:58 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

WIndows Server 2022 21H2
JDK Alibaba-Dragonwell-17.0.4

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by MinecraftXZS** [comment]
同求，报错如下：
09:24:10 [警告] [MiraiMC] 验证完成后，请输入指令 /miraiverify unsafedevice 3076006731
09:24:10 [警告] [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel 3076006731
09:24:10 [警告] [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#device-locker
>miraiverify unsafedevice 3076006731
09:25:06 [信息] 已将验证请求提交到服务器
09:25:06 [严重] [MiraiMC] Exception in decoding packet.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
    at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
    at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
    at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
    at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
    at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
    at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
    at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
    at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
    at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
09:25:06 [警告] [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException
    at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299)
    at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275)
    at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295)
    at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319)
    at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318)
    at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623)
    at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368)
    at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231)
    at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt)
    at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55)
    at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112)
    at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
    at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
    at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
    at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
    at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
    at java.base/java.lang.Thread.run(Thread.java:833)
09:25:06 [警告] [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
09:25:06 [警告] [MiraiMC] 登录机器人时出现异常，原因: null
09:25:06 [信息] [MiraiMC] Bot cancelled: Bot closed
>mirai
09:33:27 [信息] This server is running MiraiMC version 1.7.1 by DreamVoid

**Comment by MinecraftXZS** [comment]
为什么标无效？这是更新了papermc核心之后出现的
