### ISSUE TITLE
登陆机器人显示QQ版本过低

### ISSUE THREAD

**Issue by Zhou-Shilin** [DreamVoid/MiraiMC#318]
### 问题描述

各种协议都试过了，没用
下面是日志：（qq号和密码已删）
`> mirai login qq号 密码
[171月2023 16:02:40.482] [Craft Scheduler Thread - 2393/INFO] [MiraiMC/]: 登录新的机器人账号: qq号, 协议: ANDROID_PHONE
[171月2023 16:02:40.552] [DefaultDispatcher-worker-1/INFO] [MiraiMC/]: ECDH key is invalid, start to fetch ecdh public key from server.
[171月2023 16:02:40.863] [DefaultDispatcher-worker-4/INFO] [MiraiMC/]: Successfully fetched ecdh public key from server.
[171月2023 16:02:41.091] [DefaultDispatcher-worker-4/WARN] [MiraiMC/]: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[mirai-core-all-2.13.2.jar:?] {}
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [mirai-core-all-2.13.2.jar:?] {}
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [mirai-core-all-2.13.2.jar:?] {}
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[mirai-core-all-2.13.2.jar:?] {}
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-all-2.13.2.jar:?] {}
	... 9 more
[171月2023 16:02:41.092] [DefaultDispatcher-worker-4/WARN] [MiraiMC/]: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
[171月2023 16:02:41.093] [Craft Scheduler Thread - 2393/WARN] [MiraiMC/]: 登录机器人时出现异常，原因: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[171月2023 16:02:41.094] [nioEventLoopGroup-3-4/INFO] [MiraiMC/]: Bot cancelled: Bot closed`

### 复现方法

1. 输入指令/mirai login 你的qq号 密码
2. 报错

### 服务端类型

Bukkit

### 服务端版本

Paper-1.18.2

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[171月2023 16:02:40.482] [Craft Scheduler Thread - 2393/INFO] [MiraiMC/]: 登录新的机器人账号: qq号, 协议: ANDROID_PHONE
[171月2023 16:02:40.552] [DefaultDispatcher-worker-1/INFO] [MiraiMC/]: ECDH key is invalid, start to fetch ecdh public key from server.
[171月2023 16:02:40.863] [DefaultDispatcher-worker-4/INFO] [MiraiMC/]: Successfully fetched ecdh public key from server.
[171月2023 16:02:41.091] [DefaultDispatcher-worker-4/WARN] [MiraiMC/]: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[mirai-core-all-2.13.2.jar:?] {}
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [mirai-core-all-2.13.2.jar:?] {}
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) [mirai-core-all-2.13.2.jar:?] {}
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) [mirai-core-all-2.13.2.jar:?] {}
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[mirai-core-all-2.13.2.jar:?] {}
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-all-2.13.2.jar:?] {}
	... 9 more
[171月2023 16:02:41.092] [DefaultDispatcher-worker-4/WARN] [MiraiMC/]: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
[171月2023 16:02:41.093] [Craft Scheduler Thread - 2393/WARN] [MiraiMC/]: 登录机器人时出现异常，原因: Error(bot=Bot(1413892514), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[171月2023 16:02:41.094] [nioEventLoopGroup-3-4/INFO] [MiraiMC/]: Bot cancelled: Bot closed
```

### 额外说明

Window Server 2016 / Java17 OpenJDK Zulu

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by ApliNi** [comment]
https://github.com/DreamVoid/MiraiMC/issues/314

**Comment by Shiroiame-Kusu** [comment]
> #314

https://github.com/DreamVoid/MiraiMC/issues/322#issuecomment-1399120614
