### ISSUE TITLE
无法在服务器登录QQ，提示“当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面”

### ISSUE THREAD

**Issue by Shiroiame-Kusu** [DreamVoid/MiraiMC#319]
### 问题描述

无法登录QQ账号，提示QQ版本过低
[MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)

### 复现方法

1. 安装插件
2. 启动服务端
3. 登录账号

### 服务端类型

Bukkit

### 服务端版本

Mirai-1.19.2/Purpur-1.19.3

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[08:08:30 INFO]: [MiraiMC] 登录新的机器人账号: 3199375003, 协议: ANDROID_PHONE
[08:08:30 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[08:08:30 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[08:08:30 WARN]: [MiraiMC] 当前登录的QQ（3199375003）需要滑动验证码验证
[08:08:30 WARN]: [MiraiMC] 请打开以下链接进行验证
[08:08:30 WARN]: [MiraiMC] https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=3199375003&sid=3012715209569024126&cap_cd=d0oHuWktPChdHxBriLgu_-R_zfrHgyLepgI2S5NsxzmC__uQiu3s3A**&clientype=1&apptype=2
[08:08:30 WARN]: [MiraiMC] 验证完成后，请输入指令 /miraiverify captcha 3199375003 <ticket>
[08:08:30 WARN]: [MiraiMC] 如需取消登录，请输入指令 /miraiverify cancel 3199375003
[08:08:30 WARN]: [MiraiMC] 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
> miraiverify captcha 3199375003 t03kR92SLE004cX9bExAz3IFUHB6jH57GsXenTdZ5Ca9aCtqa7wf_z7x7kEOBVXnJRfrlO6H7_SoOdmaksgJYzdvqSQJ8SR1c7KxLJAcDGe0JJFnASCXYPDGyL-lHM9ppPcAIHhdOB6z7FMPtUHrqvqRl-P7kpqM1v_qBnycBJ24KA*
[08:09:12 INFO]: 已将验证码提交到服务器
[08:09:12 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        ... 9 more
[08:09:12 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
[08:09:12 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[08:09:12 INFO]: [MiraiMC] Bot cancelled: Bot closed
> miraimc
[08:10:09 INFO]: This server is running MiraiMC version 1.7.1 by DreamVoid
[08:10:09 INFO]: For help, type /miraimc help
```

### 额外说明

系统：Windows Server 2022/Debian Bookworm
环境：OpenJDK 17
已清理过plugins/MiraiMC文件夹（包括config和device.json）
一开始报的是[MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(xxxx), code=6, title=登录失败, message=服务连接中，请稍后再试。(0x6), errorInfo=)，第二天清理完config和device.json之后就变成了Error(bot=Bot(3199375003), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
目前是我的服务器和我朋友的服务器（加载了MiraiMC插件）都出现了这个问题

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Shiroiame-Kusu** [comment]
？
