### ISSUE TITLE
purpur 1.19.3无法正常使用miraiMC

### ISSUE THREAD

**Issue by Shizuri23** [DreamVoid/MiraiMC#320]
### 问题描述

如同，可以加载插件，无法登陆qq账号

### 复现方法

/mirai login 账号 密码

### 服务端类型

Bukkit

### 服务端版本

purpur-1.19.3

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[18:29:51 WARN]: [MiraiMC] Plugin MiraiMC v1.7.1 generated an exception while executing task 39210
java.util.NoSuchElementException: Could not find an implementation for service class net.mamoe.mirai.IMirai
        at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:21) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:120) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:132) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:173) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:63) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1895]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.internal.MiraiImpl
                at java.lang.Class.forName0(Native Method) ~[?:?]
                at java.lang.Class.forName(Class.java:375) ~[?:?]
                at net.mamoe.mirai.utils.ServicesKt.findCreateInstance(Services.kt:27) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.utils.ServicesKt.loadService(Services.kt:20) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.Mirai.findMiraiInstance(IMirai.kt:357) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:348) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:39) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:120) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.login(MiraiBot.java:330) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:132) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:173) ~[MiraiMC-Bukkit.jar:?]
                at me.dreamvoid.miraimc.bukkit.commands.MiraiCommand$1.run(MiraiCommand.java:63) ~[MiraiMC-Bukkit.jar:?]
                at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1895]
                at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1895]
                at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
                at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by TuanZiGit** [comment]
我也是这个错误什么Could not find an implementation
