### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录。_2023年1月20

### ISSUE THREAD

**Issue by i-NMB** [DreamVoid/MiraiMC#322]
### 问题描述

登入QQ提示“[MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1037633516), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))”

### 复现方法

1. 

### 服务端类型

Bukkit

### 服务端版本

his server is running Paper version git-Paper-286 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 185fa48) You are 21 version(s) behind

### MiraiMC 插件版本

This server is running MiraiMC version 1.7.1 by DreamVoid

### 服务端日志

```text
完整错误报告：
“[16:16:20 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1037633516), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1037633516), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        ... 9 more
[16:16:20 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1037633516), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
[16:16:20 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(1037633516), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[16:16:20 INFO]: [MiraiMC] Bot cancelled: Bot closed”
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Shiroiame-Kusu** [comment]
用原版Mirai登录QQ，协议选择ANDROID_WATCH
验证码登录成功后将mirai文件夹下的bots文件夹复制到mc服务器目录下的plugins/MiraiMC/MiraiBot/
再在MC后台使用miraimc登录QQ即可

**Comment by Shiroiame-Kusu** [comment]
开发者不愿意解决，那也就只能靠自己了（摆手

**Comment by suxingye** [comment]
> 

非常感谢 解决了
