### ISSUE TITLE
登录QQ机器人账号时提示StackOverflow

### ISSUE THREAD

**Issue by Maplefstar** [DreamVoid/MiraiMC#33]
<strong>问题描述</strong>

在控制台使用指令 /mirai login 登录机器人账号时提示堆栈溢出，并且控制台被警告消息占满。
在控制台使用指令 /mirai list 同样也会报错。
此时使用指令 /reload 或 /plugman reload miraimc 试图重载此插件时，控制台会一直报错，直到重启服务器为止。

<strong>复现方法</strong>

1. 在控制台输入如上所述指令

<strong>版本类型</strong>

* Minecraft 服务端版本：paper-1.17.1
* MiraiMC 插件版本：1.3.2-release

<strong>服务器日志</strong>

```
[15:53:30 INFO]: [MiraiMC] 登录新的机器人账号: 314****388, 协议: ANDROID_PHONE
[15:53:30 INFO]: 
[15:53:30 INFO]: 
[15:53:52 ERROR]: (org.apache.logging.log4j.core.async.AbstractAsyncExceptionHandler:48) null
[15:53:52 WARN]: AsyncLogger error handling event seq=156, value='org.apache.logging.log4j.core.async.RingBufferLogEvent@22319ae6': java.lang.StackOverflowError: java.lang.StackOverflowError
[15:53:52 WARN]:  at com.google.common.collect.RegularImmutableMap.get(RegularImmutableMap.java:123)
[15:53:52 WARN]:  at com.google.common.collect.RegularImmutableMap.get(RegularImmutableMap.java:115)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateStacktrace(StacktraceDeobfuscator.java:117)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:92)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:95)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:95)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:98)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:95)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:98)
[15:53:52 WARN]:  at io.papermc.paper.util.StacktraceDeobfuscator.deobfuscateThrowable(StacktraceDeobfuscator.java:95)
......
```

```
[15:58:54 INFO]: 当前在线的机器人: 
[15:58:54 WARN]: Unexpected exception while parsing console command "mirai list"
>org.bukkit.command.CommandException: Unhandled exception executing command 'mirai' in plugin MiraiMC v1.3.2
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Purpur-1265]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.17.1.jar:git-Purpur-1265]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Purpur-1265]
at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.1.jar:git-Purpur-1265]
at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:531) ~[patched_1.17.1.jar:git-Purpur-1265]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:493) ~[patched_1.17.1.jar:git-Purpur-1265]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1480) ~[patched_1.17.1.jar:git-Purpur-1265]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1270) ~[patched_1.17.1.jar:git-Purpur-1265]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Purpur-1265]
at java.lang.Thread.run(Thread.java:831) [?:?]
>Caused by: kotlin.UninitializedPropertyAccessException: lateinit property nick has not been initialized
at net.mamoe.mirai.internal.QQAndroidBot.getNick(QQAndroidBot.kt:238) ~[?:?]
at me.dreamvoid.miraimc.bukkit.CommandProcessor.onCommand(CommandProcessor.java:115) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Purpur-1265]
... 9 more
```

```
[16:05:35 WARN]: Exception in thread "DefaultDispatcher-worker-7" java.lang.IllegalStateException: zip file closed
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:35 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalStateException: zip file closed
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:35 WARN]: Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: zip file closed
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:35 WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: zip file closed
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:35 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:35 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:35 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:35 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:35 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:35 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:38 WARN]: Exception in thread "DefaultDispatcher-worker-2" java.lang.IllegalStateException: zip file closed
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:38 WARN]: Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: zip file closed
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:38 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalStateException: zip file closed
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:38 WARN]: Exception in thread "DefaultDispatcher-worker-7" java.lang.IllegalStateException: zip file closed
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:38 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:38 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:38 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:38 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:38 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:38 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:41 WARN]: Exception in thread "DefaultDispatcher-worker-7" java.lang.IllegalStateException: zip file closed
[16:05:41 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:41 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:41 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:41 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:41 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:41 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:41 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:41 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:41 WARN]: Exception in thread "DefaultDispatcher-worker-4" java.lang.IllegalStateException: zip file closed
[16:05:41 WARN]:  at java.base/java.util.zip.ZipFile.ensureOpen(ZipFile.java:828)
[16:05:41 WARN]:  at java.base/java.util.zip.ZipFile.getEntry(ZipFile.java:327)
[16:05:41 WARN]:  at java.base/java.util.jar.JarFile.getEntry(JarFile.java:513)
[16:05:41 WARN]:  at java.base/java.util.jar.JarFile.getJarEntry(JarFile.java:468)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158)
[16:05:41 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108)
[16:05:41 WARN]:  at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[16:05:41 WARN]:  at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[16:05:41 WARN]:  at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
[16:05:41 WARN]:  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[16:05:41 WARN]:  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[16:05:41 WARN]: Exception in thread "DefaultDispatcher-worker-3" java.lang.IllegalStateException: zip file closed
......（持续刷屏）
```

**Comment by DreamVoid** [comment]
请确认你使用的PaperMC为正规途径下载的、未被修改的版本。
因为你的PaperMC服务端问题，导致MiraiMC线程出现问题（初步判断为AsyncLogger的问题）
Mirai核心捕获到错误后并不会关闭机器人进程，所以此时机器人实例仍然在运行，但是机器人实例本身没有实质性内容，所以获取机器人信息的时候会报错，也就是第二个报错片段
至于片段3，属于Mirai核心间歇性问题，一般出现在没有正常关闭机器人实例时尝试读写文件，所以是“zip file closed”
