### ISSUE TITLE
发现了一个它与模组之间的冲突

### ISSUE THREAD

**Issue by 1026869549** [DreamVoid/MiraiMC#338]
### 问题描述

本以为是类似 #164  的问题，结果测试后发现，是MiraiMC插件与Forgelin模组的冲突。
Shadowfacts' Forgelin是minecraft低版本的非常多的模组的前置插件。

我只尝试了使用CatServer核心测试，
分别尝试了1.7.1版本与开发版本的MiraiMC，配置文件完全默认。
并且在后续实验时，加上了其他各种各样的插件与模组来测试它是否能够正确加载。

最后发现，只要MiraiMC插件与Forgelin模组同时存在，则MiraiMC不能够正确加载。

### 复现方法

1. 使用最新版本的猫端核心CatServer-dae70adc-universal.jar构建1.12.2版本的服务端
2. 在正确的位置放入1.7.1版本的MiraiMC插件与最新版本的Forgelin-1.8.4.jar模组
3. 运行服务端，得到报错。

### 服务端类型

Bukkit

### 服务端版本

CatServer-1.12.2-dae70adc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)

### MiraiMC 插件版本

MiraiMC version 1.7.1 by DreamVoid

### 服务端日志

```text
[18:36:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLServerTweaker
[18:36:09] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading
[18:36:09] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_191, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_191
[18:36:09] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!
[18:36:09] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!
[18:36:09] [main/WARN] [FML]: The coremod CatCorePlugin (catserver.server.CatCorePlugin) is not signed!
[18:36:09] [main/INFO] [FML]: Searching C:\Users\Administrator\Desktop\ceshi\.\mods for mods
[18:36:09] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in [工具_SC_无中生有前置]Forgelin-1.8.4.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[18:36:09] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[18:36:09] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[18:36:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[18:36:09] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:36:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:36:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:36:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
[18:36:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
[18:36:12] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:36:12] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
[18:36:12] [main/INFO] [LaunchWrapper]: Launching wrapped minecraft {net.minecraft.server.MinecraftServer}
[18:36:16] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting minecraft server version 1.12.2
[18:36:16] [Server thread/INFO] [FML]: MinecraftForge v14.23.5.2860 Initialized
[18:36:16] [Server thread/INFO] [FML]: Starts to replace vanilla recipe ingredients with ore ingredients.
[18:36:16] [Server thread/INFO] [FML]: Invalid recipe found with multiple oredict ingredients in the same ingredient...
[18:36:16] [Server thread/INFO] [FML]: Replaced 1227 ore ingredients
[18:36:16] [Server thread/INFO] [FML]: Searching C:\Users\Administrator\Desktop\ceshi\.\mods for mods
[18:36:17] [Server thread/INFO] [FML]: Forge Mod Loader has identified 5 mods to load
[18:36:17] [Server thread/WARN] [FML]: Missing English translation for FML: assets/fml/lang/en_us.lang
[18:36:17] [Server thread/WARN] [FML]: Missing English translation for forgelin: assets/forgelin/lang/en_us.lang
[18:36:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, forgelin] at CLIENT
[18:36:18] [Server thread/INFO] [FML]: Attempting connection with missing mods [minecraft, mcp, FML, forge, forgelin] at SERVER
[18:36:20] [Server thread/INFO] [FML]: Processing ObjectHolder annotations
[18:36:20] [Server thread/INFO] [FML]: Found 1168 ObjectHolder annotations
[18:36:20] [Server thread/INFO] [FML]: Identifying ItemStackHolder annotations
[18:36:20] [Server thread/INFO] [FML]: Found 0 ItemStackHolder annotations
[18:36:20] [Server thread/INFO] [FML]: Configured a dormant chunk cache size of 0
[18:36:21] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:21] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:21] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:21] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:21] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:21] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:21] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:21] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:21] [Server thread/INFO] [FML]: Injecting itemstacks
[18:36:21] [Server thread/INFO] [FML]: Itemstack injection complete
[18:36:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Loading properties
[18:36:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Default game type: SURVIVAL
[18:36:21] [Server thread/INFO] [Minecraft]: This server is running CatServer version git-CatServer-1.12.2-dae70adc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[18:36:21] [Server thread/INFO] [Minecraft]: Debug logging is enabled
[18:36:21] [Server thread/INFO] []: Server Ping Player Sample Count: 12
[18:36:21] [Server thread/INFO] [Minecraft]: Using 4 threads for Netty based IO
[18:36:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Generating keypair
[18:36:21] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Starting Minecraft server on *:25565
[18:36:21] [Server thread/INFO] [net.minecraft.network.NetworkSystem]: Using default channel type
[18:36:22] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:22] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:22] [Server thread/INFO] [FML]: Injecting itemstacks
[18:36:22] [Server thread/INFO] [FML]: Itemstack injection complete
[18:36:22] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 5 mods
[18:36:22] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "world"
[18:36:22] [Server thread/INFO] [FML]: Injecting existing registry data into this server instance
[18:36:23] [Server thread/INFO] [FML]: Applying holder lookups
[18:36:23] [Server thread/INFO] [FML]: Holder lookups applied
[18:36:24] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Loading MiraiMC v1.7.1
[18:36:26] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Verifying mirai-core-all-2.13.2.jar
[18:36:26] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/2.13.2/mirai-core-all-2.13.2-all.jar
[18:36:30] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.13.2.jar
[18:36:30] [Server thread/INFO] [me.lucko.spark.bukkit.BukkitSparkPlugin]: [spark] Loading spark v1.8.19
[18:36:30] [Server thread/INFO] [Minecraft]: -------- World Settings For [world] --------
[18:36:30] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[18:36:30] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[18:36:30] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[18:36:30] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[18:36:30] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[18:36:30] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:36:30] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:36:30] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:36:30] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:36:30] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[18:36:30] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:36:30] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[18:36:30] [Server thread/INFO] [Minecraft]: View Distance: 10
[18:36:30] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[18:36:30] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:36:30] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[18:36:30] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[18:36:30] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[18:36:31] [Server thread/INFO] [FML]: Loading dimension 0 (world) (net.minecraft.server.dedicated.DedicatedServer@14fac152)
[18:36:31] [Server thread/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 488 advancements
[18:36:31] [Server thread/INFO] [Minecraft]: -------- World Settings For [DIM-1] --------
[18:36:31] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[18:36:31] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[18:36:31] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[18:36:31] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[18:36:31] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:36:31] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:36:31] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:36:31] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:36:31] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[18:36:31] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:36:31] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[18:36:31] [Server thread/INFO] [Minecraft]: View Distance: 10
[18:36:31] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[18:36:31] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:36:31] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[18:36:31] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[18:36:31] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[18:36:31] [Server thread/INFO] [FML]: Loading dimension -1 (DIM-1) (net.minecraft.server.dedicated.DedicatedServer@14fac152)
[18:36:31] [Server thread/INFO] [Minecraft]: -------- World Settings For [DIM1] --------
[18:36:31] [Server thread/INFO] [Minecraft]: Cactus Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Cane Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Melon Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Mushroom Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Pumpkin Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Sapling Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Wheat Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: NetherWart Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Vine Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Cocoa Growth Modifier: 100%
[18:36:31] [Server thread/INFO] [Minecraft]: Mob Spawn Range: 4
[18:36:31] [Server thread/INFO] [Minecraft]: Max TNT Explosions: 100
[18:36:31] [Server thread/INFO] [Minecraft]: Random Lighting Updates: false
[18:36:31] [Server thread/INFO] [Minecraft]: Structure Info Saving: true
[18:36:31] [Server thread/INFO] [Minecraft]: Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
[18:36:31] [Server thread/INFO] [Minecraft]: Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
[18:36:31] [Server thread/INFO] [Minecraft]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[18:36:31] [Server thread/INFO] [Minecraft]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[18:36:31] [Server thread/INFO] [Minecraft]: Arrow Despawn Rate: 1200
[18:36:31] [Server thread/INFO] [Minecraft]: Allow Zombie Pigmen to spawn from portal blocks: true
[18:36:31] [Server thread/INFO] [Minecraft]: Nerfing mobs spawned from spawners: false
[18:36:31] [Server thread/INFO] [Minecraft]: View Distance: 10
[18:36:31] [Server thread/INFO] [Minecraft]: Item Despawn Rate: 6000
[18:36:31] [Server thread/INFO] [Minecraft]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[18:36:31] [Server thread/INFO] [Minecraft]: Experience Merge Radius: 3.0
[18:36:31] [Server thread/INFO] [Minecraft]: Item Merge Radius: 2.5
[18:36:31] [Server thread/INFO] [Minecraft]: Zombie Aggressive Towards Villager: true
[18:36:31] [Server thread/INFO] [FML]: Loading dimension 1 (DIM1) (net.minecraft.server.dedicated.DedicatedServer@14fac152)
[18:36:31] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing start region for level 0
[18:36:32] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 3%
[18:36:34] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Preparing spawn area: 14%
[18:36:34] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Enabling MiraiMC v1.7.1
[18:36:34] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Mirai working dir: default
[18:36:34] [Server thread/INFO] [me.dreamvoid.miraimc.bukkit.BukkitPlugin]: [MiraiMC] Starting Mirai-Events listener.
[18:36:35] [Server thread/ERROR] [Minecraft]: Error occurred while enabling MiraiMC v1.7.1 (Is it up to date?)
java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
	at net.mamoe.mirai.utils.MiraiLoggerFactoryImplementationBridge.<clinit>(MiraiLogger.kt:269) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.__delegate_0$lambda-0(MiraiLogger.kt:88) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.$$delegate_0-wrapper(MiraiLogger.kt) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.internal.event.EventListeners$Companion$logger$2.invoke(EventListeners.kt:31) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.internal.event.EventListeners$Companion$logger$2.invoke(EventListeners.kt:30) ~[mirai-core-all-2.13.2.jar:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[SynchronizedLazyImpl.class:?]
	at net.mamoe.mirai.internal.event.EventListeners$Companion.getLogger(EventListeners.kt:30) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.internal.event.EventListeners$Companion.access$getLogger(EventListeners.kt:29) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.internal.event.EventListeners.addListener$mirai_core(EventListeners.kt:93) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.internal.event.EventChannelImpl.registerListener(EventChannelImpl.kt:95) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.EventChannel.registerListener0$mirai_core_api(EventChannel.kt:696) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.GlobalEventChannel.registerListener(GlobalEventChannel.kt:39) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeInternal(EventChannel.kt:700) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:623) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:617) ~[mirai-core-all-2.13.2.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[mirai-core-all-2.13.2.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:106) ~[MiraiMC-Bukkit.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:149) ~[MiraiMC-Bukkit.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-CatServer-1.12.2-dae70adc]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:328) [JavaPluginLoader.class:git-CatServer-1.12.2-dae70adc]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-CatServer-1.12.2-dae70adc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:438) [CraftServer.class:git-CatServer-1.12.2-dae70adc]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:384) [CraftServer.class:git-CatServer-1.12.2-dae70adc]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:330) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:642) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[18:36:35] [Server thread/INFO] [me.lucko.spark.bukkit.BukkitSparkPlugin]: [spark] Enabling spark v1.8.19
[18:36:36] [Server thread/INFO] [me.lucko.spark.bukkit.BukkitSparkPlugin]: [spark] Using Bukkit scheduler for tick monitoring
[18:36:36] [Server thread/INFO] [Minecraft]: Server permissions file permissions.yml is empty, ignoring it
[18:36:36] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Done (13.885s)! For help, type "help" or "?"
```

### 额外说明

系统环境：Windows 10 企业版 与 Windows server 2016
JAVA版本：jre1.8.0_191 与 jre1.8.0_333

多次实验，得到的报错与结果是一致的——服务端没有崩溃，其他模组与插件正常工作，只有MiraiMC插件无法工作。
实在是看不懂这个报错呜呜呜，于是我目前通过删除这个前置模组，来使MiraiMC插件正常工作。

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
我不知道CatServer是不是屏蔽了插件的Forge检测，但是
https://github.com/DreamVoid/MiraiMC/blob/4d388050ed45c3a923cdead935a4d4e9d372761a/MiraiMC-Bukkit/src/main/java/me/dreamvoid/miraimc/bukkit/BukkitPlugin.java#L139-L144
