### ISSUE TITLE
登录时 出现null报错

### ISSUE THREAD

**Issue by Natsusomekeishi** [DreamVoid/MiraiMC#340]
### 问题描述

登录时出现报错，无法正常登录

### 复现方法

1. 正常使用指令登录

### 服务端类型

Bukkit

### 服务端版本

purpur-1.19.3

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[10:05:48 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[10:05:49 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[10:05:49 ERROR]: [MiraiMC] Exception in decoding packet.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:05:49 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException: null
        at net.mamoe.mirai.internal.utils.crypto.TEA.fail(TEA.kt:299) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption$decrypt(TEA.kt:275) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.doOption(TEA.kt:295) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt(TEA.kt:319) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.utils.crypto.TEA.decrypt$default(TEA.kt:318) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.wtlogin.WtLoginExt.analyzeTlv106(WtLoginExt.kt:623) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.onLoginSuccess(WtLogin.kt:368) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:231) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:491) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.processBody(CommonNetworkHandler.kt:157) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline.access$processBody(CommonNetworkHandler.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1$3$1.invoke(CommonNetworkHandler.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:55) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:112) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$PacketDecodePipeline$1.invokeSuspend(CommonNetworkHandler.kt:126) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[10:05:49 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.utils.crypto.DecryptionFailedException)
[10:05:49 WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
[10:05:49 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Natsusomekeishi** [comment]
请问为什么关闭此议题

**Comment by PoetJamil** [comment]
请问你的问题解决了吗？我也是一样的报错

**Comment by Natsusomekeishi** [comment]
> 请问你的问题解决了吗？我也是一样的报错

并没有ε=(´ο｀*)))唉

**Comment by Wexevou** [comment]
我也这样 也给我关闭了
什么啊

**Comment by cssxsh** [comment]
https://github.com/DreamVoid/MiraiMC/discussions/341#discussioncomment-4892911
