### ISSUE TITLE
升级1.8-pre1出现的235报错

### ISSUE THREAD

**Issue by Natsusomekeishi** [DreamVoid/MiraiMC#348]
### 问题描述

**未升级之前，账号登录出现：**

1. 一直卡在设备锁解锁上，反复提示需要重新解锁，无法正常登录。
2. 产生null错误，输出诸如插件报错的内容。

**升级之后：**

出现的235报错，无法使用短信登录，使用多个QQ号仍出现该问题。

### 复现方法

1. 将最新预览版插件放入文件夹，删除原有插件jar及文件夹。
2. 使用登录指令登录。（协议为 安卓手机/安卓平板）

### 服务端类型

Bukkit

### 服务端版本

purpur-1.19.3

### MiraiMC 插件版本

1.8-pre1

### 服务端日志

```text
**以下为日志：**

`[08:06:30 INFO]: [MiraiMC] 登录新的机器人账号: 2********, 协议: ANDROID_PAD [08:06:31 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server. [08:06:31 INFO]: [MiraiMC] Successfully fetched ecdh public key from server. [08:06:31 WARN]: [MiraiMC] Exception in resumeConnection. net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2351883762), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=) at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?] at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?] at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?] at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?] Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2351883762), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=) at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331) ~[MiraiMC-Bukkit.jar:?] at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?] ... 9 more [08:06:31 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(2351883762), code=235, title=温馨提示, message=当前QQ版本过低， 请升级至最新版本后再登录。点击进入下载页面, errorInfo=)) [08:06:31 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(2*********), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=) [08:06:31 INFO]: [MiraiMC] Bot cancelled: Bot closed`
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Natsusomekeishi** [comment]
猜测，可能是被封控了。
