### ISSUE TITLE
此登录会话需要SMS验证，但当前LoginSolver(me.dreamvoid.miraimc.internal.MiraiLoginSolver@2bb18b7f)不支持。

### ISSUE THREAD

**Issue by xiantiao233** [DreamVoid/MiraiMC#349]
### 问题描述

插件是 MiraiMC-Bukkit和跨版本
输入滑动验证码之后出现错误，，已测试purpur1.19.3核心

### 复现方法

1.直接登入，无更改

### 服务端类型

Bukkit

### 服务端版本

> ver [16:41:05 INFO]: Checking version, please wait... [16:41:09 INFO]: This server is running Paper version git-Paper-307 (MC: 1.19.2) (Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 476ef25) You are running the latest version Previous version: git-Purpur-1907 (MC: 1.19.3)

### MiraiMC 插件版本

[16:41:27 INFO]: This server is running MiraiMC version 1.7.1 by DreamVoid [16:41:27 INFO]: For help, type /miraimc help

### 服务端日志

```text
已将验证码提交到服务器
[16:37:29 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: This login session requires SMS verification, but current LoginSolver(me.dreamvoid.miraimc.internal.MiraiLoginSolver@2bb18b7f) does not support it. Please override `LoginSolver.onSolveDeviceVerification`.
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.UnsupportedSmsLoginException: This login session requires SMS verification, but current LoginSolver(me.dreamvoid.miraimc.internal.MiraiLoginSolver@2bb18b7f) does not support it. Please override `LoginSolver.onSolveDeviceVerification`.
        at net.mamoe.mirai.utils.LoginSolver.onSolveDeviceVerification$suspendImpl(LoginSolver.kt:94) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.utils.LoginSolver.onSolveDeviceVerification(LoginSolver.kt) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:259) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        ... 9 more
[16:37:29 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: This login session requires SMS verification, but current LoginSolver(me.dreamvoid.miraimc.internal.MiraiLoginSolver@2bb18b7f) does not support it. Please override `LoginSolver.onSolveDeviceVerification`.)
[16:37:29 WARN]: [MiraiMC] 登录机器人时出现异常，原因: This login session requires SMS verification, but current LoginSolver(me.dreamvoid.miraimc.internal.MiraiLoginSolver@2bb18b7f) does not support it. Please override `LoginSolver.onSolveDeviceVerification`.
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
1.8-pre1
