### ISSUE TITLE
验证完之后登录机器人失败

### ISSUE THREAD

**Issue by ytv121** [DreamVoid/MiraiMC#352]
### 问题描述

已将验证码提交到服务器
[21:03:35 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1744656022), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit (1).jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit (1).jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(1744656022), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[MiraiMC-Bukkit (1).jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit (1).jar:?]
        ... 9 more
[21:03:35 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(1744656022), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=))
[21:03:35 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(1744656022), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
[21:03:35 INFO]: [MiraiMC] Bot cancelled: Bot closed

### 复现方法

1. /miraiverify captcha 1744656022 <ticket>

### 服务端类型

Bukkit

### 服务端版本

Previous version: git-Paper-323 (MC: 1.19.3)

### MiraiMC 插件版本

 1.7.1

### 服务端日志

```text
e
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by LiteCat0905** [comment]
🤔我印象这东西是你得删了bot的那个设备文件重新登录能概率解决问题🤔

**Comment by LiteCat0905** [comment]
或者用安卓的哪个app登录后生成的配置文件替换论坛有

**Comment by ytv121** [comment]
？？？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DreamVoid/MiraiMC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DreamVoid/MiraiMC] 验证完之后登录机器人失败 (Issue #352)





 
Closed #352 as not planned.

**Comment by ytv121** [comment]
还是不行啊，我这个QQ号是另一个手机注册的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "DreamVoid/MiraiMC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月12日(星期天) 晚上9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [DreamVoid/MiraiMC] 验证完之后登录机器人失败 (Issue #352)





 
🤔我印象这东西是你得删了bot的那个设备文件重新登录能概率解决问题🤔

**Comment by LiteCat0905** [comment]
你看看这个插件论坛吧，有解决方案的。这个是可以登录的！
