### ISSUE TITLE
1.7版本以上与ScriptBlockPlus插件冲突，使后者无法正常使用

### ISSUE THREAD

**Issue by seyink** [DreamVoid/MiraiMC#353]
### 问题描述

1.7版本以上会导致ScriptBlockPlus插件无法正常使用，本人亲测好几遍从100多个插件中筛查出来，确认无误才来反馈，我想这两个插件可以一起使用，因为我现在用1.7版本的MiraiMC已经无法登陆了

### 复现方法

1. 将本插件1.7以上版本与ScriptBlockPlus插件任意版本放入服务器plugins文件夹
2. 启动服务器，启动之后miraimc正常 ScriptBlockPlus插件无法使用，测试1.7及以下版本可以共同使用

### 服务端类型

Bukkit

### 服务端版本

paper-1.18.2

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[05:23:57] [Server thread/INFO]: [ScriptBlockPlus] Enabling ScriptBlockPlus v2.2.2
[05:23:57] [Server thread/ERROR]: Error occurred while enabling ScriptBlockPlus v2.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher.<clinit>(ReflectMatcher.java:39) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:213) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:129) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.enums.server.reflect.ReflectMatcher$Builder.match(ReflectMatcher.java:124) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.utils.NMSHelper.build(NMSHelper.java:70) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.ScriptBlock.onEnable(ScriptBlock.java:84) ~[ScriptBlockPlus v2.2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "io.netty.util.Version.artifactVersion()" because the return value of "java.util.Map.get(Object)" is null
	at com.github.yuttyann.scriptblockplus.utils.collection.IntHashMap.<clinit>(IntHashMap.java:48) ~[ScriptBlockPlus v2.2.2.jar:?]
	... 17 more
[05:23:57] [Server thread/INFO]: [ScriptBlockPlus] Disabling ScriptBlockPlus v2.2.2
[05:23:57] [Server thread/ERROR]: Error occurred while disabling ScriptBlockPlus v2.2.2 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at com.github.yuttyann.scriptblockplus.ScriptBlock.onDisable(ScriptBlock.java:156) ~[ScriptBlockPlus v2.2.2.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-388]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-388]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.validate(CraftScheduler.java:552) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:227) ~[paper-1.18.2.jar:git-Paper-388]
	at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:212) ~[paper-1.18.2.jar:git-Paper-388]
	at com.github.yuttyann.scriptblockplus.Scheduler.run(Scheduler.java:78) ~[ScriptBlockPlus v2.2.2.jar:?]
	at com.github.yuttyann.scriptblockplus.item.action.ScriptViewer.<clinit>(ScriptViewer.java:43) ~[ScriptBlockPlus v2.2.2.jar:?]
	... 14 more
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DreamVoid** [comment]
我就好奇一点，为什么你们都不复制完整的日志？没有完整的日志我能分析出什么问题？
