### ISSUE TITLE
无法登录机器人

### ISSUE THREAD

**Issue by panda-lsy** [DreamVoid/MiraiMC#36]
<strong>问题描述</strong>

输入登录机器人指令时报错

<strong>复现方法</strong>

1. 输入登录指令/mirai login <机器人账号> <密码>时无反应，后台报错

<strong>版本类型</strong>

* Minecraft 服务端版本：Catserver1.12.2-26208f0
* MiraiMC 插件版本：1.3.2

<strong>服务器日志</strong>

```
[14:47:41] [Craft Scheduler Thread - 77/INFO]: [MiraiMC] 登录新的机器人账号: *********, 协议: ANDROID_PHONE
[14:47:41] [Craft Scheduler Thread - 77/WARN]: [MiraiMC] Plugin MiraiMC v1.3.2 generated an exception while executing task 45
>java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.internal.MiraiImpl
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:37) ~[ReflectionMethods.class:git-CatServer-1.12.2-26208f0]
at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:17) ~[ReflectionMethods.class:git-CatServer-1.12.2-26208f0]
at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347) ~[?:?]
at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43) ~[?:?]
at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:161) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
at me.dreamvoid.miraimc.bukkit.CommandProcessor$1.run(CommandProcessor.java:59) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-26208f0]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-26208f0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_301]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_301]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
```

**Comment by panda-lsy** [comment]
**将MiraiMC更换到Dev-3后**
`[15:27:11] [Craft Scheduler Thread - 9/WARN]: [MiraiMC] Plugin MiraiMC vdev-3 generated an exception while executing task 34
>java.lang.NoSuchMethodError: kotlin.jvm.internal.MutablePropertyReference1Impl.<init>(Ljava/lang/Class;Ljava/lang/String;Ljava/lang/String;I)V
at io.ktor.client.HttpClientConfig.<clinit>(HttpClientConfig.kt) ~[?:?]
at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:41) ~[?:?]
at net.mamoe.mirai.internal.MiraiImpl.<init>(MiraiImpl.kt:136) ~[?:?]
at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt:70) ~[?:?]
at net.mamoe.mirai.internal.MiraiImpl$INSTANCE.<init>(MiraiImpl.kt) ~[?:?]
at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt) ~[?:?]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_301]
at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_301]
at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:37) ~[ReflectionMethods.class:git-CatServer-1.12.2-26208f0]
at catserver.server.remapper.target.ReflectionMethods.forName(ReflectionMethods.java:17) ~[ReflectionMethods.class:git-CatServer-1.12.2-26208f0]
at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:347) ~[?:?]
at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43) ~[?:?]
at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:156) ~[?:?]
at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:90) ~[?:?]
at me.dreamvoid.miraimc.bukkit.CommandProcessor$1.run(CommandProcessor.java:59) ~[?:?]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-26208f0]
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-26208f0]
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_301]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_301]
at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]`

**Comment by DreamVoid** [comment]
Catserver自身问题，请尝试更换为Mohist
另请检查插件名称是否变成了`(Taboo) MiraiMC.jar`

**Comment by panda-lsy** [comment]
OK
