### ISSUE TITLE
title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)

### ISSUE THREAD

**Issue by qeqwzcx** [DreamVoid/MiraiMC#361]
### 问题描述

如题，这个登入失败的提示语我没有在任何地方找到解决办法，我看他们的提示是版本低，升级最新版，但是我的是登入失败，升级最新版重试。
1.我在新安卓手机上试了登入我帐号，并没有出现风控等问题
2.我使用mcl登入QQ号尝试，发现出现一样的提示。
3.我是BC端，BC核心为waterfall，子服核心为paper

### 复现方法

1. 只要输入mirai login QQ号 密码 ，完成滑块验证以后就出现。

### 服务端类型

BungeeCord

### 服务端版本

waterfall-1.19-510

### MiraiMC 插件版本

最新版1.7.1

### 服务端日志

```text
> mirai login 280****25 caonima.
[17:12:30 INFO] [MiraiMC]: 登录新的机器人账号: 280****325, 协议: ANDROID_PHONE
[17:12:30 INFO] [MiraiMC]: ECDH key is invalid, start to fetch ecdh public key from server.
[17:12:30 INFO] [MiraiMC]: Successfully fetched ecdh public key from server.
[17:12:30 INFO] [MiraiMC]: Calculating type 2 PoW, it can take some time....
[17:12:30 INFO] [MiraiMC]: Got PoW result, cost: 23 ms
[17:12:30 WARN] [MiraiMC]: 当前登录的QQ（280*****25）需要滑动验证码验证
[17:12:30 WARN] [MiraiMC]: 请打开以下链接进行验证
[17:12:30 WARN] [MiraiMC]: https://ssl.captcha.qq.com/template/wireless_mqq_captcha.html?style=simple&aid=16&uin=2805868325&sid=7498873176616810878&cap_cd=-HtNb__567CcqT3fHpn186DlX27r9teMBypttigKY9bpPhkCS6vm0w**&clientype=1&apptype=2
[17:12:30 WARN] [MiraiMC]: 验证完成后，请输入指令 /miraiverify captcha 28****325 <ticket>
[17:12:30 WARN] [MiraiMC]: 如需取消登录，请输入指令 /miraiverify cancel 280****25
[17:12:30 WARN] [MiraiMC]: 如需帮助，请参阅: https://docs.miraimc.dreamvoid.me/troubleshoot/verify-guide#slide-captcha
> miraiverify captcha 28*****25 t03g6J9OYxGRKbxIA8-36EPGLGFPe0d4qCz-I6OO4EbObSRpDxnlJsSC8YgmVMc1OAD28QqYBp1sk-Iysm75O2zOWwZ_b1HT50UJvYje4IxvUC6M8MbEemZ0GbKZDIpySnk42I3WJCW-h4*
[17:13:04 INFO]: 已将验证码提交到服务器
[17:13:04 WARN] [MiraiMC]: Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(28*****5), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[?:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(280****325), code=45, title=禁止登录, message= 登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[?:?]
        ... 9 more
[17:13:04 WARN] [MiraiMC]: Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(280*****5), code=45, title=禁止登录, message=登录失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=))
[17:13:04 WARN] [MiraiMC]: 登录机器人时出现异常，原因: Error(bot=Bot(2*****25), code=45, title=禁止登录, message=登录 失败，建议升级最新版本后重试，或通过问题反馈与我们联系。, errorInfo=)
[17:13:04 INFO] [MiraiMC]: Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by qeqwzcx** [comment]
对，我还试了1.8测试版，也是一样，使用的插件是bungeecord版

**Comment by qeqwzcx** [comment]
?

**Comment by DreamVoid** [comment]
https://github.com/DreamVoid/MiraiMC/issues/353#issuecomment-1427299902

<h1>？</h1>
