### ISSUE TITLE
当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by ApliNi** [DreamVoid/MiraiMC#378]
### 问题描述

登录账号时出现 `当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面`

### 复现方法

1. 在已有插件数据时
2. 输入指令 `mirai login QQ号 密码`

或

1. 使用 `/mirai login <账号> <密码>` 登录账户
2. 在浏览器完成验证码, 从开发者工具中获取 ticket
4. 输入 `miraiverify captcha <账号> <ticket>`

或

1. 输入指令 `mirai login QQ号 密码 MACOS`
2. 在浏览器完成验证码, 从开发者工具中获取 ticket
3. 输入 `miraiverify captcha <账号> <ticket>`

### 服务端类型

Bukkit

### 服务端版本

purpur-1.19.3-1912

### MiraiMC 插件版本

This server is running MiraiMC version 1.8-pre1 by DreamVoid

### 服务端日志

```text
OpenJDK 64-Bit Server VM warning: UseAVX=3 is not supported on this CPU, setting it to UseAVX=2
WARNING: Using incubator modules: jdk.incubator.vector
Starting org.bukkit.craftbukkit.Main
System Info: Java 19 (OpenJDK 64-Bit Server VM 19.0.1+10) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[10:57:04 INFO]: Building unoptimized datafixer
[10:57:05 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[10:57:07 INFO]: Loaded 7 recipes
[10:57:07 INFO]: Starting minecraft server version 1.19.3
[10:57:07 INFO]: Loading properties
[10:57:07 INFO]: This server is running Purpur version git-Purpur-1912 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 0090323 on HEAD)
[10:57:08 INFO]: Server Ping Player Sample Count: 0
[10:57:08 INFO]: Using 4 threads for Netty based IO
[10:57:08 INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[10:57:08 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[10:57:08 INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[10:57:08 INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[10:57:08 INFO]: Default game type: SURVIVAL
[10:57:08 INFO]: Generating keypair
[10:57:08 INFO]: Starting Minecraft server on *:25565
[10:57:08 INFO]: Using default channel type
[10:57:08 INFO]: Paper: Using Java compression from Velocity.
[10:57:08 INFO]: Paper: Using Java cipher from Velocity.
[10:57:15 ERROR]: Purpur: Failed to download and install spark plugin
[10:57:15 WARN]: java.net.SocketTimeoutException: Connect timed out
[10:57:15 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:539)
[10:57:15 WARN]:        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:585)
[10:57:15 WARN]:        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
[10:57:15 WARN]:        at java.base/java.net.Socket.connect(Socket.java:666)
[10:57:15 WARN]:        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304)
[10:57:15 WARN]:        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:178)
[10:57:15 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:531)
[10:57:15 WARN]:        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:636)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:378)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1241)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1127)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1661)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1585)
[10:57:15 WARN]:        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:224)
[10:57:15 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:465)
[10:57:15 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:309)
[10:57:15 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
[10:57:15 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[10:57:15 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1589)
[10:57:15 INFO]: [MiraiMC] Preparing MiraiMC start-up.
[10:57:15 INFO]: [MiraiMC] Start-up tasks finished.
[10:57:15 INFO]: [MiraiMC] Loading MiraiMC v1.8-pre1
[10:57:15 INFO]: [MiraiMC] Preparing MiraiMC pre-load.
[10:57:15 INFO]: [MiraiMC] Loading config.
[10:57:16 INFO]: [MiraiMC] Mirai working dir: default
[10:57:16 INFO]: [MiraiMC] Selected mirai core version: stable
[10:57:17 INFO]: [MiraiMC] Verifying mirai-core-all-2.14.0.jar
[10:57:17 INFO]: [MiraiMC] Downloading https://repo.huaweicloud.com/repository/maven/net/mamoe/mirai-core-all/2.14.0/mirai-core-all-2.14.0-all.jar
[10:57:18 INFO]: [MiraiMC] Loading library plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.14.0.jar
[10:57:18 INFO]: [MiraiMC] Pre-load tasks finished.
[10:57:18 INFO]: [MiraiMC] Loading Chat2QQ v1.8.0
[10:57:18 WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[10:57:18 WARN]: The server will make no attempt to authenticate usernames. Beware.
[10:57:18 WARN]: While this makes the game possible to play without internet access, it also opens up the ability for hackers to connect with any username they choose.
[10:57:18 WARN]: You will not be offered any support as long as the server allows offline-mode players to join.
[10:57:18 WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[10:57:18 INFO]: Preparing level "world"
[10:57:19 INFO]: [MiraiMC] Enabling MiraiMC v1.8-pre1
[10:57:19 INFO]: [MiraiMC] Preparing MiraiMC post-load.
[10:57:19 INFO]: [MiraiMC] Initializing SQLite database.
[10:57:19 INFO]: [MiraiMC] Starting Mirai-Event listener.
[10:57:19 INFO]: [MiraiMC] Starting Auto-Login bot.
[10:57:19 WARN]: [MiraiMC] 确保您正在使用开源的 MiraiMC 插件，未知来源的插件可能会盗取您的账号！
[10:57:19 WARN]: [MiraiMC] 请始终从 GitHub 或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[10:57:19 INFO]: [MiraiMC] Some initialization tasks will continue to run afterwards.
[10:57:19 INFO]: [MiraiMC] Post-load tasks finished. Welcome to use MiraiMC!
[10:57:19 INFO]: [MiraiMC] Registering events.
[10:57:19 INFO]: [MiraiMC] Initializing bStats metrics.
[10:57:19 INFO]: [MiraiMC] Enabling Chat2QQ v1.8.0
[10:57:19 INFO]: JMX monitoring enabled
[10:57:19 INFO]: Running delayed init tasks
[10:57:19 INFO]: Done (11.958s)! For help, type "help"
[10:57:19 INFO]: [MiraiMC] Checking update...
[10:57:19 INFO]: [MiraiMC-AutoLogin] Starting auto login task.
[10:57:19 INFO]: [MiraiMC] 你使用的是最新版本的 MiraiMC！
[10:57:21 INFO]: [MiraiMC] ========== [ MiraiMC 公告版 ] ==========
[10:57:21 INFO]: [MiraiMC] 1.8-pre1 已发布，支持短信验证码登录，并修复了多个 Bug。
[10:57:21 INFO]: [MiraiMC] 如有需要可更新使用。
[10:57:21 INFO]: [MiraiMC] =======================================
> mirai login QQ号 密码
[10:57:26 INFO]: [MiraiMC] 登录新的机器人账号: QQ号, 协议: ANDROID_PHONE
[10:57:26 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[10:57:27 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[10:57:27 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(QQ号), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载 页面, errorInfo=)
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(QQ号), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:331) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        ... 9 more
[10:57:27 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(QQ号), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=))
[10:57:27 WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(QQ号), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
[10:57:27 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

我尝试过删除插件文件夹以及 https://github.com/DreamVoid/MiraiMC/issues/264 中的方法 `临时解决方案，先使用mirai console loader登录一下机器人账号，然后把device.json复制到插件目录` 无法解决.

mirai console loader 可以正常登录, 将文件复制到 miraiMC 后依然出现此问题.

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by Tanloon** [comment]
+1,期待解决
但估计是腾讯风控？我好几个号原本可以，重启服务器重新登录一下就235了

**Comment by DICEALPHAHU** [comment]
+1 按照[之前的方法](https://github.com/DreamVoid/MiraiMC/issues/17)无法解决这个问题，应该是最近qq更新后产生了这样的报错235，我那天发现登不上去提示报错了

**Comment by DICEALPHAHU** [comment]
> 我的问题解决了, 用手机QQ登录几天机器人账号再用MiraiMC登录, 会提示进行短信验证
我刚刚换了1.8-pro1的版本，现在出现了237错误（网络不稳定）:(
