### ISSUE TITLE
code235,已经试过mcl的fix，可以登录，但miraimc不行

### ISSUE THREAD

**Issue by HaiXi2912** [DreamVoid/MiraiMC#381]
### 问题描述

code235,已经试过mcl的fix，可以登录，但miraimc不行
已经把json放进miraimc，不行
并且这报错跟以前不一样，这次比较长

### 复现方法

1. 正常登录无果
2. 使用mcl的fix登录成功后放入miraimc中，依旧无效

### 服务端类型

Bukkit

### 服务端版本

git-Purpur-1858 (MC: 1.19.2)

### MiraiMC 插件版本

version 1.8-pre1

### 服务端日志

```text
[12:46:53 INFO]: [MiraiMC] 登录新的机器人账号: 2917364996, 协议: MACOS
[12:46:53 INFO]: [MiraiMC] ECDH key is invalid, start to fetch ecdh public key from server.
[12:46:53 INFO]: [MiraiMC] Successfully fetched ecdh public key from server.
[12:46:53 WARN]: [MiraiMC] Failed with auth method: Password@582039063
net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2917364996), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
[12:46:53 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException: null
[12:46:53 INFO]: [MiraiMC] ECDH key is valid.
[12:46:53 WARN]: [MiraiMC] Failed with auth method: Error[net.mamoe.mirai.internal.network.auth.ProducerFailureException]@2039434264
net.mamoe.mirai.internal.network.auth.ProducerFailureException: null
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2917364996), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2917364996), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        ... 5 more
[12:46:53 WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.auth.ProducerFailureException: null
        at net.mamoe.mirai.internal.network.auth.CoroutineOnDemandValueScope.receiveOrNull(CoroutineOnDemandValueScope.kt:152) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.auth.AuthControl.acquireAuth(AuthControl.kt:98) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:219) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:247) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
        Suppressed: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2917364996), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450) ~[MiraiMC-Bukkit.jar:?]
                at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
                at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
                at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
        Suppressed: net.mamoe.mirai.internal.network.handler.selector.SelectorRequireReconnectException
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(2917364996), code=235, title=温馨提示, message=当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面, errorInfo=)
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:450) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
        ... 5 more
[12:46:53 WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.auth.ProducerFailureException)
[12:46:53 WARN]: [MiraiMC] 登录机器人时出现异常，原因: null
[12:46:53 INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 额外说明

JDK 19

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和[Issue列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。

**Comment by DICEALPHAHU** [comment]
建议将配置文件中的mirai-core-version改成 latest，我是这么解决的

**Comment by HaiXi2912** [comment]
我更改了登录模式，又可以了，很迷，希望不要再出问题了，一周要修好几次机器人
