### ISSUE TITLE
Will Miraimc work with Folia?

### ISSUE THREAD

**Issue by MineSunshineone** [DreamVoid/MiraiMC#384]
### 功能描述

Considering paper's new project Folia, and the popularity of the Miriamc project, I thought it would be great to make an adaptation for Folia!

### 使用方法

1. Add Folia-Supported

**Comment by DreamVoid** [comment]
MiraiMC don't touch nms api, and it can work well.

**Comment by MineSunshineone** [comment]
[22:10:58 ERROR]: Error occurred while enabling MiraiMC v1.8-pre1 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:260) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskLaterAsynchronously(CraftScheduler.java:192) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskAsynchronously(CraftScheduler.java:161) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at me.dreamvoid.miraimc.bukkit.MiraiAutoLogin.doStartUpAutoLogin(MiraiAutoLogin.java:84) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:103) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:59) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[folia-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[folia-1.19.4.jar:git-Folia-"31c1621"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:10:58 INFO]: [MiraiMC] Disabling MiraiMC v1.8-pre1
[22:10:58 INFO]: [MiraiMC] Preparing MiraiMC unload.
[22:10:58 INFO]: [MiraiMC] Closing all bots
[22:10:58 INFO]: [MiraiMC] Stopping bot event listener.
[22:10:58 INFO]: [MiraiMC] Closing SQLite database.
[22:10:58 INFO]: [MiraiMC] Unload tasks finished. Thanks for use MiraiMC!

**Comment by DreamVoid** [comment]
Multi thread issue, report to papermc instead of here.

**Comment by MineSunshineone** [comment]
[11:57:20 ERROR]: [Whitelist4QQ] Failed to register events for class me.dreamvoid.whitelist4qq.bukkit.listener.BotEvent because me/dreamvoid/miraimc/bukkit/event/message/passive/MiraiGroupMessageEvent does not exist.
[11:57:20 ERROR]: Error occurred while enabling Whitelist4QQ v1.3 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:260) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:247) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at me.dreamvoid.whitelist4qq.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:61) ~[Whitelist4QQ.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:279) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:192) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[11:57:20 INFO]: [Whitelist4QQ] Disabling Whitelist4QQ v1.3
[11:57:20 ERROR]: Error occurred (in the plugin loader) while disabling Whitelist4QQ v1.3 (Is it up to date?)
java.lang.UnsupportedOperationException: null
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.handle(CraftScheduler.java:536) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.cancelTasks(CraftScheduler.java:349) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at me.dreamvoid.whitelist4qq.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:77) ~[Whitelist4QQ.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:227) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:196) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[kaiiju-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:631) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:542) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:681) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:465) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:318) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:348) ~[kaiiju-1.19.4.jar:git-Kaiiju-"02ef39a"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by MineSunshineone** [comment]
sorry for bother you, but i dont know how to deal with it. i also thought Miraimc is an awsome plugins

**Comment by x1aoren** [comment]
[MiraiMC-Folia.zip](https://github.com/user-attachments/files/16356584/MiraiMC-Folia.zip)
修改版，仅供私用，侵权即删
@MineSunshineone 
@DreamVoid

**Comment by DreamVoid** [comment]
> [MiraiMC-Folia.zip](https://github.com/user-attachments/files/16356584/MiraiMC-Folia.zip)
> 修改版，仅供私用，侵权即删
> @MineSunshineone 
> @DreamVoid 

光明正大了是吧😅
