### ISSUE TITLE
服务器启动时插件启动失败

### ISSUE THREAD

**Issue by NoMathExpectation** [DreamVoid/MiraiMC#39]
<strong>问题描述</strong>

如标题，我实在不知道怎么回事。

<strong>复现方法</strong>

1. 

<strong>版本类型</strong>

* Minecraft 服务端版本：paper 1.17.1
* MiraiMC 插件版本：1.4 pre1

<strong>服务器日志</strong>

(节选)
```
[22:05:41 INFO]: Enabling MiraiMC v1.4-pre1
[22:05:41 INFO]: Mirai working dir: default
[22:05:41 INFO]: Starting Mirai-Events listener.
[22:05:42 ERROR]: Error occurred while enabling MiraiMC v1.4-pre1 (Is it up to date?)
java.lang.LinkageError: loader constraint violation in interface itable initialization for class net.mamoe.mirai.internal.event.Handler: when selecting method 'java.lang.Object kotlin.coroutines.CoroutineContext.fold(java.lang.Object, kotlin.jvm.functions.Function2)' the class loader 'app' for super interface kotlin.coroutines.CoroutineContext, and the class loader 'MiraiMC-release.jar' @1f38cf4 of the selected method's class, net.mamoe.mirai.internal.event.Handler have different Class objects for the type kotlin.jvm.functions.Function2 used in the signature (kotlin.coroutines.CoroutineContext is in unnamed module of loader 'app'; net.mamoe.mirai.internal.event.Handler is in unnamed module of loader 'MiraiMC-release.jar' @1f38cf4, parent loader 'app')
	at net.mamoe.mirai.event.EventChannel.createListener(EventChannel.kt:606) ~[MiraiMC-release.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt:511) ~[MiraiMC-release.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways$default(EventChannel.kt:503) ~[MiraiMC-release.jar:?]
	at net.mamoe.mirai.event.EventChannel.subscribeAlways(EventChannel.kt) ~[MiraiMC-release.jar:?]
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.startListenEvent(MiraiEvent.java:81) ~[MiraiMC-release.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onEnable(BukkitPlugin.java:42) ~[MiraiMC-release.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]
	at java.lang.Thread.run(Thread.java:831) [?:?]
[22:05:42 INFO]: Disabling MiraiMC v1.4-pre1
[22:05:42 INFO]: Stopping bot event listener.
[22:05:42 ERROR]: Error occurred while disabling MiraiMC v1.4-pre1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.mamoe.mirai.event.Listener.complete()" because "this.BotOnlineListener" is null
	at me.dreamvoid.miraimc.bukkit.MiraiEvent.stopListenEvent(MiraiEvent.java:160) ~[MiraiMC-release.jar:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onDisable(BukkitPlugin.java:94) ~[MiraiMC-release.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529) ~[patched_1.17.1.jar:git-Paper-172]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1126) ~[patched_1.17.1.jar:git-Paper-172]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-172]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by DreamVoid** [comment]
```System Info: Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[23:13:55 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[23:13:55 INFO]: Reloading ResourceManager: Default, bukkit
[23:13:56 INFO]: Loaded 7 recipes
[23:13:57 INFO]: Starting minecraft server version 1.17.1
[23:13:57 INFO]: Loading properties
[23:13:57 INFO]: This server is running Purpur version git-Purpur-1261 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 325d6c3 on HEAD)
[23:13:58 INFO]: Debug logging is disabled
[23:13:58 INFO]: Server Ping Player Sample Count: 12
[23:13:58 INFO]: Using 4 threads for Netty based IO
[23:13:58 INFO]: Default game type: SURVIVAL
[23:13:58 INFO]: Generating keypair
[23:13:58 INFO]: Starting Minecraft server on *:25565
[23:13:58 INFO]: Using default channel type
[23:13:59 INFO]: [MiraiMC] Loading MiraiMC v1.4-pre1
[23:13:59 INFO]: Server permissions file permissions.yml is empty, ignoring it
[23:13:59 INFO]: Preparing level "world"
[23:13:59 INFO]: Preparing start region for dimension minecraft:overworld
[23:14:00 INFO]: Time elapsed: 259 ms
[23:14:00 INFO]: Preparing start region for dimension minecraft:the_nether
[23:14:00 INFO]: Time elapsed: 68 ms
[23:14:00 INFO]: Preparing start region for dimension minecraft:the_end
[23:14:00 INFO]: Time elapsed: 64 ms
[23:14:00 INFO]: [MiraiMC] Enabling MiraiMC v1.4-pre1
[23:14:00 INFO]: [MiraiMC] Mirai working dir: default
[23:14:00 INFO]: [MiraiMC] Starting Mirai-Events listener.
[23:14:00 INFO]: [MiraiMC] Loading auto-login file.
[23:14:00 INFO]: [MiraiMC] Registering commands.
[23:14:00 INFO]: [MiraiMC] Registering events.
[23:14:00 INFO]: [MiraiMC] Initializing SQLite database.
[23:14:00 INFO]: [MiraiMC] Initializing bStats metrics.
[23:14:00 WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[23:14:00 WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[23:14:00 INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[23:14:00 INFO]: Running delayed init tasks
[23:14:00 INFO]: Done (2.653s)! For help, type "help"
[23:14:00 INFO]: Timings Reset
[23:14:00 INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
>
```
本地测试无问题，这给我整不会了

---

请尝试先移除所有插件，然后逐个加入并重新启动服务器，直到复现此问题，并将相应插件名称回复给我。

**Comment by NoMathExpectation** [comment]
找到了，是Trmenu，这家伙内置了TabooLib

不过没关系了，更新了Trmenu后这个bug就没了
