### ISSUE TITLE
Waterfall无法加载插件

### ISSUE THREAD

**Issue by ZeroJoKCN** [DreamVoid/MiraiMC#432]
### 问题描述

将插件放入Waterfall后无法正常加载

### 复现方法

1. 将MiraiMC放入Waterfall
2. 启动服务器

### 服务端类型

BungeeCord

### 服务端版本

Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536

### MiraiMC 插件版本

MiraiMC version dev-234

### 服务端日志

```text
[15:22:10] [main/WARN]: Exception encountered when loading plugin: MiraiMC
java.lang.NoClassDefFoundError: net/mamoe/mirai/event/events/SignEvent
	at me.dreamvoid.miraimc.bungee.MiraiEvent.startListenEvent(MiraiEvent.java:177) ~[?:?]
	at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:98) ~[?:?]
	at me.dreamvoid.miraimc.bungee.BungeePlugin.onEnable(BungeePlugin.java:51) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.events.SignEvent
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 7 more
```

### 额外说明

启动参数：java -jar waterfall.jar
系统：Windows Server 2022

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [X] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
警告一次，再次滥用issue功能将会被加入黑名单。
