### ISSUE TITLE
当前网络不稳定 登录失败

### ISSUE THREAD

**Issue by xuechenyi1** [DreamVoid/MiraiMC#435]
### 问题描述

登录时提示
登录环境不稳定 推荐使用常用设备或验证码登录

### 复现方法

```java
在登录时
```

### 服务端类型

Bukkit

### 服务端版本

Paper-1.20.1(git-96)

### MiraiMC 插件版本

1.7.1

### 服务端日志

```text
[19:59:11] [DefaultDispatcher-worker-3/WARN]: [MiraiMC] Exception in resumeConnection.
net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3248942565), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.handler.CommonNetworkHandler$StateConnecting$startState$2.invokeSuspend(CommonNetworkHandler.kt:248) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) ~[MiraiMC-Bukkit.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677) ~[MiraiMC-Bukkit.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664) ~[MiraiMC-Bukkit.jar:?]
Caused by: net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(3248942565), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:311) ~[MiraiMC-Bukkit.jar:?]
	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[MiraiMC-Bukkit.jar:?]
	... 9 more
[19:59:11] [DefaultDispatcher-worker-3/WARN]: [MiraiMC] Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(3248942565), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=))
[19:59:11] [Craft Scheduler Thread - 16 - MiraiMC/WARN]: [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(3248942565), code=237, title=安全提醒, message=当前网络不稳定，登录失败。推荐使用常用设备或通过手机号登录。, errorInfo=)
[19:59:11] [DefaultDispatcher-worker-3/INFO]: [MiraiMC] Bot cancelled: Bot closed
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [X] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
警告一次，再次滥用 issue 将会被加入黑名单
