### ISSUE TITLE
插件加载失败

### ISSUE THREAD

**Issue by CoolMagic233** [DreamVoid/MiraiMC#436]
### 问题描述

插件在加载时报错，导致启动完成服务端后无法使用/mirai命令

### 复现方法

1. 下载插件
2. 启动服务端

### 服务端类型

Nukkit

### 服务端版本

21:18:32 [INFO ] This server is running Nukkit git-9a84110 「」 implementing API version 1.0.14 for Minecraft: BE v1.20.10 (protocol version 594)

### MiraiMC 插件版本

v1.8-rc1

### 服务端日志

```text
21:11:36 [INFO ] Loading nukkit.yml ...
21:11:36 [INFO ] Loading server.properties ...
21:11:36 [INFO ] Selected English (eng) as the base language
21:11:36 [INFO ] Starting Minecraft: BE server version v1.20.10
21:11:36 [INFO ] Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
21:11:36 [WARN ] Encryption is not enabled. For better security, it's recommended to enable it (network.encryption=true in nukkit.yml) if you don't use a proxy software.
21:11:36 [INFO ] Opening server on 127.0.0.1:19137
21:11:36 [INFO ] This server is running Nukkit version git-9a84110 "" (API 1.0.14)
21:11:36 [INFO ] Nukkit is distributed under the GPL License
21:11:36 [INFO ] Loading runtime items...
21:11:37 [INFO ] Loading recipes...
21:11:37 [INFO ] Loaded 1509 recipes.
21:11:37 [INFO ] Successfully loaded 0 resource packs
21:11:38 [WARN ] Unknown channel option 'IP_DONTFRAG' for channel '[id: 0x4ce88741]'
21:11:38 [INFO ] Loading CParkour v0.1
21:11:38 [INFO ] Loading DataManager v0.2
21:11:38 [INFO ] Loading EconomyAPI v2.0.2
21:11:38 [INFO ] Loading HiddenCommands v1.0
21:11:38 [INFO ] Loading JoinCommand v1.0.0-SNAPSHOT
21:11:38 [INFO ] Loading MiraiMC v1.8-rc1
21:11:38 [FATAL] Could not load plugin
java.lang.NullPointerException: Cannot invoke "cn.nukkit.plugin.PluginLogger.info(String)" because "this.logger" is null
        at me.dreamvoid.miraimc.nukkit.NukkitLogger.info(NukkitLogger.java:57) ~[?:?]
        at me.dreamvoid.miraimc.MiraiMCPlugin.startUp(MiraiMCPlugin.java:34) ~[?:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.<init>(NukkitPlugin.java:30) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128) ~[?:?]
        at jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347) ~[?:?]
        at java.lang.Class.newInstance(Class.java:645) ~[?:?]
        at cn.nukkit.plugin.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:56) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugin(PluginManager.java:95) [server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:269) [server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:132) [server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:124) [server.jar:?]
        at cn.nukkit.plugin.PluginManager.loadPlugins(PluginManager.java:120) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:505) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:120) [server.jar:?]
21:11:38 [FATAL] Could not load plugin "MiraiMC"
21:11:38 [INFO ] Loading MultiWorld v1.1
21:11:38 [INFO ] Loading RankingAPI v1.4.4-SNAPSHOT
21:11:38 [INFO ] Loading ReplaceCommand v0.1
21:11:38 [INFO ] Loading ScoreboardPlugin v1.0
21:11:38 [INFO ] Loading spark v1.10.43
21:11:38 [INFO ] Loading Tips v2.1.7-SNAPSHOT
21:11:38 [INFO ] Loading TipsVeriable v1.0.2
21:11:38 [INFO ] Loading TransferWDPE v1.0.0
21:11:38 [INFO ] Loading CTask v0.1
21:11:38 [INFO ] Loading MemoriesOfTime-GameCore v1.6.11-SNAPSHOT
21:11:38 [INFO ] Enabling RankingAPI v1.4.4-SNAPSHOT
21:11:38 [INFO ] [RankingAPI] RankingAPI Enabled！ Version：1.4.4-SNAPSHOT git-858c071
21:11:38 [INFO ] Enabling TipsVeriable v1.0.2
21:11:38 [INFO ] [TipsVeriable] Tips 变量拓展加载成功
21:11:38 [INFO ] Enabling MemoriesOfTime-GameCore v1.6.11-SNAPSHOT
21:11:38 [INFO ] [MemoriesOfTime-GameCore] MemoriesOfTime-GameCore Enabled! Version:1.6.11-SNAPSHOT git-fce87e9
21:11:38 [INFO ] Preparing level "lobby"
21:11:38 [INFO ] Preparing start region for level "lobby"
21:11:39 [INFO ] Preparing level "nether"
21:11:39 [INFO ] Preparing start region for level "nether"
21:11:39 [INFO ] Enabling CParkour v0.1
21:11:39 [INFO ] Enabling DataManager v0.2
21:11:39 [INFO ] [DataManager] 变量已成功注册了0个!
21:11:39 [INFO ] [DataManager] 插件工作模式:only
21:11:39 [INFO ] [DataManager] 插件加载成功, 目前运行插件版本号:0.2
21:11:39 [INFO ] Enabling EconomyAPI v2.0.2
21:11:39 [INFO ] [EconomyAPI] Data provider was set to: Yaml
21:11:39 [INFO ] Enabling HiddenCommands v1.0
21:11:39 [INFO ] Enabling JoinCommand v1.0.0-SNAPSHOT
21:11:39 [INFO ] [JoinCommand] Version: 1.0.0-SNAPSHOT git-b559047
21:11:39 [INFO ] Enabling MultiWorld v1.1
21:11:39 [INFO ] Enabling ReplaceCommand v0.1
21:11:39 [INFO ] [ReplaceCommand] 插件启动!
21:11:39 [INFO ] Enabling ScoreboardPlugin v1.0
21:11:39 [INFO ] Enabling spark v1.10.43
21:11:39 [INFO ] [spark] Starting background profiler...
21:11:40 [INFO ] [spark] The async-profiler engine is not supported for your os/arch (windowsserver2019/amd64), so the built-in Java engine will be used instead.
21:11:40 [INFO ] Enabling Tips v2.1.7-SNAPSHOT
21:11:40 [INFO ] [Tips] 加载样式: default
21:11:40 [INFO ] [Tips] 当前样式已设置为: default
21:11:40 [INFO ] [Tips] 检测到 MemoriesOfTime-GameCore 成功开启计分板功能
21:11:40 [INFO ] [Tips] 插件加载完成~
21:11:40 [INFO ] Enabling TransferWDPE v1.0.0
21:11:40 [INFO ] Enabling CTask v0.1
21:11:40 [INFO ] [DataManager] 变量每日任务_bw_status注册成功!
21:11:40 [INFO ] [DataManager] 变量每日任务_bw_progress注册成功!
21:11:40 [INFO ] [DataManager] 变量每日任务_bw_finish注册成功!
21:11:40 [INFO ] [CTask] 插件已加载
21:11:40 [INFO ] Starting GS4 status listener
21:11:40 [INFO ] Setting query port to 19137
21:11:40 [INFO ] Query is running on 127.0.0.1:19137
21:11:40 [INFO ] Default game type: Survival Mode
21:11:40 [INFO ] Done (4.512s)! For help, type "help" or "?"
21:11:40 [WARN ] [RankingAPI]  RankingAPI 是一款免费插件，开源链接: https://github.com/lt-name/RankingAPI
> ver
21:18:32 [INFO ] This server is running Nukkit git-9a84110 「」 implementing API version 1.0.14 for Minecraft: BE v1.20.10 (protocol version 594)
> mirai
21:21:22 [INFO ] Unknown command. Try /help for a list of commands
```

### 额外说明

Windows server 2019 , jdk17 , nukkitx

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
已修复，请更新最新开发版使用，新版本不久会发布。
