### ISSUE TITLE
开发版报错NoClassDefFoundError

### ISSUE THREAD

**Issue by CoolMagic233** [DreamVoid/MiraiMC#437]
### 问题描述

报错NoClassDefFoundError导致插件卸载并关闭服务器

### 复现方法

1. 下载actions的开发版 https://github.com/DreamVoid/MiraiMC/actions/runs/5715440240
2. 启动服务端

### 服务端类型

Nukkit

### 服务端版本

Nukkit-PM1E-MOT-1.20.10

### MiraiMC 插件版本

vdev-255

### 服务端日志

```text
06:45:22 [INFO ] -- Nukkit MOT --
06:45:28 [INFO ] Loaded 0 resource packs
06:45:28 [INFO ] Opening server on 0.0.0.0:20040
06:45:29 [WARN ] Unknown channel option 'IP_DONTFRAG' for channel '[id: 0x2e6f2238]'
06:45:29 [INFO ] Enabling Nukkit-MOT vgit-f742995
06:45:29 [INFO ] Loading BridgingPractise v2.5
06:45:29 [INFO ] Loading CDuels v0.4.1
06:45:29 [INFO ] Loading CPSCounter v1.0.1
06:45:29 [INFO ] Loading CustomForm v1.0.6Candidate1
06:45:29 [INFO ] Loading DataManager v0.4
06:45:29 [INFO ] Loading DbLib v1.0.1
06:45:29 [INFO ] [DbLib] Establishing a connection withjdbc:sqlite:nukkit.db (user:nukkit)
> Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
06:45:29 [INFO ] [DbLib] DbLib 1.0.1 created by fromgate for nukkit.ru
06:45:29 [INFO ] Loading EconomyAPI v2.0.2
06:45:29 [INFO ] Loading FFAKB v1.0.0
06:45:29 [INFO ] Loading HiddenCommands v1.0
06:45:29 [INFO ] Loading JoinCommand v1.0.0-SNAPSHOT
06:45:29 [INFO ] Loading KDR_C v1.1
06:45:29 [INFO ] Loading KotlinLib v1.4.31
06:45:29 [INFO ] Loading LevelSystem v0.0.5
06:45:29 [INFO ] Loading LockTime v1.0.0
06:45:29 [INFO ] Loading MainLobbyPlugin v1.0.0
06:45:29 [INFO ] [MainLobbyPlugin] Plugin load!
06:45:29 [INFO ] Loading MiraiMC vdev-255
06:45:29 [INFO ] [MiraiMC] Preparing MiraiMC start-up.
06:45:30 [INFO ] [MiraiMC] Start-up tasks finished.
06:45:30 [INFO ] [MiraiMC] Preparing MiraiMC pre-load.
06:45:30 [INFO ] [MiraiMC] Loading config.
06:45:30 [INFO ] [MiraiMC] Mirai working dir: default
06:45:30 [INFO ] [MiraiMC] Selected mirai core version: stable
06:45:31 [INFO ] [MiraiMC] Verifying mirai-core-all-2.13.2.jar
06:45:31 [INFO ] [MiraiMC] Loading library C:\Users\Administrator\Desktop\stage-1\plugins\MiraiMC\MiraiBot\libs\mirai-core-all-2.13.2.jar
06:45:31 [INFO ] [MiraiMC] Pre-load tasks finished.
06:45:31 [INFO ] Loading MultiWorld v1.1
06:45:31 [INFO ] Loading RankingAPI v1.4.4-SNAPSHOT
06:45:31 [INFO ] Loading RankShop v0.0.7
06:45:31 [INFO ] Loading ReplaceCommand v0.1
06:45:31 [INFO ] Loading ScoreboardPlugin v1.0
06:45:31 [INFO ] Loading spark v1.10.43
06:45:32 [INFO ] Loading Tips v2.1.7-SNAPSHOT
06:45:32 [INFO ] Loading TipsVeriable v1.0.2
06:45:32 [INFO ] Loading WorldFixer v1.6
06:45:32 [INFO ] Loading WorldProtect v2.3
06:45:32 [INFO ] Loading EAPIMySQLProvider v1.0.3
06:45:32 [INFO ] Loading BedWar v1.8.21
06:45:32 [INFO ] Loading MemoriesOfTime-GameCore v1.6.11-SNAPSHOT
06:45:32 [INFO ] Loading RsNPC v2.3.2-PM1E-SNAPSHOT
06:45:32 [INFO ] Loading CrystalWars v0.6.0-SNAPSHOT
06:45:32 [INFO ] [CrystalWars] 已启用中文！
06:45:32 [INFO ] Loading BFFA v0.1.0
06:45:32 [INFO ] Loading HuntGame v1.2.1-PM1E-
06:45:32 [INFO ] [HuntGame] Language: de_DE loaded !
06:45:32 [INFO ] [HuntGame] Language: en_US loaded !
06:45:32 [INFO ] [HuntGame] Language: zh_CN loaded !
06:45:33 [INFO ] Enabling DataManager v0.4
06:45:33 [INFO ] [DataManager] 变量已成功注册了0个!
06:45:33 [INFO ] [DataManager] 插件工作模式:only
06:45:33 [INFO ] [DataManager] 插件加载成功, 目前运行插件版本号:0.4
06:45:33 [INFO ] Enabling RankingAPI v1.4.4-SNAPSHOT
06:45:33 [INFO ] [RankingAPI] RankingAPI Enabled！ Version：1.4.4-SNAPSHOT git-e401137
06:45:33 [INFO ] Enabling TipsVeriable v1.0.2
06:45:33 [INFO ] [TipsVeriable] Tips 变量拓展加载成功
06:45:33 [INFO ] Enabling MemoriesOfTime-GameCore v1.6.11-SNAPSHOT
06:45:33 [WARN ] [MemoriesOfTime-GameCore] Warning! The current plugin version is not applicable to this server core! Please check the plugin version!
06:45:33 [WARN ] [MemoriesOfTime-GameCore] Server Code : Nukkit MOT  |  Plugin Version : 1.6.11-SNAPSHOT git-fce87e9
06:45:36 [INFO ] [MemoriesOfTime-GameCore] MemoriesOfTime-GameCore Enabled! Version:1.6.11-SNAPSHOT git-fce87e9
06:45:36 [INFO ] Preparing level "lobby"
06:45:36 [INFO ] Preparing level "bpractise"
06:45:36 [INFO ] Preparing level "Clutch-1"
06:45:36 [INFO ] Preparing level "Comboly"
06:45:36 [INFO ] Preparing level "Crystalwars#1"
06:45:36 [INFO ] Preparing level "Crystalwars#2"
06:45:36 [INFO ] Preparing level "Fist"
06:45:36 [INFO ] Preparing level "Gapple"
06:45:36 [INFO ] Preparing level "HuntGame#1"
06:45:36 [INFO ] Preparing level "HuntGame#2"
06:45:36 [INFO ] Preparing level "HuntGame#3"
06:45:36 [INFO ] Preparing level "Knock"
06:45:36 [INFO ] Preparing level "Knock1"
06:45:36 [INFO ] Preparing level "Knock2"
06:45:36 [INFO ] Preparing level "Knock3"
06:45:36 [INFO ] Preparing level "nether"
06:45:36 [INFO ] Preparing level "Nodebuff"
06:45:36 [INFO ] Preparing level "Sumo"
06:45:36 [INFO ] Preparing level "Sumo-1"
06:45:36 [INFO ] Preparing level "Sumo-2"
06:45:36 [INFO ] Preparing level "Sumo-3"
06:45:36 [INFO ] Preparing level "Training"
06:45:36 [INFO ] Preparing level "Void"
06:45:36 [INFO ] Preparing level "world"
06:45:36 [INFO ] Enabling BridgingPractise v2.5
06:45:37 [INFO ] BridgingPractiseNK By [Hapixel Dev Team] Successfully Loaded.
06:45:37 [INFO ] Enabling CDuels v0.4.1
06:45:37 [INFO ] [CDuels] 开始识别房间
06:45:37 [INFO ] [CDuels] 开始识别Sumo的房间
06:45:37 [INFO ] [CDuels] 识别到房间->Sumo-1
06:45:37 [INFO ] [CDuels] 识别到房间->Sumo-2
06:45:37 [INFO ] [CDuels] 识别到房间->Sumo-3
06:45:37 [INFO ] [CDuels] 开始识别Builduhc的房间
06:45:37 [INFO ] [CDuels] 开始识别NodeBuff的房间
06:45:37 [INFO ] [CDuels] 开始识别Fist的房间
06:45:37 [INFO ] [CDuels] 开始识别Iron的房间
06:45:37 [INFO ] [CDuels] 已识别房间3个
06:45:37 [INFO ] [CDuels] 插件加载完成
06:45:37 [INFO ] Enabling CPSCounter v1.0.1
06:45:37 [INFO ] [CPSCounter] 插件加载成功!
06:45:37 [INFO ] Enabling CustomForm v1.0.6Candidate1
06:45:37 [INFO ] [CustomForm] 检测到您安装了Tips前置，已经自动开启适配功能！
06:45:37 [INFO ] [CustomForm] 检测到您未安装了DCurrency前置，未开启适配功能！
06:45:37 [INFO ] [CustomForm] 检测到您安装了EconomyAPI前置，已经自动开启适配功能！
06:45:37 [INFO ] [CustomForm] 检测到您未安装了playerPoints前置，未开启适配功能！
06:45:37 [INFO ] [CustomForm] 成功加载窗口:duels
06:45:37 [INFO ] [CustomForm] 成功加载窗口:Games
06:45:37 [INFO ] [CustomForm] 成功加载窗口:Information
06:45:37 [INFO ] [CustomForm] 成功加载3个脚本窗口
06:45:37 [INFO ] [CustomForm] CustomForm onLoad
06:45:37 [INFO ] Enabling DbLib v1.0.1
06:45:37 [INFO ] Enabling EconomyAPI v2.0.2
06:45:37 [INFO ] [EconomyAPI] Data provider was set to: Yaml
06:45:37 [INFO ] Enabling FFAKB v1.0.0
06:45:37 [INFO ] Enabling HiddenCommands v1.0
06:45:37 [INFO ] Enabling JoinCommand v1.0.0-SNAPSHOT
06:45:37 [INFO ] [JoinCommand] Version: 1.0.0-SNAPSHOT git-b559047
06:45:37 [INFO ] Enabling KDR_C v1.1
06:45:37 [INFO ] [DataManager] 变量defeat注册成功!
06:45:37 [INFO ] [DataManager] 变量death注册成功!
06:45:37 [INFO ] [DataManager] 变量victory注册成功!
06:45:37 [INFO ] [DataManager] 变量beat注册成功!
06:45:37 [INFO ] Enabling KotlinLib v1.4.31
06:45:37 [INFO ] Enabling LevelSystem v0.0.5
06:45:37 [INFO ] [DataManager] 变量level注册成功!
06:45:37 [INFO ] [DataManager] 变量exp注册成功!
06:45:37 [INFO ] [LevelSystem] 插件加载完毕!当前版本: 0.0.4
06:45:37 [INFO ] Enabling LockTime v1.0.0
06:45:37 [INFO ] [LockTime] LockTime插件启动,时间锁定为6000
06:45:37 [INFO ] Enabling MainLobbyPlugin v1.0.0
06:45:37 [INFO ] [MainLobbyPlugin] Plugin enable!
06:45:37 [INFO ] Enabling MiraiMC vdev-255
06:45:37 [INFO ] [MiraiMC] Preparing MiraiMC post-load.
06:45:37 [INFO ] [MiraiMC] Initializing SQLite database.
06:45:37 [INFO ] [MiraiMC] Starting Mirai-Event listener.
06:45:38 [ERROR] Throwing
java.lang.RuntimeException: plugin: MiraiMC load failed!
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:426) [server.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:927) [server.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:917) [server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:748) [server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:87) [server.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/mamoe/mirai/event/events/SignEvent
        at me.dreamvoid.miraimc.nukkit.MiraiEvent.startListenEvent(MiraiEvent.java:181) ~[MiraiMC-Nukkit.jar:?]
        at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:133) ~[MiraiMC-Nukkit.jar:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:51) ~[MiraiMC-Nukkit.jar:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:92) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:422) ~[server.jar:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.event.events.SignEvent
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at me.dreamvoid.miraimc.nukkit.MiraiEvent.startListenEvent(MiraiEvent.java:181) ~[MiraiMC-Nukkit.jar:?]
        at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:133) ~[MiraiMC-Nukkit.jar:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onEnable(NukkitPlugin.java:51) ~[MiraiMC-Nukkit.jar:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:92) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:119) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:422) ~[server.jar:?]
        ... 4 more
06:45:38 [INFO ] Disabling MiraiMC vdev-255
06:45:38 [INFO ] [MiraiMC] Preparing MiraiMC unload.
06:45:38 [INFO ] [MiraiMC] Closing all bots
06:45:38 [ERROR] Throwing
java.lang.NoClassDefFoundError: net/mamoe/mirai/auth/QRCodeLoginListener
        at me.dreamvoid.miraimc.MiraiMCPlugin.unload(MiraiMCPlugin.java:190) ~[MiraiMC-Nukkit.jar:?]
        at me.dreamvoid.miraimc.nukkit.NukkitPlugin.onDisable(NukkitPlugin.java:81) ~[MiraiMC-Nukkit.jar:?]
        at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:94) ~[server.jar:?]
        at cn.nukkit.plugin.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:134) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.disablePlugin(PluginManager.java:504) ~[server.jar:?]
        at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:428) ~[server.jar:?]
        at cn.nukkit.Server.enablePlugin(Server.java:927) ~[server.jar:?]
        at cn.nukkit.Server.enablePlugins(Server.java:917) ~[server.jar:?]
        at cn.nukkit.Server.<init>(Server.java:748) ~[server.jar:?]
        at cn.nukkit.Nukkit.main(Nukkit.java:87) [server.jar:?]
Caused by: java.lang.ClassNotFoundException: net.mamoe.mirai.auth.QRCodeLoginListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:43) ~[server.jar:?]
        at cn.nukkit.plugin.PluginClassLoader.findClass(PluginClassLoader.java:27) ~[server.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:587) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 10 more
>
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
修改配置文件的mirai版本为latest
