### ISSUE TITLE
Velocity下报错

### ISSUE THREAD

**Issue by Q2297045667** [DreamVoid/MiraiMC#446]
### 问题描述

默认配置文件的情况下Velocity报错

### 复现方法

1. Velocity正常加载插件

### 服务端类型

Velocity

### 服务端版本

velocity-3.2.0-SNAPSHOT-265

### MiraiMC 插件版本

1.8

### 服务端日志

```text
[19:48:17 ERROR]: Can't construct a java object for tag:yaml.org,2002:me.dreamvoid.miraimc.internal.ConfigSerializable; exception=Class not found: me.dreamvoid.miraimc.internal.ConfigSerializable
[19:48:17 ERROR]:  in 'string', line 5, column 1:
[19:48:17 ERROR]:     general:
[19:48:17 ERROR]:     ^
[19:48:17 ERROR]: 
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:336)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:452)
[19:48:17 ERROR]:       at me.dreamvoid.miraimc.velocity.VelocityConfig.loadConfig(VelocityConfig.java:34)
[19:48:17 ERROR]:       at me.dreamvoid.miraimc.MiraiMCPlugin.preLoad(MiraiMCPlugin.java:56)
[19:48:17 ERROR]:       at me.dreamvoid.miraimc.velocity.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:73)
[19:48:17 ERROR]:       at me.dreamvoid.miraimc.velocity.Lmbda$17.execute(Unknown Source)
[19:48:17 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[19:48:17 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[19:48:17 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[19:48:17 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[19:48:17 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[19:48:17 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[19:48:17 ERROR]: Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: me.dreamvoid.miraimc.internal.ConfigSerializable
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:664)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:322)
[19:48:17 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
[19:48:17 ERROR]:       ... 16 more
[19:48:17 INFO] [miraimc]: Preparing MiraiMC post-load.
[19:48:17 ERROR]: Couldn't pass ProxyInitializeEvent to miraimc
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "me.dreamvoid.miraimc.MiraiMCConfig$Database.Type" is null
        at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:116) ~[?:?]
        at me.dreamvoid.miraimc.velocity.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:83) ~[?:?]
        at me.dreamvoid.miraimc.velocity.Lmbda$17.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-265.jar:3.2.0-SNAPSHOT (git-19abb909-b265)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [X] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by Q2297045667** [comment]
注：最新的actions版本也报错
