### ISSUE TITLE
希望能获得被回复的消息内容

### ISSUE THREAD

**Issue by Maplefsnow** [DreamVoid/MiraiMC#45]
**功能描述**

建议增加获得“被回复的消息”的内容的功能，即当群内有人回复之前的某一条消息时，能便捷地获得该条消息的详细信息（event.getRepliedMessage之类）

**使用方法**

1. qwq

**额外说明**

qwqwq

**Comment by DreamVoid** [comment]
这个和GroupMessageEvent有什么区别吗？

**Comment by Maplefstar** [comment]
> 这个和GroupMessageEvent的getMessageToMirai有什么区别吗？

类似这种情况，下图中的消息只有下面的主体部分可以被获取，但是被引用的引文和被引人，没有比较直接的获取方法。
故在此建议添加该方法。
![IMG_20210924_205146.jpg](https://user-images.githubusercontent.com/45029436/134677145-bfc9fd3b-cfd8-4cb2-9423-0b54d81dd10b.jpg)

**Comment by DreamVoid** [comment]
> 但是被引用的引文和被引人，

```QuoteReply```是找到了，但是Mirai提供的事件里没有直接获取这个的，我也不知道```QuoteReply```要怎么用
等我好好研究一下吧。
当然如果你研究出来了也可以告诉我或者直接开PR

**Comment by Maplefstar** [comment]
> > 但是被引用的引文和被引人，
> 
> ```QuoteReply```是找到了，但是Mirai提供的事件里没有直接获取这个的，我也不知道```QuoteReply```要怎么用
> 等我好好研究一下吧。
> 当然如果你研究出来了也可以告诉我或者直接开PR

好的，我也去研究一下

**Comment by Wagoodnight** [comment]
请问为什么每次都会出现这种情况？
----------------------------------------------------------------------------------------------------------------------------------------------
[36m08:24:33 [[34mINFO ] 已将ticket提交到服务器
[36m08:24:33 [[31mWARN ] [MiraiMC] null
>net.mamoe.mirai.network.WrongPasswordException: Error(bot=Bot(312***077), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁
at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl.doLogin(SsoProcessor.kt:265) ~[mirai-core-all-2.8-M1.jar:2.8-M1]
at net.mamoe.mirai.internal.network.components.SsoProcessorImpl$SlowLoginImpl$doLogin$1.invokeSuspend(SsoProcessor.kt) ~[mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [mirai-core-all-2.8-M1.jar:2.8-M1]
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [mirai-core-all-2.8-M1.jar:2.8-M1]
[36m08:24:33 [[34mINFO ] [MiraiMC] Bot cancelled: Bot closed
[36m08:24:33 [[31mWARN ] [MiraiMC] 登录机器人时出现异常，原因: Error(bot=Bot(312***077), code=237, title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=), tips=若频繁出现, 请尝试开启设备锁

**Comment by iamyou** [comment]
bot.getEventChannel().subscribeAlways<GroupMessageEvent>(event -> {
    MessageChain chain = new MessageChainBuilder() // 引用收到的消息并回复 "Hi!", 也可以添加图片等更多元素.
        .append(new QuoteReply(event.getMessage()))
        .append("Hi!")
        .build();
    event.getSubject().sendMessage(chain);
});
这个是官方给的方法

**Comment by iamyou** [comment]
回复是属于消息的元数据……
QuoteReply quote = chain.get(QuoteReply.Key);
这样获取quote
然后……怎么用……

**Comment by iamyou** [comment]
https://mirai.mamoe.net/topic/679/%E5%85%B3%E4%BA%8E%E8%8E%B7%E5%8F%96%E5%9B%9E%E5%A4%8D%E6%B6%88%E6%81%AF%E7%9A%84%E9%97%AE%E9%A2%98
我去问了

**Comment by DreamVoid** [comment]
我大致有一点思路，你等一下去Jenkins CI下载最新开发版试一下
我没上传maven中央仓库，你要自己引入maven本地jar库
