### ISSUE TITLE
插件在 Velocity 平台无法正常加载。

### ISSUE THREAD

**Issue by XXY233** [DreamVoid/MiraiMC#461]
### 问题描述

我是第一次全新安装插件，插件在 Velocity 平台无法正常加载。

### 复现方法

1. 将插件放入 plugins 文件夹。
2. 启动 velocity 服务器。

### 服务端类型

Velocity

### 服务端版本

Velocity 3.2.0-SNAPSHOT (git-ae63da68-b286)

### MiraiMC 插件版本

1.8

### 服务端日志

```text
[12:25:38 INFO]: Booting up Velocity 3.2.0-SNAPSHOT (git-ae63da68-b286)...
[12:25:38 INFO]: Loading localizations...
[12:25:38 INFO]: Connections will use NIO channels, Java compression, Java ciphers
[12:25:39 WARN]: Player info forwarding is disabled! All players will appear to be connecting from the proxy and will have offline-mode UUIDs.
[12:25:39 INFO]: Loading plugins...
[12:25:39 INFO] [miraimc]: Preparing MiraiMC start-up.
[12:25:39 INFO] [miraimc]: Start-up tasks finished.
[12:25:39 INFO]: Loaded plugin miraimc 1.8 by DreamVoid
[12:25:39 INFO]: Loaded 1 plugins
[12:25:39 INFO] [miraimc]: Preparing MiraiMC pre-load.
[12:25:39 INFO] [miraimc]: Loading config.
[12:25:39 WARN] [miraimc]: An error occurred while loading plugin.
[12:25:39 ERROR]: Can't construct a java object for tag:yaml.org,2002:me.dreamvoid.miraimc.internal.ConfigSerializable; exception=Class not found: me.dreamvoid.miraimc.internal.ConfigSerializable
[12:25:39 ERROR]:  in 'string', line 5, column 1:
[12:25:39 ERROR]:     general:
[12:25:39 ERROR]:     ^
[12:25:39 ERROR]:
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:364)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:270)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:253)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:207)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:191)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:477)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:457)
[12:25:39 ERROR]:       at me.dreamvoid.miraimc.velocity.VelocityConfig.loadConfig(VelocityConfig.java:34)
[12:25:39 ERROR]:       at me.dreamvoid.miraimc.MiraiMCPlugin.preLoad(MiraiMCPlugin.java:56)
[12:25:39 ERROR]:       at me.dreamvoid.miraimc.velocity.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:73)
[12:25:39 ERROR]:       at me.dreamvoid.miraimc.velocity.Lmbda$1.execute(Unknown Source)
[12:25:39 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[12:25:39 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[12:25:39 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[12:25:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[12:25:39 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[12:25:39 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[12:25:39 ERROR]: Caused by: org.yaml.snakeyaml.error.YAMLException: Class not found: me.dreamvoid.miraimc.internal.ConfigSerializable
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor.getClassForNode(Constructor.java:685)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.getConstructor(Constructor.java:349)
[12:25:39 ERROR]:       at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:358)
[12:25:39 ERROR]:       ... 16 more
[12:25:39 INFO] [miraimc]: Preparing MiraiMC post-load.
[12:25:39 ERROR]: Couldn't pass ProxyInitializeEvent to miraimc
java.lang.NullPointerException: Cannot invoke "String.toLowerCase()" because "me.dreamvoid.miraimc.MiraiMCConfig$Database.Type" is null
        at me.dreamvoid.miraimc.MiraiMCPlugin.postLoad(MiraiMCPlugin.java:116) ~[?:?]
        at me.dreamvoid.miraimc.velocity.VelocityPlugin.onProxyInitialization(VelocityPlugin.java:83) ~[?:?]
        at me.dreamvoid.miraimc.velocity.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.2.0-SNAPSHOT-286.jar:3.2.0-SNAPSHOT (git-ae63da68-b286)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity-3.2.0-SNAPSHOT-286.jar:3.2.0-SNAPSHOT (git-ae63da68-b286)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity-3.2.0-SNAPSHOT-286.jar:3.2.0-SNAPSHOT (git-ae63da68-b286)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
[12:25:39 INFO]: Listening on /[0:0:0:0:0:0:0:0]:25577
[12:25:39 INFO]: Done (1.19s)!
```

### 额外说明

这个问题似乎两个月前就有了，但是由于发起 issue 的人乱填模板导致被忽视了：https://github.com/DreamVoid/MiraiMC/issues/446

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
尝试用压缩文件打开 jar 文件，然后导航到 `me/dreamvoid/miraimc/internal` 目录，告诉我是否有 `ConfigSerializable.class` 文件。
最近很忙，回复慢。

**Comment by XXY233** [comment]
感谢您百忙之中抽出时间回复我！我按照你的要求刚刚查看了 jar 文件，确实存在 `ConfigSerializable.class` 文件。
![image](https://github.com/DreamVoid/MiraiMC/assets/46647646/f551c5c0-63a6-47d0-be84-1e3fbe76c209)

**Comment by 100luo-6** [comment]
您解决了吗

**Comment by XXY233** [comment]
> 您解决了吗

还没有解决，请等待作者回复。

**Comment by DreamVoid** [comment]
配置中删掉`legacy-event-support: false`即可正常加载
