### ISSUE TITLE
Waterfall使用MiraiMC发送消息提示Illegal input

### ISSUE THREAD

**Issue by 1301727735** [DreamVoid/MiraiMC#492]
### 问题描述

1.BungeeCord连接MCL后无法发送消息
2.提示 Illegal input
3.群消息无法正确转发

### 复现方法

1. 重启Bungee
2. 以HTTP-API方式登录
3. 发送消息，戳一戳或者使用chat2qq的/qchat

### 服务端类型

BungeeCord

### 服务端版本

waterfall-1.20-564

### MiraiMC 插件版本

version dev-210

### 服务端日志

```text
[07:34:01] [main/INFO]: Using standard Java JCE cipher.
[07:34:01] [main/INFO]: Using standard Java compressor.
[07:34:01] [main/INFO]: Enabled Waterfall version git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=cmd_alert, file=modules\cmd_alert.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=cmd_find, file=modules\cmd_find.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=cmd_list, file=modules\cmd_list.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=cmd_send, file=modules\cmd_send.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=cmd_server, file=modules\cmd_server.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Discovered module: ModuleSpec(name=reconnect_yaml, file=modules\reconnect_yaml.jar, provider=JenkinsModuleSource())
[07:34:01] [main/INFO]: Loaded plugin MiniMOTD version 2.1.0 by jmp
[07:34:01] [main/INFO]: Loaded plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:01] [main/INFO]: Loaded plugin LuckPerms version 5.4.119 by Luck
[07:34:02] [main/INFO]: Loaded plugin ntdRpChatAdapter version 1.0.0 by danirod12
[07:34:03] [main/INFO]: Loaded plugin nLogin version 10.2.53 by NickUC
[07:34:03] [main/INFO]: Loaded plugin nAntiBot version 6.1.19 by NickUC
[07:34:04] [main/INFO] [Geyser-BungeeCord]: 正在加载插件...
[07:34:04] [main/INFO] [Geyser-BungeeCord]: 已启用插件 RYSurvival-SlimefunMapping
[07:34:04] [main/INFO] [Geyser-BungeeCord]: 已加载 1 个插件
[07:34:04] [main/INFO] [Geyser-BungeeCord]: [simefunmapping] 任渊生存-粘液材质映射已加载
[07:34:04] [main/INFO]: Loaded plugin Geyser-BungeeCord version 2.2.2-SNAPSHOT by GeyserMC
[07:34:04] [main/INFO]: Loaded plugin GeyserSkinManager-BungeeCord version 1.7 by Camotoy
[07:34:04] [main/INFO]: Loaded plugin FallBackServer version 3.2.0-Beta2 by CandiesJar
[07:34:04] [main/INFO] [MiraiMC]: Preparing MiraiMC start-up.
[07:34:04] [main/INFO] [MiraiMC]: Start-up tasks finished.
[07:34:04] [main/INFO] [MiraiMC]: Preparing MiraiMC pre-load.
[07:34:04] [main/INFO] [MiraiMC]: Loading config.
[07:34:04] [main/INFO] [MiraiMC]: Mirai working dir: C:\Users\Administrator\Desktop\mirai1
[07:34:04] [main/INFO] [MiraiMC]: Selected mirai core version: latest
[07:34:04] [main/INFO] [MiraiMC]: Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[07:34:04] [main/INFO] [MiraiMC]: Verifying mirai-core-all-2.16.0.jar
[07:34:04] [main/INFO] [MiraiMC]: Loading library C:\Users\Administrator\Desktop\mirai1\libs\mirai-core-all-2.16.0.jar
[07:34:04] [main/INFO] [MiraiMC]: Pre-load tasks finished.
[07:34:04] [main/INFO]: Loaded plugin MiraiMC version dev-210 by DreamVoid
[07:34:04] [main/INFO]: Loaded plugin PlugManBungee version 2.3.7 by null
[07:34:04] [main/INFO]: Loaded plugin cmd_server version git:cmd_server:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:04] [main/INFO]: Loaded plugin cmd_send version git:cmd_send:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:04] [main/INFO]: Loaded plugin Chat2QQ version 1.6 by DreamVoid
[07:34:04] [main/WARN] [floodgate]: This is a fork of Floodgate by kejonaMC that allows using the Floodgate API on BungeeCord and Velocity when Geyser is also installed. Geyser is required for this to work.
[07:34:04] [main/INFO] [floodgate]: 成功启动 Floodgate，耗时346ms
[07:34:04] [main/INFO]: Loaded plugin floodgate version 2.2.2-SNAPSHOT (b20-987d918) by GeyserMC
[07:34:04] [main/INFO]: Loaded plugin SkinsRestorer version 15.0.7 by knat, AlexProgrammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[07:34:04] [main/INFO]: Loaded plugin BungeeGuard version 1.3-SNAPSHOT by Luck
[07:34:04] [main/INFO]: Loaded plugin BungeePackFix version 1.1.6-beta-1 by LoneDev
[07:34:04] [main/INFO]: Loaded plugin cmd_list version git:cmd_list:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:04] [main/INFO]: Loaded plugin InteractiveChatBungee version 4.2.9.0 by LOOHP
[07:34:04] [main/INFO]: Loaded plugin cmd_find version git:cmd_find:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:04] [main/INFO]: Loaded plugin TAB version 4.1.2 by NEZNAMY
[07:34:04] [main/INFO]: Loaded plugin FriendSystem version 3.9 by sk8ingDuck
[07:34:04] [main/INFO]: Loaded plugin cmd_alert version git:cmd_alert:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:04] [main/INFO]: 正在读取配置文件plugins\mesagisto\config.yml
[07:34:05] [main/INFO]: Loaded plugin Mesagisto version 1.0.0-rc by null
[07:34:05] [main/INFO]: Loaded plugin BungeeTp version 1.0.2 by SavageAvocado
[07:34:05] [main/WARN]: Forced host server pvp is not defined
[07:34:05] [main/INFO]: Enabled plugin MiniMOTD version 2.1.0 by jmp
[07:34:05] [main/INFO]: Enabled plugin reconnect_yaml version git:reconnect_yaml:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:05] [main/INFO]:         __    
[07:34:05] [main/INFO]:   |    |__)   LuckPerms v5.4.119
[07:34:05] [main/INFO]:   |___ |      Running on BungeeCord - Waterfall
[07:34:05] [main/INFO]: 
[07:34:06] [main/INFO] [LuckPerms]: Loading configuration...
[07:34:06] [main/INFO] [LuckPerms]: Loading storage provider... [H2]
[07:34:06] [main/INFO] [LuckPerms]: Loading messaging service... [SQL]
[07:34:06] [main/ERROR] [LuckPerms]: Exception occurred whilst enabling SQL messaging service
java.lang.IllegalStateException: Can't find a supported sql storage implementation
	at me.lucko.luckperms.common.messaging.MessagingFactory$SqlMessengerProvider.obtain(MessagingFactory.java:269) ~[?:?]
	at me.lucko.luckperms.common.messaging.LuckPermsMessagingService.<init>(LuckPermsMessagingService.java:69) ~[?:?]
	at me.lucko.luckperms.common.messaging.MessagingFactory.getServiceFor(MessagingFactory.java:143) ~[?:?]
	at me.lucko.luckperms.bungee.messaging.BungeeMessagingFactory.getServiceFor(BungeeMessagingFactory.java:62) ~[?:?]
	at me.lucko.luckperms.common.messaging.MessagingFactory.getInstance(MessagingFactory.java:102) ~[?:?]
	at me.lucko.luckperms.common.plugin.AbstractLuckPermsPlugin.enable(AbstractLuckPermsPlugin.java:202) ~[?:?]
	at me.lucko.luckperms.bungee.LPBungeeBootstrap.onEnable(LPBungeeBootstrap.java:168) ~[?:?]
	at me.lucko.luckperms.bungee.loader.BungeeLoaderPlugin.onEnable(BungeeLoaderPlugin.java:50) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:302) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
[07:34:06] [main/WARN] [LuckPerms]: Messaging service 'sql' not recognised.
[07:34:06] [main/INFO] [LuckPerms]: Loading internal permission managers...
[07:34:06] [main/INFO] [LuckPerms]: Performing initial data load...
[07:34:06] [main/INFO] [LuckPerms]: Successfully enabled. (took 1070ms)
[07:34:06] [main/INFO]: Enabled plugin LuckPerms version 5.4.119 by Luck
[07:34:06] [main/INFO]: Reloading configuration...
[07:34:06] [main/INFO]: Adding scope main with 3 servers
[07:34:06] [main/INFO]: Enabled plugin ntdRpChatAdapter version 1.0.0 by danirod12
[07:34:06] [main/INFO] [nLogin]: Successful plugin core start (took 0.15s)
[07:34:07] [main/INFO]:           __             _       
[07:34:07] [main/INFO]:   _ __   / /  ___   __ _(_)_ __  
[07:34:07] [main/INFO]:  | '_ \ / /  / _ \ / _` | | '_ \ 
[07:34:07] [main/INFO]:  | | | / /__| (_) | (_| | | | | |
[07:34:07] [main/INFO]:  |_| |_\____/\___/ \__, |_|_| |_|
[07:34:07] [main/INFO]:                   |___/            
[07:34:07] [main/INFO]:  By: www.nickuc.com - V 10.2.53
[07:34:07] [main/INFO]:  
[07:34:07] [main/ERROR]: [main] INFO com.nickuc.login.lib.hikari.HikariDataSource - nlogin-hikaricp - Starting...
[07:34:07] [main/ERROR]: [main] INFO com.nickuc.login.lib.hikari.HikariDataSource - nlogin-hikaricp - Start completed.
[07:34:07] [main/WARN] [nLogin]: Disabling Cumulus forms, since it is broken for BungeeCord: https://github.com/GeyserMC/Floodgate/issues/178.
[07:34:07] [main/WARN] [nLogin]: As a workaround, you can use kejonaMC fork (https://github.com/kejonaMC/Floodgate) and run the server with flag "-DForceGeyserFormsForNLogin".
[07:34:07] [main/INFO]: Enabled plugin nLogin version 10.2.53 by NickUC
[07:34:07] [main/INFO] [nAntiBot]: Successful plugin core start (took 0.11s)
[07:34:07] [main/INFO]:           _         _   _   ___       _   
[07:34:07] [main/INFO]:   _ __   /_\  _ __ | |_(_) / __\ ___ | |_ 
[07:34:07] [main/INFO]:  | '_ \ //_\\| '_ \| __| |/__\/// _ \| __|
[07:34:07] [main/INFO]:  | | | /  _  \ | | | |_| / \/  \ (_) | |_ 
[07:34:07] [main/INFO]:  |_| |_\_/ \_/_| |_|\__|_\_____/\___/ \__|
[07:34:07] [main/INFO]:                                          
[07:34:07] [main/INFO]:  By: www.nickuc.com - V 6.1.19 DEVELOPMENT
[07:34:07] [main/INFO]: 
[07:34:08] [main/INFO] [nAntiBot]: Connecting to the remote server antibot.nickuc.com...
[07:34:08] [main/INFO]: Enabled plugin nAntiBot version 6.1.19 by NickUC
[07:34:08] [main/INFO]: Enabled plugin Geyser-BungeeCord version 2.2.2-SNAPSHOT by GeyserMC
[07:34:09] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: ******************************************
[07:34:09] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: 
[07:34:09] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: 加载 Geyser 中, 版本 2.2.2-SNAPSHOT (git-master-f8e6d26)
[07:34:09] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: 
[07:34:09] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: ******************************************
[07:34:10] [pool-8-thread-4/INFO] [nAntiBot]: [Captcha] Captchas generated successfully. (RAM usage ? 7.9 MB [static only], total = 500, protocol count = 42, threads = 4, took 2.31s)
[07:34:10] [main/WARN] [GeyserSkinManager-BungeeCord]: ForceShowSkins active through config; Floodgate check is bypassed!
[07:34:10] [main/INFO]: Enabled plugin GeyserSkinManager-BungeeCord version 1.7 by Camotoy
[07:34:10] [main/INFO] [FallBackServer]: 
  _____     _ _ _                _     ____                           
 |  ___|_ _| | | |__   __ _  ___| | __/ ___|  ___ _ ____   _____ _ __ 
 | |_ / _` | | | '_ \ / _` |/ __| |/ /\___ \ / _ \ '__\ \ / / _ \ '__|
 |  _| (_| | | | |_) | (_| | (__|   <  ___) |  __/ |   \ V /  __/ |   
 |_|  \__,_|_|_|_.__/ \__,_|\___|_|\_\|____/ \___|_|    \_/ \___|_|   
                                                                      
[07:34:10] [main/INFO] [FallBackServer]: [!] Starting all listeners..
[07:34:10] [main/INFO] [FallBackServer]: [!] Using default method
[07:34:10] [main/INFO] [FallBackServer]: [!] Preparing commands..
[07:34:10] [main/INFO] [FallBackServer]: [!] Starting telemetry service...
[07:34:10] [main/INFO] [FallBackServer]: [!] Plugin loaded successfully
[07:34:10] [main/WARN] [FallBackServer]:  
[07:34:10] [main/WARN] [FallBackServer]: You're running a BETA VERSION of the plugin.
[07:34:10] [main/WARN] [FallBackServer]: Updater is disabled for debugging purposes.
[07:34:10] [main/WARN] [FallBackServer]: If you find any bugs, please report them on discord.
[07:34:10] [main/WARN] [FallBackServer]:  
[07:34:10] [main/INFO]: Enabled plugin FallBackServer version 3.2.0-Beta2 by CandiesJar
[07:34:10] [main/INFO] [MiraiMC]: Preparing MiraiMC post-load.
[07:34:10] [main/INFO] [MiraiMC]: Initializing SQLite database.
[07:34:10] [main/INFO] [MiraiMC]: Verifying sqlite-jdbc-3.36.0.3.jar
[07:34:10] [main/INFO] [MiraiMC]: Loading library plugins\MiraiMC\libraries\sqlite-jdbc-3.36.0.3.jar
[07:34:10] [main/INFO] [me.dreamvoid.miraimc.libraries.com.zaxxer.hikari.HikariDataSource]: MiraiMC-SQLite - Starting...
[07:34:10] [main/INFO] [me.dreamvoid.miraimc.libraries.com.zaxxer.hikari.HikariDataSource]: MiraiMC-SQLite - Start completed.
[07:34:10] [main/INFO] [MiraiMC]: Starting Mirai-Event listener.
[07:34:10] [main/INFO] [MiraiMC]: Starting Auto-Login bot.
[07:34:10] [main/WARN] [MiraiMC]: 确保您正在使用开源的 MiraiMC 插件，未知来源的插件可能会盗取您的账号！
[07:34:10] [main/WARN] [MiraiMC]: 请始终从 GitHub 或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[07:34:10] [main/INFO] [MiraiMC]: Some initialization tasks will continue to run afterwards.
[07:34:10] [main/INFO] [MiraiMC]: Post-load tasks finished. Welcome to use MiraiMC!
[07:34:10] [main/INFO] [MiraiMC]: Registering commands.
[07:34:10] [main/INFO] [MiraiMC]: Registering events.
[07:34:10] [MiraiMC Pool Thread #0/INFO] [MiraiMC-AutoLogin]: Starting auto login task.
[07:34:10] [main/INFO] [MiraiMC]: Initializing HttpAPI async task.
[07:34:10] [main/INFO]: Enabled plugin MiraiMC version dev-210 by DreamVoid
[07:34:10] [main/INFO]: Enabled plugin PlugManBungee version 2.3.7 by null
[07:34:10] [main/INFO]: Enabled plugin cmd_server version git:cmd_server:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:10] [main/INFO]: Enabled plugin cmd_send version git:cmd_send:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:10] [MiraiMC Pool Thread #0/WARN] [MiraiMC-AutoLogin]: 读取自动登录文件时发现未知的协议类型，请修改: 
[07:34:10] [main/INFO]: Enabled plugin Chat2QQ version 1.6 by DreamVoid
[07:34:10] [main/INFO]: Enabled plugin floodgate version 2.2.2-SNAPSHOT (b20-987d918) by GeyserMC
[07:34:11] [main/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mEnforcing default permissions plugin-side due to platform limitations.[0;39m
[07:34:11] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: Registered 547 custom items
[07:34:11] [main/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mFloodgate skin listener registered[0;39m
[07:34:11] [main/INFO]: Enabled plugin SkinsRestorer version 15.0.7 by knat, AlexProgrammerDE, Th3Tr0LLeR, McLive, DoNotSpamPls
[07:34:11] [main/INFO]: Enabled plugin BungeeGuard version 1.3-SNAPSHOT by Luck
[07:34:11] [main/INFO]: Enabled plugin BungeePackFix version 1.1.6-beta-1 by LoneDev
[07:34:11] [main/INFO]: Enabled plugin cmd_list version git:cmd_list:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:11] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: Registered 1464 custom skulls as custom blocks.
[07:34:11] [main/INFO]: [InteractiveChat] Registered Plugin Messaging Channels!
[07:34:11] [main/INFO]: [InteractiveChat] InteractiveChat (Bungeecord) has been enabled!
[07:34:11] [main/INFO]: Enabled plugin InteractiveChatBungee version 4.2.9.0 by LOOHP
[07:34:11] [main/INFO]: Enabled plugin cmd_find version git:cmd_find:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    +==================+[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    |   SkinsRestorer  |[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    +==================+[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[36;1m    Version: [32;1m15.0.7[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[36;1m    Commit: [32;1m301d078[0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m    This is the latest version![0;39m
[07:34:11] [SkinsRestorer Pool Thread #1/INFO]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[32;1m----------------------------------------------[0;39m
[07:34:12] [main/INFO] [TAB]: Enabled in 550ms
[07:34:12] [main/INFO]: Enabled plugin TAB version 4.1.2 by NEZNAMY
[07:34:12] [main/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[07:34:12] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: Registered 1464 custom blocks.
[07:34:12] [main/INFO] [com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Start completed.
[07:34:12] [main/INFO] [FriendSystem]: [FriendSystem] Plugin enabled!
[07:34:12] [main/INFO]: Enabled plugin FriendSystem version 3.9 by sk8ingDuck
[07:34:12] [main/INFO]: Enabled plugin cmd_alert version git:cmd_alert:1.20-R0.3-SNAPSHOT:e07197d:564 by WaterfallMC
[07:34:12] [main/INFO] [Mesagisto]: Mesagisto信使启用成功
[07:34:12] [main/INFO]: Enabled plugin Mesagisto version 1.0.0-rc by null
[07:34:12] [main/INFO]: Enabled plugin BungeeTp version 1.0.2 by SavageAvocado
[07:34:12] [Netty Boss IO Thread #0/INFO]: Listening on /0.0.0.0:1247
[07:34:12] [DefaultDispatcher-worker-2/INFO] [Mesagisto]: Connecting to websocket mesagisto wss://mesagisto.itsusinn.site
[07:34:12] [pool-5-thread-1/WARN] [floodgate]: 
**********************************
* The prefix you entered in your Floodgate config (BE.) is long! (3 characters)
* A prefix is there to prevent username conflicts. However, a long prefix makes the chance of username conflicts higher.
* We strongly recommend using . as the prefix, but other alternatives that will not conflict include: +, - and *
**********************************
[07:34:13] [DefaultDispatcher-worker-2/INFO] [Mesagisto]: Successfully connected to mesagisto
[07:34:13] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: ========== [ MiraiMC 公告版 ] ==========
[07:34:13] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: MCBBS已死，不知道各位服主有什么质量高的宣传途径
[07:34:13] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: 欢迎来 GitHub 讨论页讨论：
[07:34:13] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: https://github.com/DreamVoid/MiraiMC/discussions
[07:34:13] [MiraiMC Pool Thread #1/INFO] [MiraiMC]: =======================================
[07:34:13] [FriendSystem Pool Thread #0/INFO] [FriendSystem]: [FriendSystem] Plugin is up-to-date! (Version: 3.9)
[07:34:15] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: Reusing cached player skull resource pack.
[07:34:15] [Geyser-BungeeCord Pool Thread #0/WARN] [Geyser-BungeeCord]: The resource pack Slimefun.mcpack has a file in it that meets or exceeds 80 characters in its path (textures/items/jardin_exotico/comida/bbq_double_bacon_wrapped_hot_dog_in_a_tortilla_with_cheese.png, 99 characters long). This will cause problems on some Bedrock platforms. Please rename it to be shorter, or reduce the amount of folders needed to get to the file.
[07:34:15] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: Geyser正在启动 0.0.0.0:3399
[07:34:15] [Geyser-BungeeCord Pool Thread #0/INFO] [Geyser-BungeeCord]: 完成 (6.604s)! 执行/geyser help 来获取帮助信息!
[07:34:18] [Netty Worker IO Thread #2/INFO]: [/182.91.41.127:15096] <-> InitialHandler has connected
[07:34:18] [Netty Worker IO Thread #2/INFO]: [ldbdhj|/182.91.41.127:15096] <-> ServerConnector [lobby] has connected
[07:34:40] [main/INFO]: This server is running MiraiMC version dev-210 by DreamVoid
[07:35:00] [MiraiMC Pool Thread #1/INFO]: 2534002574 HTTP-API登录成功！
[07:35:17] [main/INFO]: 发送好友消息时出现异常，状态码: 400，原因: Illegal input
[07:43:23 INFO]: 已发送QQ群聊天消息！
[07:43:23 WARN] [Chat2QQ]: 使用2534002574发送消息时出现异常，原因: me.dreamvoid.miraimc.httpapi.exception.AbnormalStatusException: Illegal input
> mirai sendfriendnudge 2534002574 1301727735
[07:44:33 INFO]: An internal error occurred whilst executing this command, please check the console log for details.
[07:44:33 WARN]: Error in dispatching command
java.util.NoSuchElementException: 2534002574
        at net.mamoe.mirai.Bot$Companion.getInstance(Bot.kt:215) ~[?:?]
        at net.mamoe.mirai.Bot.getInstance(Bot.kt) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.<init>(MiraiBot.java:48) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.getBot(MiraiBot.java:76) ~[?:?]
        at me.dreamvoid.miraimc.commands.MiraiCommand.onCommand(MiraiCommand.java:170) ~[?:?]
        at me.dreamvoid.miraimc.bungee.BungeePlugin$1.execute(BungeePlugin.java:54) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:213) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.api.plugin.PluginManager.dispatchCommand(PluginManager.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at io.github.waterfallmc.waterfall.console.WaterfallConsole.runCommand(WaterfallConsole.java:30) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.processInput(SimpleTerminalConsole.java:87) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:168) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:141) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:72) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall.jar:git:Waterfall-Bootstrap:1.20-R0.3-SNAPSHOT:e07197d:564]
```

### 额外说明

使用Windows Server 2022
Java版本zulu17.48.15-ca-jdk17.0.10-win_x64
更换miraimc版本后无法解决问题
MCL登录使用8.9.96协议版本
接收群消息时显示null
[07:38:58 INFO] [MiraiMC]: [GroupMessage/2534002574] [暮舟极光(730502518)] sky40727(2516313034) -> null
[07:40:16 INFO] [MiraiMC]: [GroupMessage/2534002574] [暮舟极光(730502518)] ldbdhj(2278700243) -> null

### 协议

- [X] 我已查阅[常见问题疑难解答](https://docs.miraimc.dreamvoid.me/troubleshoot/faq)和 [issue 列表](https://github.com/DreamVoid/MiraiMC/issues?q=is%3Aissue+-label%3A%E6%97%A0%E6%95%88+-label%3A%E9%87%8D%E5%A4%8D)，并确认我的问题不在其中。
- [X] 我确认我已认真阅读所有注意事项并认真填写表单。
- [ ] 我确认我没有看这些选择框就随便勾选了。
- [X] 我明白，如果没有正确填写 issue 模板的内容，本 issue 将会直接被关闭并被锁定。
- [X] 我明白，如果滥用 issue 功能，我将会被列入黑名单。

**Comment by DreamVoid** [comment]
再也没有HTTP API了
