### ISSUE TITLE
LoliServer 无法正常使用插件

### ISSUE THREAD

**Issue by LittleHed** [DreamVoid/MiraiMC#50]
**问题描述**

同ip下的子服不能登录同一个qq，我Airplane-1.17.1端测试可以正常使用申请白名单，但是同一个机子下的loliserver端就不行

**复现方法**

1. https://www.mcbbs.net/thread-1191446-1-3.html 下载loliserver最新构建（1.16.5版本）
2. 启动服务器，加载完成后关闭并加入Whitelist4QQ,MiraiMC,Chat2QQ
3. 绑定自动登录的QQ账号
4. 重启服务器
5. 经过测试，三种协议均是相同报错

**版本类型**

* Minecraft 服务端版本：[loliserver-1.16.5]
* MiraiMC 插件版本：[v1.5]

**截图**

无
**服务器日志**

```
[00:18:27][Server thread][INFO]: [MiraiMC] Enabling MiraiMC v1.5
[00:18:27][Server thread][INFO]: [MiraiMC] Mirai working dir: default
[00:18:27][Server thread][INFO]: [MiraiMC] Starting Mirai-Events listener.
[00:18:27][Server thread][INFO]: [MiraiMC] Loading auto-login file.
[00:18:27][Server thread][INFO]: [MiraiMC] Registering commands.
[00:18:27][Server thread][INFO]: [MiraiMC] Registering events.
[00:18:27][Server thread][INFO]: [MiraiMC] Initializing SQLite database.
[00:18:27][Server thread][WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[00:18:27][Server thread][WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[00:18:27][Server thread][INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[00:18:27][Server thread][INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.1.6
[00:18:28][Server thread][INFO]: [SkinsRestorer] Using SpigotSkinRefresher
[00:18:28][Server thread][INFO]: [SkinsRestorer] Detected Minecraft v1_16_R3, using SpigotSkinRefresher.
>
>
>
[00:18:36][Server thread][INFO]: [Whitelist4QQ] Enabling Whitelist4QQ v1.0
[00:18:36][Server thread][INFO]: [Essentials] Enabling Essentials v2.19.0
[00:18:36][Server thread][ERROR]: [Essentials] You are running a server that does not properly support Bukkit plugins. Bukkit plugins should not be used with Forge/Fabric mods! For Forge: Consider using ForgeEssentials, or SpongeForge + Nucleus.
[00:18:36][Server thread][INFO]: [Essentials] Status determining class: net.minecraftforge.common.MinecraftForge
[00:18:37][Server thread][INFO]: Attempting to convert old kits in config.yml to new kits.yml
[00:18:37][Server thread][INFO]: No kits found to migrate.
[00:18:38][Server thread][INFO]: Loaded 853 items from items.csv.
[00:18:38][Server thread][INFO]: Using locale en_US
[00:18:38][Server thread][INFO]: [Essentials] ServerListPingEvent: Spigot iterator API
[00:18:38][Server thread][INFO]: [Essentials] Metrics disabled per bStats config.
[00:18:38][Server thread][WARN]: [Essentials] Detected supported permissions plugin LuckPerms without Vault installed.
[00:18:38][Server thread][WARN]: [Essentials] Features such as chat prefixes/suffixes and group-related functionality will not work until you install Vault.
[00:18:38][Server thread][INFO]: [Essentials] Using superperms-based permissions.
[00:18:38][Server thread][INFO]: [AdvancedCleaner] Enabling AdvancedCleaner v1.3
[00:18:38][Server thread][WARN]: [AdvancedCleaner] Failed to load entity limit, entity type not found: PIG_ZOMBIE
[00:18:38][Server thread][WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[00:18:38][Server thread][INFO]: [PlaceholderAPI] Enabling PlaceholderAPI v2.10.10
[00:18:39][Server thread][INFO]: [PlaceholderAPI] Fetching available expansion information...
[00:18:39][Server thread][INFO]: [MiraiMC] Enabling Chat2QQ v1.4.1
[00:18:39][Server thread][INFO]: [MiaoBoard] Enabling MiaoBoard v2.5.1-git-3f193bbf460541fb71a29af94bca98f8317e2ea7
[00:18:39][Server thread][INFO]: [CatSeedLogin] Enabling CatSeedLogin v1.3.8-SNAPSHOT
[00:18:39][Server thread][WARN]: [CatSeedLogin] 服务器没有装载ProtocolLib插件，这将无法使用登录前隐藏背包
[00:18:39][Server thread][INFO]: [Boom] Enabling Boom v1.2.5
[00:18:39][Server thread][INFO]: [Boom] 防爆插件1.2.5已启用 作者404E
[00:18:39][Server thread][INFO]: Server permissions file permissions.yml is empty, ignoring it
[00:18:39][Server thread][INFO]: [PlaceholderAPI] Placeholder expansion registration initializing...
[00:18:39][Server thread][INFO]: Preparing start region for dimension minecraft:overworld
[00:18:40][Server thread][INFO]: Preparing spawn area: 0%
[00:18:41][Worker-Main-12][INFO]: Preparing spawn area: 83%
[00:18:43][Server thread][INFO]: Preparing spawn area: 84%
[00:18:44][Worker-Main-10][INFO]: Preparing spawn area: 86%
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=30} Block{create:fluid_pipe}
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=30} Block{create:fluid_pipe}
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=29} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=29} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=30} Block{create:fluid_pipe}
[00:18:44][Worker-Main-13][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=37, z=29} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-12][INFO]: Preparing spawn area: 89%
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=94, y=18, z=-158} Block{create:fluid_pipe}
[00:18:44][Worker-Main-11][WARN]: Tried to access a block entity before it was created. BlockPos{x=93, y=18, z=-158} Block{create:encased_fluid_pipe}
[00:18:45][Server thread][INFO]: Preparing spawn area: 95%
[00:18:45][Server thread][INFO]: Done (18.862s)! For help, type "help"
[00:18:45][Server thread][INFO]: Strawgolem: Server Starting
[00:18:45][Server thread][INFO]: HELLO from NoLakes Forge!
[00:18:45][Server thread][INFO]: Loading quests from D:\BaiduNetdiskDownload\新建文件夹\MCSManager_8.6.23_Win64\server\server_core\机械动力：超越极致\config\ftbquests\quests
[00:18:45][Server thread][INFO]: Loaded 3 chapter groups, 13 chapters, 450 quests, 0 reward tables
[00:18:45][Craft Scheduler Thread - 5][INFO]: [Essentials] Fetching version information...
[00:18:45][Craft Scheduler Thread - 0][INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[00:18:45][Craft Scheduler Thread - 11][INFO]: [CatSeedLogin] 缓存加载 18 个数据
[00:18:45][Craft Scheduler Thread - 0][INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 3317251311 Protocol: ANDROID_WATCH
[00:18:45][Server thread][INFO]: [PlaceholderAPI] Successfully registered expansion: server
[00:18:45][Server thread][INFO]: 1 placeholder hooks successfully registered!
[00:18:45][Craft Scheduler Thread - 0][INFO]: [MiraiMC] 登录新的机器人账号: 3317251311, 协议: ANDROID_WATCH
[00:18:46][Thread-23][WARN]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/EssentialsX/Essentials/releases/latest
[00:18:46][Thread-23][WARN]:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[00:18:46][Thread-23][WARN]:    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[00:18:46][Thread-23][WARN]:    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[00:18:46][Thread-23][WARN]:    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
[00:18:46][Thread-23][WARN]:    at java.base/java.security.AccessController.doPrivileged(Native Method)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
[00:18:46][Thread-23][WARN]:    at com.earth2me.essentials.updatecheck.UpdateChecker.lambda$fetchLatestRelease$1(UpdateChecker.java:106)
[00:18:46][Thread-23][WARN]:    at java.base/java.lang.Thread.run(Thread.java:829)
[00:18:46][Thread-23][WARN]: Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/EssentialsX/Essentials/releases/latest
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
[00:18:46][Thread-23][WARN]:    at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
[00:18:46][Thread-23][WARN]:    at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
[00:18:46][Thread-23][WARN]:    at com.earth2me.essentials.updatecheck.UpdateChecker.lambda$fetchLatestRelease$1(UpdateChecker.java:95)
[00:18:46][Thread-23][WARN]:    ... 1 more
[00:18:46][Craft Scheduler Thread - 5][WARN]: [Essentials] Error while fetching EssentialsX version information! Build information: id:'2.19.0' branch:'2.x' isDev:false.
[00:18:46][Craft Scheduler Thread - 0][WARN]: [MiraiMC] Plugin MiraiMC v1.5 generated an exception while executing task 7
 kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath
        at kotlin.jvm.internal.ClassReference.error(ClassReference.kt:84) ~[improvedbackpacks:1.6.2.0]
        at kotlin.jvm.internal.ClassReference.getNestedClasses(ClassReference.kt:24) ~[improvedbackpacks:1.6.2.0]
        at kotlin.reflect.full.KClasses.getCompanionObject(KClasses.kt:51) ~[?:?]
        at kotlin.reflect.full.KClasses.getCompanionObjectInstance(KClasses.kt:61) ~[?:?]
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:352) ~[?:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43) ~[?:?]
        at net.mamoe.mirai.internal.MiraiImpl.<clinit>(MiraiImpl.kt:77) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:398) ~[?:?]
        at moe.loliserver.remapper.proxy.ProxyReflection.forName(ProxyReflection.java:39) ~[forge:?]
        at moe.loliserver.remapper.proxy.ProxyReflection.forName(ProxyReflection.java:17) ~[forge:?]
        at net.mamoe.mirai.FindMiraiInstanceKt.findMiraiInstance(findMiraiInstance.kt:18) ~[?:?]
        at net.mamoe.mirai._MiraiInstance.get(IMirai.kt:352) ~[?:?]
        at net.mamoe.mirai.Mirai.getInstance(IMirai.kt:43) ~[?:?]
        at net.mamoe.mirai.BotFactory$INSTANCE.newBot(BotFactory.kt:119) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:213) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
        at me.dreamvoid.miraimc.bukkit.MiraiAutoLogin.lambda$doStartUpAutoLogin$0(MiraiAutoLogin.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:81) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [forge:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]
```

**额外说明**

**Comment by DreamVoid** [comment]
我不推荐使用任何基于Catserver的分支，因为作者的人品很差
请依次尝试以下解决方案
* 请尝试关闭Loliserver配置中任何能remap的配置，然后重试
* 更换为Mohist

**Comment by LittleHed** [comment]
> 我不推荐使用任何基于Catserver的分支，因为作者的人品很差 请依次尝试以下解决方案
> 
> * 请尝试关闭Loliserver配置中任何能remap的配置，然后重试
> * 更换为Mohist

很遗憾，经过测试墨端不支持我正在使用的模组整合包..
Loli-Update:
  check-update: false
LoliServer:
  check_libraries: true
  forge_ignore_optional_mods_version_check: false
  chunk_unload_delay: 5
  optimize_explosions: true
  prevent_from_entering_unloaded_chunks: true
  ignore_empty_time: all_worlds
  disable_packet_debug: true
  allow_sand_duping: false
请问一下这哪些选项和remap相关的，我试着关一下。。

**Comment by DreamVoid** [comment]
请按照以下步骤操作：
1. 使用干净启动Loliserver（除了MiraiMC和MiraiMC的附属插件不安装任何其他插件，服务端配置为默认）
2. 完整记录服务端输出的所有日志
3. 日志内容回复此 issue

**Comment by LittleHed** [comment]
经过测试是模组导致的问题，干净启动可以正常使用
