### ISSUE TITLE
开服过程中报错

### ISSUE THREAD

**Issue by Radiation-pi** [DreamVoid/MiraiMC#61]
**问题描述**

1.5.1版本开服过程中多次报错，但基本功能能够使用

**复现方法**

1. 未知

**版本类型**

* Minecraft 服务端版本：paper-1.16.5
* MiraiMC 插件版本：1.5.1

**截图**

**服务器日志**

```
[13:07:12] [Server thread/INFO]: [MiraiMC] Loading MiraiMC v1.5.1
[13:07:12] [Server thread/ERROR]: Cannot load plugins\MiraiMC\config.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 43, column 21:
            check-update: true
                        ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:59) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:188) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPlugin.reloadConfig(JavaPlugin.java:157) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.plugin.java.JavaPlugin.getConfig(JavaPlugin.java:133) ~[patched_1.16.5.jar:git-Paper-790]
	at me.dreamvoid.miraimc.bukkit.BukkitConfig.loadConfig(BukkitConfig.java:18) ~[?:?]
	at me.dreamvoid.miraimc.bukkit.BukkitPlugin.onLoad(BukkitPlugin.java:27) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-790]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-790]
	at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 43, column 21:
            check-update: true
                        ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:869) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:235) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:257) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:248) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:236) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:162) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:95) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:119) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:150) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490) ~[patched_1.16.5.jar:git-Paper-790]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:416) ~[patched_1.16.5.jar:git-Paper-790]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:57) ~[patched_1.16.5.jar:git-Paper-790]
	... 12 more
[13:07:13] [Server thread/INFO]: [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
[13:07:13] [Server thread/INFO]: [MiraiMC] Verifying mirai-core-all-2.9.0-RC.jar
[13:07:13] [Server thread/INFO]: [MiraiMC] Downloading https://repo1.maven.org/maven2/net/mamoe/mirai-core-all/2.9.0-RC/mirai-core-all-2.9.0-RC-all.jar
[13:07:17] [Server thread/INFO]: [MiraiMC] Loading library mirai-core-all-2.9.0-RC.jar
[13:07:17] [Server thread/INFO]: [spark] Loading spark v1.6.2
[13:07:17] [Server thread/INFO]: [MiraiMC] Loading Chat2QQ v1.4.1
[13:07:17] [Server thread/INFO]: [Languagy] Loading Languagy v2.0.3
[13:07:17] [Server thread/INFO]: [LoginManager] Loading LoginManager v1.34
[13:07:17] [Server thread/INFO]: [DropSpawner] Loading DropSpawner v1.0.3
[13:07:17] [Server thread/INFO]: [CatSeedLogin] Loading CatSeedLogin v1.3.5-SNAPSHOT
[13:07:17] [Server thread/INFO]: [MapPicture] Loading MapPicture v1.0.0
[13:07:17] [Server thread/INFO]: [EasyWhitelist] Loading EasyWhitelist v1.0.1
[13:07:17] [Server thread/INFO]: [mcMMO] Loading mcMMO v2.1.196
[13:07:17] [Server thread/INFO]: [ViaVersion] Loading ViaVersion v4.1.1
[13:07:17] [Server thread/INFO]: [ViaVersion] ViaVersion 4.1.1 is now loaded, injecting!
[13:07:17] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading 1.12 -> 1.13 mappings...
[13:07:17] [Server thread/INFO]: [Vault] Loading Vault v1.7.2-b107
[13:07:17] [Server thread/INFO]: [BottledExp] Loading BottledExp v2.2.8.2
[13:07:17] [Server thread/INFO]: [dynmap] Loading dynmap v3.1-beta6-438
[13:07:17] [Server thread/INFO]: [dynmap] version=git-Paper-790 (MC: 1.16.5)
[13:07:17] [Via-Mappingloader-1/INFO]: [ViaVersion] Loading 1.13 -> 1.13.2 mappings...
[13:07:17] [Via-Mappingloader-2/INFO]: [ViaVersion] Loading 1.13.2 -> 1.14 mappings...
[13:07:17] [Via-Mappingloader-3/INFO]: [ViaVersion] Loading 1.14 -> 1.15 mappings...
[13:07:17] [Via-Mappingloader-4/INFO]: [ViaVersion] Loading 1.15 -> 1.16 mappings...
[13:07:17] [Via-Mappingloader-5/INFO]: [ViaVersion] Loading 1.16 -> 1.16.2 mappings...
[13:07:17] [Via-Mappingloader-6/INFO]: [ViaVersion] Loading 1.16.2 -> 1.17 mappings...
[13:07:17] [Via-Mappingloader-7/INFO]: [ViaVersion] Loading 1.17 -> 1.18 mappings...
[13:07:17] [Server thread/INFO]: [dynmap] Mod Support API available
[13:07:17] [Server thread/INFO]: [Towny] Loading Towny v0.97.0.0
[13:07:17] [Server thread/INFO]: [WorldBorder] Loading WorldBorder v1.9.10 (beta)
[13:07:17] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b501
[13:07:19] [Via-Mappingloader-0/INFO]: [ViaVersion] Loading block connection mappings ...
[13:07:19] [Server thread/INFO]: [TownyChat] Loading TownyChat v0.88
[13:07:19] [Server thread/INFO]: [AncientGates] Loading AncientGates v2.4
[13:07:19] [Server thread/INFO]: [TAB] Loading TAB v2.8.10
[13:07:23] [Server thread/WARN]: **** SERVER IS RUNNING IN OFFLINE/INSECURE MODE!
[13:07:23] [Server thread/WARN]: The server will make no attempt to authenticate usernames. Beware.
[13:07:23] [Server thread/WARN]: Whilst this makes it possible to use BungeeCord, unless access to your server is properly restricted, it also opens up the ability for hackers to connect with any username they choose.
[13:07:23] [Server thread/WARN]: Please see http://www.spigotmc.org/wiki/firewall-guide/ for further information.
[13:07:23] [Server thread/WARN]: To change this, set "online-mode" to "true" in the server.properties file.
[13:07:23] [Server thread/INFO]: Preparing level "world"
[13:07:23] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Preparing spawn area: 0%
[13:07:27] [Server thread/INFO]: Time elapsed: 3403 ms
[13:07:27] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[13:07:29] [Server thread/INFO]: Time elapsed: 2548 ms
[13:07:29] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[13:07:29] [Server thread/INFO]: Time elapsed: 75 ms
[13:07:29] [Server thread/INFO]: [PlugMan] Enabling PlugMan v2.1.7
[13:07:29] [Server thread/INFO]: [MiraiMC] Enabling MiraiMC v1.5.1
[13:07:29] [Server thread/INFO]: [MiraiMC] Mirai working dir: default
[13:07:29] [Server thread/INFO]: [MiraiMC] Starting Mirai-Events listener.
[13:07:30] [Server thread/INFO]: [MiraiMC] Loading auto-login file.
[13:07:30] [Server thread/INFO]: [MiraiMC] Registering commands.
[13:07:30] [Server thread/INFO]: [MiraiMC] Registering events.
[13:07:30] [Server thread/INFO]: [MiraiMC] Initializing SQLite database.
[13:07:30] [Server thread/INFO]: [MiraiMC] Initializing bStats metrics.
[13:07:30] [Server thread/WARN]: [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
[13:07:30] [Server thread/WARN]: [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
[13:07:30] [Server thread/INFO]: [MiraiMC] All tasks done. Welcome to use MiraiMC!
[13:07:30] [Server thread/INFO]: [spark] Enabling spark v1.6.2
[13:07:30] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[13:07:30] [Server thread/INFO]: [PlaceholderAPI] Successfully registered expansion: spark
[13:07:30] [Server thread/INFO]: [spark] Registered PlaceholderAPI placeholders
[13:07:30] [Server thread/INFO]: [MiraiMC] Enabling Chat2QQ v1.4.1
[13:07:43] [Craft Scheduler Thread - 5/INFO]: [MiraiMC] [AutoLogin] Starting auto login task.
[13:07:43] [Craft Scheduler Thread - 25/INFO]: [Vault] Checking for Updates ... 
[13:07:43] [Craft Scheduler Thread - 5/INFO]: [MiraiMC] [AutoLogin] Auto login bot account: 2767139663 Protocol: ANDROID_PAD
[13:07:43] [Craft Scheduler Thread - 15/INFO]: [InteractiveChat] Loading languages...
[13:07:43] [Craft Scheduler Thread - 8/INFO]: [CatSeedLogin] 缓存加载 202 个数据
[13:07:44] [Craft Scheduler Thread - 5/INFO]: [MiraiMC] 登录新的机器人账号: xxxxxxx, 协议: ANDROID_PAD
[13:07:44] [Craft Scheduler Thread - 6/INFO]: [MiraiMC] Checking update...
[13:07:44] [Craft Scheduler Thread - 6/INFO]: [MiraiMC] You are using the latest version!
[13:07:44] [Craft Scheduler Thread - 14/INFO]: [AncientGates] Update Available: 2.5.1
[13:07:44] [Craft Scheduler Thread - 14/INFO]: [AncientGates] Spigot Link: https://www.spigotmc.org/resources/ancient-gates.6583/
[13:07:45] [Craft Scheduler Thread - 25/WARN]: [Vault] Stable Version: 1.7.3 is out! You are still running version: 1.7.2
[13:07:45] [Craft Scheduler Thread - 25/WARN]: [Vault] Update at: https://dev.bukkit.org/projects/vault
[13:07:46] [Craft Scheduler Thread - 23/INFO]: Initialized items.yml
[13:07:47] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Server list: 14.22.9.53:443, 183.47.98.105:8080, 49.7.253.214:443, 101.91.40.21:80, 183.47.98.25:14000, 114.222.112.229:443, 49.7.253.45:80, 42.81.192.181:443, 101.91.37.175:8080, msfwifi.3g.qq.com:8080.
[13:07:48] [DefaultDispatcher-worker-2/WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:130)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:238)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:168)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:163)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/C:/Users/Administrator/Desktop/server/main/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.9.0-RC.jar is not signed.
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:463)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:316)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:259)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:129)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:189)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:217)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:127)
[13:07:48] [DefaultDispatcher-worker-2/WARN]: 	... 39 more
[13:07:48] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Loaded account secrets from local cache.
[13:07:48] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] ECDH key is valid.
[13:07:48] [DefaultDispatcher-worker-2/INFO]: [MiraiMC] Saved account secrets to local cache for fast login.
```

**额外说明**

设置里即使关掉mirai的记录，还是会在控制台看到qq群的聊天消息，后台可读性差
本人技术力低下，属于暂时为好友代理服主，不知道是设置问题还是和其他插件冲突，望大佬能给予帮助
不胜感激！

**Comment by DreamVoid** [comment]
你配置改炸了，备份配置文件然后删掉，重新生成新的配置文件以后再改

**Comment by Radiation-pi** [comment]
感谢！
