### ISSUE TITLE
Mohist 1.12.2 机器人无法登录问题

### ISSUE THREAD

**Issue by nkqt** [DreamVoid/MiraiMC#68]
**版本类型**

* Minecraft 服务端版本：mohist1.12.2
* MiraiMC 插件版本：1.5.2

**截图**
![QQ图片20211221161215](https://user-images.githubusercontent.com/96467698/146895128-3328e523-23bf-422d-9256-ada6018afc66.png)

**服务器日志**
[14:52:55 INFO]: 正在启用 QQConnect v3.1-SNAPSHOT
[14:52:55 INFO]: [QQConnect] ────────────────────────
[14:52:55 INFO]: [QQConnect] 插件 QQConnect 已完成加载
[14:52:55 INFO]: [QQConnect] 作者: 郁冬Yyc
[14:52:55 INFO]: [QQConnect] ────────────────────────
[14:52:55 INFO]: [QQConnect] 机器人 3534094246 正在登录中...
[14:52:55 INFO]: [MiraiMC] 登录新的机器人账号: 3534094246, 协议: ANDROID_PHONE
[14:52:55 ERROR]: 启用 QQConnect v3.1-SNAPSHOT 时发生错误 (它是最新的吗？)
 java.lang.NoClassDefFoundError: Could not initialize class kotlinx.serialization.json.Json
        at kotlinx.serialization.json.JsonKt.Json$default(Json.kt:135) ~[?:?]
        at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:72) ~[?:?]
        at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:624) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:213) ~[?:?]
        at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
        at org.yycstudio.qqconnect.bot.Bot.initBot(Bot.java:23) ~[?:?]
        at org.yycstudio.qqconnect.QQConnect.onEnable(QQConnect.java:38) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:177) ~[JavaPlugin.class:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:318) [JavaPluginLoader.class:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:399) [SimplePluginManager.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:477) [CraftServer.class:?]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:418) [CraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:383) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:315) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:590) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by DreamVoid** [comment]
请尝试手动执行命令 ```/mirai login <账号> <密码>``` 检查问题是否存在，如不存在，请上报对应插件作者。
