### ISSUE TITLE
无需验证账号登录时的问题

### ISSUE THREAD

**Issue by yupenBob** [DreamVoid/MiraiMC#73]
**问题描述**

我在登录我的机器人时出现了问题，我关闭了我的机器人验证，但登录出现了问题

**复现方法**

1. 我就输入了mirai login，登录了我的机器人qq

**版本类型**

* Minecraft 服务端版本：This server is running CraftBukkit version 2991-Spigot-018b9a0-f3f3094 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT) 
* MiraiMC 插件版本：1.5.2  

**截图**

**服务器日志**

```
>mirai login ******* **********
[19:49:50] [Craft Scheduler Thread - 10/INFO]: [MiraiMC] 登录新的机器人账号: ********, 协议: ANDROID_PHONE
[19:49:57] [Craft Scheduler Thread - 10/WARN]: [MiraiMC] Plugin MiraiMC v1.5.2 generated an exception while executing task 4035
java.lang.NoClassDefFoundError: Could not initialize class net.mamoe.mirai.internal.utils.crypto.ECDHKt
        at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.AccountSecretsImpl(AccountSecretsManager.kt:146) ~[?:?]
        at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:154) ~[?:?]
        at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36) ~[?:?]
        at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24) ~[?:?]
        at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28) ~[?:?]        at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28) ~[?:?]        at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38) ~[?:?]
        at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97) ~[?:?]
        at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.logout(SsoProcessor.kt:138) ~[?:?]
        at net.mamoe.mirai.internal.QQAndroidBot$close$1.invokeSuspend(QQAndroidBot.kt:79) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org.kotlinlang-kotlin-stdlib-1.4.20.jar:1.4.20-release-308 (1.4.20)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274) ~[?:?]
        at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source) ~[?:?]
        at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38) ~[?:?]
        at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source) ~[?:?]
        at net.mamoe.mirai.internal.QQAndroidBot.close(QQAndroidBot.kt:77) ~[?:?]
        at net.mamoe.mirai.internal.AbstractBot.login(AbstractBot.kt:136) ~[?:?]
        at net.mamoe.mirai.internal.AbstractBot$login$1.invokeSuspend(AbstractBot.kt) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[org.kotlinlang-kotlin-stdlib-1.4.20.jar:1.4.20-release-308 (1.4.20)]
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178) ~[?:?]
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166) ~[?:?]
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397) ~[?:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431) ~[?:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420) ~[?:?]
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328) ~[?:?]
        at kotlinx.coroutines.ResumeAwaitOnCompletion.invoke(JobSupport.kt:1408) ~[?:?]
        at kotlinx.coroutines.JobSupport.notifyCompletion(JobSupport.kt:1519) ~[?:?]
        at kotlinx.coroutines.JobSupport.completeStateFinalization(JobSupport.kt:323) ~[?:?]
        at kotlinx.coroutines.JobSupport.finalizeFinishingState(JobSupport.kt:240) ~[?:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompletingSlowPath(JobSupport.kt:906) ~[?:?]
        at kotlinx.coroutines.JobSupport.tryMakeCompleting(JobSupport.kt:863) ~[?:?]
        at kotlinx.coroutines.JobSupport.makeCompletingOnce$kotlinx_coroutines_core(JobSupport.kt:828) ~[?:?]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:100) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[org.kotlinlang-kotlin-stdlib-1.4.20.jar:1.4.20-release-308 (1.4.20)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[?:?]
```

**额外说明**

**Comment by DreamVoid** [comment]
尝试在配置文件中修改mirai核心版本为2.8.2，然后重新启动服务器

**Comment by DreamVoid** [comment]
暂作归档处理，有必要可继续回复或开新issue
