### ISSUE TITLE
JCE cannot authenticate the provider BC

### ISSUE THREAD

**Issue by BillZhucn** [DreamVoid/MiraiMC#74]
**问题描述**

开服后出现这样一段WARN

**复现方法**

1. 

**版本类型**

* Minecraft 服务端版本： This server is running Paper version git-Paper-150 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 0c64d40)
* MiraiMC 插件版本： This server is running MiraiMC version 1.5.2 by DreamVoid

**截图**

**服务器日志**

```
[03:49:47 WARN]: java.security.NoSuchProviderException: JCE cannot authenticate the provider BC
[03:49:47 WARN]:        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)
[03:49:47 WARN]:        at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:168)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:163)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.access$createClient(BotClientHolder.kt:24)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
[03:49:47 WARN]:        at MiraiMC-Bukkit.jar//kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
[03:49:47 WARN]: Caused by: java.util.jar.JarException: The JCE Provider file:/C:/Users/Administrator/Desktop/PixelTail_8th/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.9.2.jar is not signed.
[03:49:47 WARN]:        at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)
[03:49:47 WARN]:        at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)
[03:49:47 WARN]:        at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)
[03:49:47 WARN]:        at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)
[03:49:47 WARN]:        at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)
[03:49:47 WARN]:        at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)
[03:49:47 WARN]:        at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)
[03:49:47 WARN]:        ... 39 more
```

**额外说明**

**Comment by DreamVoid** [comment]
请阅读mirai.mamoe.net上的常见问题说明
