### ISSUE TITLE
手动登录QQ账号报错

### ISSUE THREAD

**Issue by Yuii-guoguo** [DreamVoid/MiraiMC#78]
**问题描述**

手动登录账号报错

**复现方法**

1. 使用/mirai login 账号 密码

**版本类型**

* Minecraft 服务端版本：Bungeecord #1628版本
* MiraiMC 插件版本：1.5.3

**截图**

**服务器日志**

```
02:46:42 [严重] Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.

02:46:42 [严重] SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

02:46:42 [严重] SLF4J: Defaulting to no-operation (NOP) logger implementation

02:46:42 [严重] SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

02:46:50 [严重] java.security.NoSuchProviderException: JCE cannot authenticate the provider BC

02:46:50 [严重]     at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:131)

02:46:50 [严重]     at java.base/javax.crypto.KeyAgreement.getInstance(KeyAgreement.java:240)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDH$Companion.calculateShareKey(ECDHJvmDesktop.kt:89)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDH.lambda-3$testECDH(ECDHJvmDesktop.kt:49)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDH.<clinit>(ECDHJvmDesktop.kt:61)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:141)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDHKt.adjustToPublicKey(ECDH.kt:136)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey.<init>(ECDH.kt:125)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.crypto.ECDHInitialPublicKey$$serializer.deserialize(ECDH.kt:122)

02:46:50 [严重]     at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)

02:46:50 [严重]     at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.AccountSecretsImpl$$serializer.deserialize(AccountSecretsManager.kt:80)

02:46:50 [严重]     at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:224)

02:46:50 [严重]     at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:214)

02:46:50 [严重]     at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:137)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs(utils.kt:168)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs(utils.kt:1)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils__UtilsKt.loadAs$default(utils.kt:163)

02:46:50 [严重]     at net.mamoe.mirai.internal.utils.io.serialization.SerializationUtils.loadAs$default(utils.kt:1)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecretsImpl(AccountSecretsManager.kt:198)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.FileCacheAccountSecretsManager.getSecrets(AccountSecretsManager.kt:192)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.CombinedAccountSecretsManager.getSecrets(AccountSecretsManager.kt:240)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.AccountSecretsManagerKt.getSecretsOrCreate(AccountSecretsManager.kt:152)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.createClient(BotClientHolder.kt:36)
02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.BotClientHolderImpl$client$2.invoke(BotClientHolder.kt:28)

02:46:50 [严重]     at net.mamoe.mirai.utils.LateinitMutableProperty.getValue(LateinitMutableProperty.kt:38)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.BotClientHolderImpl.getClient(BotClientHolder.kt:28)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.getClient(SsoProcessor.kt:97)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.components.SsoProcessorImpl.login(SsoProcessor.kt:111)

02:46:50 [严重]     at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$StateConnecting$1.invokeSuspend(NettyNetworkHandler.kt:257)

02:46:50 [严重]     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

02:46:50 [严重]     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)

02:46:50 [严重]     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)

02:46:50 [严重]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)

02:46:50 [严重]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)

02:46:50 [严重]     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

02:46:50 [严重] Caused by: java.util.jar.JarException: The JCE Provider file:/www/BungeeCord/plugins/MiraiMC/MiraiBot/libs/mirai-core-all-2.9.2.jar is not signed.

02:46:50 [严重]     at java.base/javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:464)

02:46:50 [严重]     at java.base/javax.crypto.JarVerifier.verifyJars(JarVerifier.java:317)

02:46:50 [严重]     at java.base/javax.crypto.JarVerifier.verify(JarVerifier.java:260)

02:46:50 [严重]     at java.base/javax.crypto.ProviderVerifier.verify(ProviderVerifier.java:130)

02:46:50 [严重]     at java.base/javax.crypto.JceSecurity.verifyProvider(JceSecurity.java:190)

02:46:50 [严重]     at java.base/javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:218)

02:46:50 [严重]     at java.base/javax.crypto.JceSecurity.getInstance(JceSecurity.java:128)

02:46:50 [严重]     ... 39 more
```

**额外说明**

使用mysql5.7作为数据库,上一个版本也是

**Comment by DreamVoid** [comment]
？你确定复现方法是手动登录机器人？
#74
