### ISSUE TITLE
Bungee无法自动登陆

### ISSUE THREAD

**Issue by Baikele** [DreamVoid/MiraiMC#80]
**问题描述**
在Bungee上自动登陆或者直接登陆会报错

**复现方法**
添加自动登陆或者是手动登陆都可以
**版本类型**
waterfall-1.18-475

**截图**

**服务器日志**

```
[22:34:30 INFO] [MiraiMC]: ECDH key is invalid, start to fetch ecdh public key from server.
[22:34:30 ERROR] [MiraiMC]: Failed to fetch ECDH public key from server, using default key instead
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at io.ktor.utils.io.bits.MemoryJvmKt.sliceSafe(MemoryJvm.kt:211) ~[?:?]
        at io.ktor.utils.io.bits.Memory.slice-SK3TCg8(MemoryJvm.kt:47) ~[?:?]
        at io.ktor.utils.io.charsets.CharsetJVMKt.encodeImpl(CharsetJVM.kt:356) ~[?:?]
        at io.ktor.utils.io.charsets.EncodingKt.encodeToImpl(Encoding.kt:204) ~[?:?]
        at io.ktor.utils.io.charsets.EncodingKt.encode(Encoding.kt:62) ~[?:?]
        at io.ktor.utils.io.charsets.EncodingKt.encode$default(Encoding.kt:57) ~[?:?]
        at io.ktor.http.CodecsKt.encodeURLParameter(Codecs.kt:123) ~[?:?]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:68) ~[?:?]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:67) ~[?:?]
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85) ~[?:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347) ~[?:?]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default(_Collections.kt:3341) ~[?:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:67) ~[?:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:108) ~[?:?]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:90) ~[?:?]
        at io.ktor.http.URLUtilsKt.appendUrlFullPath(URLUtils.kt:101) ~[?:?]
        at io.ktor.http.URLUtilsKt.getFullPath(URLUtils.kt:79) ~[?:?]
        at io.ktor.http.Url.toString(URLBuilder.kt:169) ~[?:?]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:183) ~[?:?]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1) ~[?:?]
        at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:71) ~[?:?]
        at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[?:?]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[?:?]
[22:34:31 ERROR] [MiraiMC]: Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {353=[B@5cb23240}
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188) ~[?:?]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368) ~[?:?]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) ~[?:?]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[?:?]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[?:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[waterfall-1.18-475.jar:git:Waterfall-Bootstrap:1.18-R0.1-SNAPSHOT:21e4c1d:475]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]
[22:34:31 WARN] [MiraiMC]: 登录机器人时出现异常，原因: null
[22:34:31 INFO] [MiraiMC]: Bot cancelled: Bot closed
```

**额外说明**

**Comment by DreamVoid** [comment]
请尝试使用mirai 核心版本 2.8.2

**Comment by Baikele** [comment]
> 

我世界使用的miraimc1.5.3的版本，他不是自动生成么？

**Comment by Baikele** [comment]
> 请试用mirai内核版本2.8.2

好家伙，新问题，Bungee不支持db么？
[23:43:53 WARN] [MiraiMC]: 登录机器人时出现异常，原因: Fields [display, product, device, board, brand, model, bootloader, fingerprint, bootId, procVersion, baseBand, version, simInfo, osType, macAddress, wifiBSSID, wifiSSID, imsiMd5, imei, apn] are required for type with serial name 'net.mamoe.mirai.utils.DeviceInfo', but they were missing

**Comment by DreamVoid** [comment]
按要求提供完整服务端后开新issue
