### ISSUE TITLE
开发板最新错误提示 服务端版本最新spigot-1.12.2

### ISSUE THREAD

**Issue by Thelongyu** [DreamVoid/MiraiMC#81]
[13:11:45 ERROR]: [MiraiMC] Exception in decoding packet.
java.lang.IllegalStateException: Cannot find error message, unknown login result type: 180, TLVMap = {353=[B@6b0f44dc}
        at net.mamoe.mirai.internal.network.protocol.packet.login.WtLogin$Login.decode(WtLogin.kt:188) ~[mirai-core-all-2.10.0-RC.jar:2.10.0-RC]
        at net.mamoe.mirai.internal.network.components.PacketCodecImpl.processBody(PacketCodec.kt:368) ~[mirai-core-all-2.10.0-RC.jar:2.10.0-RC]
        at net.mamoe.mirai.internal.network.impl.netty.NettyNetworkHandler$PacketDecodePipeline$send$1.invokeSuspend(NettyNetworkHandler.kt:175) [mirai-core-all-2.10.0-RC.jar:2.10.0-RC]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.10.0-RC.jar:2.10.0-RC]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.10.0-RC.jar:2.10.0-RC]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [spigot-1.12.2.jar:git-Spigot-79a30d7-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_301]

**Comment by DreamVoid** [comment]
2. 为什么我开的Issue/Pull Request被直接关闭了？
你没有按照要求开Issue，我不会花费时间去理解不按模板提交的issue。你的Issue在之前已经有人提过了，为了处理效率不接受两个相同问题的Issue。
你在Gitee等其他Git平台提交了PR，除了Github外，所有Git平台都是Github的镜像，都从Github拉取代码，因此不接受其他Git平台的PR。
