### ISSUE TITLE
服务器消息没有同步到QQ群

### ISSUE THREAD

**Issue by SilenceAkarin** [DreamVoid/MiraiMC#88]
**问题描述**
服务器在启动很长时间后
QQ消息能同步到服务器，但服务器的消息无法同步到QQ
使用checkonline显示机器人保持在线
控制台使用mirai sendfriendmessage私聊能收到消息
使用mirai sendgroupmessage群内没有收到消息
退出账号后使用mirai checkonline出现WARN
再次登录账号时出现log4j2错误，机器人登录成功（log4j2错误没有在latest.log记录）
但服务器的消息仍然没有同步到QQ群

**复现方法**

1.服务器退出Bot后使用mirai checkonline 1934896563出现Warn警告
2.服务器退出bot后登录bot出现log4j2错误

**版本类型**

* Minecraft 服务端版本：Paper-176 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: b164899)
* MiraiMC 插件版本：MiraiMC 1.5.3

**截图**

**服务器日志**

```
[11:09:28 WARN]: Unexpected exception while parsing console command "mirai checkonline 1934896563"
org.bukkit.command.CommandException: Unhandled exception executing command 'mirai' in plugin MiraiMC v1.5.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchCommand(CraftServer.java:897) ~[paper-1.18.1.jar:git-Paper-176]
        at org.bukkit.craftbukkit.v1_18_R1.CraftServer.dispatchServerCommand(CraftServer.java:860) ~[paper-1.18.1.jar:git-Paper-176]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:507) ~[paper-1.18.1.jar:git-Paper-176]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:481) ~[paper-1.18.1.jar:git-Paper-176]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1470) ~[paper-1.18.1.jar:git-Paper-176]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1264) ~[paper-1.18.1.jar:git-Paper-176]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-176]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.util.NoSuchElementException: 1934896563
        at net.mamoe.mirai.Bot$Companion.getInstance(Bot.kt:205) ~[MiraiMC-Bukkit.jar:?]
        at net.mamoe.mirai.Bot.getInstance(Bot.kt) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.<init>(MiraiBot.java:41) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.api.MiraiBot.getBot(MiraiBot.java:51) ~[MiraiMC-Bukkit.jar:?]
        at me.dreamvoid.miraimc.bukkit.Commands.onCommand(Commands.java:173) ~[MiraiMC-Bukkit.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
        ... 9 more
```
[log4j2错误.txt](https://github.com/DreamVoid/MiraiMC/files/7947311/log4j2.txt)

**额外说明**

这是服务器使用的插件
![QQ图片20220127113012](https://user-images.githubusercontent.com/74251339/151287112-db79d530-f76e-4226-b069-009c68f41301.png)

**Comment by SilenceAkarin** [comment]
删了账号后重新授权解决问题了.....
