### ISSUE TITLE
异步执行任务异常：无法初始化类 me.dreamvoid.miraimc.api.MiraiBot$1

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [DreamVoid/MiraiMC#90]
**问题描述**

如题，因为这个问题无法登录
还有我没学过Java，不知道这玩意到底是不是KolinLib的问题。而且第一次使用Bukkit登录的Bot覆盖后可以正常运行一段时间，之后就出了这个问题。在上一个issue #87 中，使用Bukkit覆盖后解决，但是这个问题似乎是MiraiMC的Bug而不是KolinLib的问题。

**复现方法**

1. 未知

**版本类型**

* Minecraft 服务端版本：此服务器正在运行 Nukkit git-9455daa 「」API 版本 1.0.13 的 Minecraft: BE v1.18.0 (协议版本 475)
* MiraiMC 插件版本：

**截图**

![image](https://user-images.githubusercontent.com/79651409/151344004-9744bbf4-ebb2-4e9a-82b3-d0e10663d7b9.png)

**服务器日志**

```
2022-01-27 10:23:43.768 [main] INFO  - Loading §anukkit.yml§f ...
2022-01-27 10:23:43.947 [main] INFO  - Loading §aserver.properties§f ...
2022-01-27 10:23:44.035 [main] INFO  - 将 中文(简体) (chs) 设置为基本语言
2022-01-27 10:23:44.036 [main] INFO  - 正在启动 Minecraft: BE §bv1.18.0§r
2022-01-27 10:23:44.051 [main] INFO  - Selected Zlib Provider: 2 (cn.nukkit.utils.ZlibThreadLocal)
2022-01-27 10:23:44.165 [main] INFO  - 正在于 0.0.0.0:20493 启动服务器
2022-01-27 10:23:44.231 [main] INFO  - 此服务器正在运行 Nukkit §egit-9455daa§f 版本 "§b§f" (API 1.0.13)
2022-01-27 10:23:44.232 [main] INFO  - Nukkit 根据 LGPL 许可发行
2022-01-27 10:23:44.956 [main] INFO  - Loading runtime items...
2022-01-27 10:23:45.978 [main] INFO  - Loading recipes...
2022-01-27 10:23:47.152 [main] INFO  - Loaded 1509 recipes.
2022-01-27 10:23:47.154 [main] INFO  - 成功加载 0 个资源包
2022-01-27 10:23:47.629 [main] INFO  - 读取 MiraiMC v1.6-pre1 中
2022-01-27 10:23:49.375 [main] INFO  - [MiraiMC] Verifying maven-metadata-net.mamoe.mirai-core-all.xml
2022-01-27 10:23:49.376 [main] INFO  - [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/maven-metadata.xml
2022-01-27 10:23:49.758 [main] INFO  - [MiraiMC] Verifying mirai-core-all-2.10.0-RC2.jar
2022-01-27 10:23:49.957 [main] INFO  - [MiraiMC] Downloading https://maven.aliyun.com/nexus/content/groups/public/net/mamoe/mirai-core-all/2.10.0-RC2/mirai-core-all-2.10.0-RC2-all.jar
2022-01-27 10:24:27.288 [main] INFO  - [MiraiMC] Loading library mirai-core-all-2.10.0-RC2.jar
2022-01-27 10:24:27.365 [main] INFO  - 读取 BetterVanillaGenerator v1.2.2 中
2022-01-27 10:24:27.422 [main] INFO  - 读取 KotlinLib v1.4.31 中
2022-01-27 10:24:27.430 [main] INFO  - 读取 MobPlugin v1.21.4 中
2022-01-27 10:24:27.439 [main] INFO  - 读取 ScoreboardPlugin v1.0 中
2022-01-27 10:24:27.442 [main] INFO  - 读取 MOTD v1.0 中
2022-01-27 10:24:27.448 [main] INFO  - 读取 ClassicVillagePopulator v1.0.2 中
2022-01-27 10:24:27.454 [main] INFO  - 读取 PlaceholderAPI v2.1.1 中
2022-01-27 10:24:27.577 [main] INFO  - 读取 SingleTemplateStructurePopulator v1.0.1 中
2022-01-27 10:24:27.624 [main] INFO  - 读取 StrongholdPopulator v1.0.0 中
2022-01-27 10:24:27.629 [main] INFO  - 读取 MultiTemplateStructurePopulator v1.0.0 中
2022-01-27 10:24:27.643 [main] INFO  - 读取 NoSpaceInName v1.1.0 中
2022-01-27 10:24:27.650 [main] INFO  - 读取 Link2QQ v1.1 中
2022-01-27 10:24:27.660 [main] INFO  - 读取 TheEnd v1.2.0 中
2022-01-27 10:24:27.666 [main] INFO  - 读取 NetherFortressPopulator v1.0.0 中
2022-01-27 10:24:27.672 [main] INFO  - 读取 MineshaftPopulator v1.0.0 中
2022-01-27 10:24:27.726 [main] INFO  - 读取 Chat2QQ v1.4.2 中
2022-01-27 10:24:27.739 [main] INFO  - 读取 OceanMonumentPopulator v1.0.0 中
2022-01-27 10:24:27.761 [main] INFO  - 读取 QuasiStructurePopulator v1.0.3 中
2022-01-27 10:24:27.822 [main] INFO  - 读取 SimpleScoreboards v2.5.0 中
2022-01-27 10:24:27.831 [main] INFO  - 开启 BetterVanillaGenerator v1.2.2 中
2022-01-27 10:24:27.928 [main] INFO  - 开启 MobPlugin v1.21.4 中
2022-01-27 10:24:28.291 [main] INFO  - 开启 ClassicVillagePopulator v1.0.2 中
2022-01-27 10:24:28.311 [main] INFO  - 开启 SingleTemplateStructurePopulator v1.0.1 中
2022-01-27 10:24:28.565 [main] INFO  - 开启 StrongholdPopulator v1.0.0 中
2022-01-27 10:24:28.652 [main] INFO  - 开启 MultiTemplateStructurePopulator v1.0.0 中
2022-01-27 10:24:29.541 [main] INFO  - 开启 TheEnd v1.2.0 中
2022-01-27 10:24:29.566 [main] INFO  - 开启 NetherFortressPopulator v1.0.0 中
2022-01-27 10:24:29.637 [main] INFO  - 开启 MineshaftPopulator v1.0.0 中
2022-01-27 10:24:29.653 [main] INFO  - 开启 OceanMonumentPopulator v1.0.0 中
2022-01-27 10:24:29.663 [main] INFO  - 开启 QuasiStructurePopulator v1.0.3 中
2022-01-27 10:24:29.778 [main] INFO  - 准备世界 "§aworld§f" 中
2022-01-27 10:24:30.080 [main] INFO  - Preparing start region for level "world"
2022-01-27 10:24:30.156 [main] INFO  - 准备世界 "§anether§f" 中
2022-01-27 10:24:30.160 [main] INFO  - Preparing start region for level "nether"
2022-01-27 10:24:30.230 [main] INFO  - 开启 MiraiMC v1.6-pre1 中
2022-01-27 10:24:30.231 [main] INFO  - [MiraiMC] Mirai working dir: default
2022-01-27 10:24:30.231 [main] INFO  - [MiraiMC] Starting Mirai-Events listener.
2022-01-27 10:24:30.463 [main] INFO  - [MiraiMC] Loading auto-login file.
2022-01-27 10:24:30.465 [main] INFO  - [MiraiMC] Registering commands.
2022-01-27 10:24:30.479 [main] INFO  - [MiraiMC] Registering events.
2022-01-27 10:24:30.523 [main] INFO  - [MiraiMC] Initializing SQLite database.
2022-01-27 10:24:30.756 [main] INFO  - [MiraiMC] Initializing bStats metrics.
2022-01-27 10:24:30.760 [main] WARN  - [MiraiMC] 确保您正在使用开源的MiraiMC插件，未知来源的插件可能会盗取您的账号！
2022-01-27 10:24:30.761 [main] WARN  - [MiraiMC] 请始终从Github或作者指定的其他途径下载插件: https://github.com/DreamVoid/MiraiMC
2022-01-27 10:24:30.761 [main] INFO  - [MiraiMC] All tasks done. Welcome to use MiraiMC!
2022-01-27 10:24:30.762 [main] INFO  - 开启 KotlinLib v1.4.31 中
2022-01-27 10:24:30.762 [main] INFO  - 开启 ScoreboardPlugin v1.0 中
2022-01-27 10:24:30.762 [main] INFO  - 开启 MOTD v1.0 中
2022-01-27 10:24:30.767 [main] INFO  - 开启 PlaceholderAPI v2.1.1 中
2022-01-27 10:24:30.926 [main] ERROR - Throwing
java.lang.RuntimeException: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.CallableReference$NoReceiver from class kotlin.jvm.internal.CallableReference
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:440) [server-release.jar:?]
	at cn.nukkit.Server.enablePlugin(Server.java:750) [server-release.jar:?]
	at cn.nukkit.Server.enablePlugins(Server.java:739) [server-release.jar:?]
	at cn.nukkit.Server.<init>(Server.java:582) [server-release.jar:?]
	at cn.nukkit.Nukkit.main(Nukkit.java:120) [server-release.jar:?]
Caused by: java.lang.IllegalAccessError: tried to access class kotlin.jvm.internal.CallableReference$NoReceiver from class kotlin.jvm.internal.CallableReference
	at kotlin.jvm.internal.CallableReference.<clinit>(CallableReference.java:48) ~[?:?]
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.<clinit>(KDeclarationContainerImpl.kt) ~[?:?]
	at kotlin.reflect.jvm.internal.KClassImpl$data$1.invoke(KClassImpl.kt:180) ~[?:?]
	at kotlin.reflect.jvm.internal.KClassImpl$data$1.invoke(KClassImpl.kt:180) ~[?:?]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) ~[?:?]
	at kotlin.reflect.jvm.internal.KClassImpl.getSupertypes(KClassImpl.kt:254) ~[?:?]
	at kotlin.reflect.full.KClasses.getSuperclasses(KClasses.kt:185) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.util.UtilsKt.nestedSuperClass(Utils.kt:61) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.util.UtilsKt.nestedSuperClass$default(Utils.kt:56) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.PlaceholderAPIIml.getFormatter(PlaceholderAPIIml.kt:324) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.PlaceholderAPIIml.visitorSensitivePlaceholder(PlaceholderAPIIml.kt:124) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.api.PlaceholderAPI$Builder.build(PlaceholderAPI.kt:306) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.api.scope.DefaultsKt.registerDefaultPlaceholders(Defaults.kt:205) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.PlaceholderAPIIml.init$PlaceholderAPI(PlaceholderAPIIml.kt:70) ~[?:?]
	at com.creeperface.nukkit.placeholderapi.PlaceholderPlugin.onEnable(PlaceholderPlugin.kt:23) ~[?:?]
	at cn.nukkit.plugin.PluginBase.setEnabled(PluginBase.java:89) ~[server-release.jar:?]
	at cn.nukkit.plugin.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:117) ~[server-release.jar:?]
	at cn.nukkit.plugin.PluginManager.enablePlugin(PluginManager.java:436) ~[server-release.jar:?]
	... 4 more
2022-01-27 10:24:30.935 [main] INFO  - 关闭 PlaceholderAPI v2.1.1 中
2022-01-27 10:24:30.937 [main] INFO  - 开启 NoSpaceInName v1.1.0 中
2022-01-27 10:24:30.952 [main] INFO  - 开启 Link2QQ v1.1 中
2022-01-27 10:24:30.956 [main] INFO  - 开启 Chat2QQ v1.4.2 中
2022-01-27 10:24:30.972 [main] INFO  - 开启 SimpleScoreboards v2.5.0 中
2022-01-27 10:24:31.123 [main] INFO  - 启动 GS4 状态监听器
2022-01-27 10:24:31.124 [main] INFO  - 将 Query 端口设置为 20493
2022-01-27 10:24:31.125 [main] INFO  - Query 运行于 0.0.0.0:20493
2022-01-27 10:24:31.126 [main] INFO  - 默认游戏模式：生存模式
2022-01-27 10:24:31.126 [main] INFO  - 启动完成 (47.473s)！如需帮助，请输入 "help" 或 "?"
2022-01-27 10:24:31.130 [main] INFO  - 准备世界 "§athe_end§f" 中
2022-01-27 10:24:31.244 [main] INFO  - Preparing start region for level "the_end"
2022-01-27 10:24:31.266 [Nukkit Asynchronous Task Handler #0] INFO  - [MiraiMC] [AutoLogin] Starting auto login task.
2022-01-27 10:24:31.272 [Nukkit Asynchronous Task Handler #1] INFO  - [MiraiMC] Checking update...
2022-01-27 10:24:32.418 [Nukkit Asynchronous Task Handler #1] INFO  - [MiraiMC] 已找到新的插件更新，最新版本: 1.5.3
2022-01-27 10:24:32.418 [Nukkit Asynchronous Task Handler #1] INFO  - [MiraiMC] 从Github下载更新: https://github.com/DreamVoid/MiraiMC/releases/latest
2022-01-27 10:25:37.279 [main] INFO  - §6§lMiraiMC§r §b机器人帮助菜单
2022-01-27 10:25:37.280 [main] INFO  - §6/mirai login <账号> <密码> [协议]:§r 登录一个机器人
2022-01-27 10:25:37.280 [main] INFO  - §6/mirai logout <账号>:§r 退出一个机器人
2022-01-27 10:25:37.280 [main] INFO  - §6/mirai list:§r 查看当前存在的机器人
2022-01-27 10:25:37.281 [main] INFO  - §6/mirai sendfriendmessage <账号> <好友> <消息>:§r 向指定好友发送私聊消息
2022-01-27 10:25:37.281 [main] INFO  - §6/mirai sendgroupmessage <账号> <群号> <消息>:§r 向指定群发送群聊消息
2022-01-27 10:25:37.281 [main] INFO  - §6/mirai sendfriendnudge <账号> <好友>:§r 向指定好友发送戳一戳
2022-01-27 10:25:37.281 [main] INFO  - §6/mirai checkonline <账号>:§r 检查指定的机器人是否在线
2022-01-27 10:25:37.281 [main] INFO  - §6/mirai autologin add <账号> <密码> [协议]:§r 添加一个自动登录账号
2022-01-27 10:25:37.282 [main] INFO  - §6/mirai autologin list:§r 查看自动登录账号列表
2022-01-27 10:25:37.282 [main] INFO  - §6/mirai autologin remove <账号>:§r 删除一个自动登录账号
2022-01-27 10:25:39.328 [main] INFO  - §6§lMiraiMC§r §b插件帮助菜单§r §a玩家绑定
2022-01-27 10:25:39.328 [main] INFO  - §6/miraimc bind add <玩家名> <QQ号>:§r 为玩家和QQ号添加绑定
2022-01-27 10:25:39.328 [main] INFO  - §6/miraimc bind getplayer <玩家名>:§r 获取指定玩家名绑定的QQ号
2022-01-27 10:25:39.329 [main] INFO  - §6/miraimc bind getqq <QQ号>:§r 获取指定QQ号绑定的玩家名
2022-01-27 10:25:39.329 [main] INFO  - §6/miraimc bind removeplayer <玩家名>:§r 删除一个玩家的绑定
2022-01-27 10:25:39.329 [main] INFO  - §6/miraimc bind removeqq <QQ号>:§r 删除一个QQ号的绑定
2022-01-27 10:25:43.778 [main] INFO  - §6§lMiraiMC§r §b插件帮助菜单§r §a玩家绑定
2022-01-27 10:25:43.779 [main] INFO  - §6/miraimc bind add <玩家名> <QQ号>:§r 为玩家和QQ号添加绑定
2022-01-27 10:25:43.779 [main] INFO  - §6/miraimc bind getplayer <玩家名>:§r 获取指定玩家名绑定的QQ号
2022-01-27 10:25:43.779 [main] INFO  - §6/miraimc bind getqq <QQ号>:§r 获取指定QQ号绑定的玩家名
2022-01-27 10:25:43.779 [main] INFO  - §6/miraimc bind removeplayer <玩家名>:§r 删除一个玩家的绑定
2022-01-27 10:25:43.779 [main] INFO  - §6/miraimc bind removeqq <QQ号>:§r 删除一个QQ号的绑定
2022-01-27 10:25:54.278 [main] INFO  - §6§lMiraiMC§r §b插件帮助菜单§r §a玩家绑定
2022-01-27 10:25:54.278 [main] INFO  - §6/miraimc bind add <玩家名> <QQ号>:§r 为玩家和QQ号添加绑定
2022-01-27 10:25:54.278 [main] INFO  - §6/miraimc bind getplayer <玩家名>:§r 获取指定玩家名绑定的QQ号
2022-01-27 10:25:54.279 [main] INFO  - §6/miraimc bind getqq <QQ号>:§r 获取指定QQ号绑定的玩家名
2022-01-27 10:25:54.279 [main] INFO  - §6/miraimc bind removeplayer <玩家名>:§r 删除一个玩家的绑定
2022-01-27 10:25:54.279 [main] INFO  - §6/miraimc bind removeqq <QQ号>:§r 删除一个QQ号的绑定
2022-01-27 10:25:58.029 [main] INFO  - §a配置文件已经重新加载，部分配置可能需要重新启动服务器才能生效！
2022-01-27 10:26:01.178 [main] INFO  - §6§lMiraiMC§r §b机器人帮助菜单
2022-01-27 10:26:01.178 [main] INFO  - §6/mirai login <账号> <密码> [协议]:§r 登录一个机器人
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai logout <账号>:§r 退出一个机器人
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai list:§r 查看当前存在的机器人
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai sendfriendmessage <账号> <好友> <消息>:§r 向指定好友发送私聊消息
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai sendgroupmessage <账号> <群号> <消息>:§r 向指定群发送群聊消息
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai sendfriendnudge <账号> <好友>:§r 向指定好友发送戳一戳
2022-01-27 10:26:01.179 [main] INFO  - §6/mirai checkonline <账号>:§r 检查指定的机器人是否在线
2022-01-27 10:26:01.180 [main] INFO  - §6/mirai autologin add <账号> <密码> [协议]:§r 添加一个自动登录账号
2022-01-27 10:26:01.180 [main] INFO  - §6/mirai autologin list:§r 查看自动登录账号列表
2022-01-27 10:26:01.180 [main] INFO  - §6/mirai autologin remove <账号>:§r 删除一个自动登录账号
2022-01-27 10:26:18.487 [Nukkit Asynchronous Task Handler #1] INFO  - [MiraiMC] 登录新的机器人账号: 2064388365, 协议: ANDROID_PHONE
2022-01-27 10:26:18.525 [Nukkit Asynchronous Task Handler #1] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: Could not initialize class kotlin.reflect.jvm.internal.KClassImpl$Data
	at kotlin.reflect.jvm.internal.KClassImpl$data$1.invoke(KClassImpl.kt:180) ~[?:?]
	at kotlin.reflect.jvm.internal.KClassImpl$data$1.invoke(KClassImpl.kt:180) ~[?:?]
	at kotlin.reflect.jvm.internal.ReflectProperties$LazyVal.invoke(ReflectProperties.java:63) ~[?:?]
	at kotlin.reflect.jvm.internal.KClassImpl.getSimpleName(KClassImpl.kt:234) ~[?:?]
	at net.mamoe.mirai.utils.DefaultFactory.create(MiraiLogger.kt:580) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory.create(MiraiLogger.kt:64) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory.create(MiraiLogger.kt:79) ~[?:?]
	at net.mamoe.mirai.utils.MiraiLogger$Factory$INSTANCE.create(MiraiLogger.kt) ~[?:?]
	at net.mamoe.mirai.utils.WindowHelperJvm.<clinit>(SwingSolver.kt:135) ~[?:?]
	at net.mamoe.mirai.utils.LoginSolver.<clinit>(LoginSolver.jvm.kt:92) ~[?:?]
	at net.mamoe.mirai.utils.BotConfiguration.<init>(BotConfiguration.kt:236) ~[?:?]
	at net.mamoe.mirai.utils.BotConfiguration.<clinit>(BotConfiguration.kt:624) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:213) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
	at me.dreamvoid.miraimc.nukkit.commands.miraisubcommand.LoginCommand$1.onRun(LoginCommand.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[server-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
2022-01-27 10:26:18.538 [Thread-10] INFO  - [BugReport] 侦测到一个错误，正在生成错误报告。
2022-01-27 10:26:18.552 [Thread-10] INFO  - [BugReport] 创建错误报告：/home/container/logs/bug_reports/20220127102618_NoClassDefFoundError.md
2022-01-27 10:43:59.029 [Nukkit Asynchronous Task Handler #3] INFO  - [MiraiMC] 登录新的机器人账号: 2064388365, 协议: ANDROID_PHONE
2022-01-27 10:43:59.030 [Nukkit Asynchronous Task Handler #3] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: Could not initialize class me.dreamvoid.miraimc.api.MiraiBot$1
	at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:213) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
	at me.dreamvoid.miraimc.nukkit.commands.miraisubcommand.LoginCommand$1.onRun(LoginCommand.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[server-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
2022-01-27 10:43:59.036 [Thread-13] INFO  - [BugReport] 侦测到一个错误，正在生成错误报告。
2022-01-27 10:43:59.040 [Thread-13] INFO  - [BugReport] 创建错误报告：/home/container/logs/bug_reports/20220127104359_NoClassDefFoundError.md
2022-01-27 10:44:01.384 [Nukkit Asynchronous Task Handler #3] INFO  - [MiraiMC] 登录新的机器人账号: 2064388365, 协议: ANDROID_PHONE
2022-01-27 10:44:01.384 [Nukkit Asynchronous Task Handler #3] FATAL - Exception in asynchronous task
java.lang.NoClassDefFoundError: Could not initialize class me.dreamvoid.miraimc.api.MiraiBot$1
	at me.dreamvoid.miraimc.api.MiraiBot.privateBotLogin(MiraiBot.java:213) ~[?:?]
	at me.dreamvoid.miraimc.api.MiraiBot.doBotLogin(MiraiBot.java:94) ~[?:?]
	at me.dreamvoid.miraimc.nukkit.commands.miraisubcommand.LoginCommand$1.onRun(LoginCommand.java:62) ~[?:?]
	at cn.nukkit.scheduler.AsyncTask.run(AsyncTask.java:23) ~[server-release.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
2022-01-27 10:44:01.386 [Thread-15] INFO  - [BugReport] 侦测到一个错误，正在生成错误报告。
2022-01-27 10:44:01.390 [Thread-15] INFO  - [BugReport] 创建错误报告：/home/container/logs/bug_reports/20220127104401_NoClassDefFoundError.md
```

**额外说明**

这玩意不是KolinLib的问题吧
插件列表
![pt simpfun cn_server_e1e4a08d_files](https://user-images.githubusercontent.com/79651409/151344967-1e89eed8-7d8e-4627-b978-315705b41964.png)

**Comment by DreamVoid** [comment]
请检查你下载的插件是否来自Github我的仓库，正常情况下不可能出现找不到内部类的情况。除非插件被篡改。

**Comment by XiaMoHuaHuo-CN** [comment]
确实来自你的仓库

**Comment by XiaMoHuaHuo-CN** [comment]
无论是正式版，测试版还是Action构建

**Comment by DreamVoid** [comment]
那就是被其他东西篡改了。

**Comment by XiaMoHuaHuo-CN** [comment]
有没有可能是线程被占用
