### ISSUE TITLE
关于隐藏 Nukkit 版本 需要验证时okhttp抛出的错误 的建议

### ISSUE THREAD

**Issue by XiaMoHuaHuo-CN** [DreamVoid/MiraiMC#91]
**功能描述**

如题

如题，隐藏下方抛出的错误
(这一行可以不用隐藏) 11:10:39 [ERROR] [MiraiMC] Failed to fetch ECDH public key from server, using default key instead
```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at io.ktor.utils.io.bits.MemoryJvmKt.sliceSafe(MemoryJvm.kt:211) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.utils.io.bits.Memory.slice-SK3TCg8(MemoryJvm.kt:47) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.utils.io.charsets.CharsetJVMKt.encodeImpl(CharsetJVM.kt:356) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.utils.io.charsets.EncodingKt.encodeToImpl(Encoding.kt:204) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.utils.io.charsets.EncodingKt.encode(Encoding.kt:62) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.utils.io.charsets.EncodingKt.encode$default(Encoding.kt:57) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.CodecsKt.encodeURLParameter(Codecs.kt:123) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:68) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.HttpUrlEncodedKt$formUrlEncodeTo$1.invoke(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlin.text.StringsKt__AppendableKt.appendElement(Appendable.kt:85) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:3347) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo$default(_Collections.kt:3341) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:67) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:108) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.HttpUrlEncodedKt.formUrlEncodeTo(HttpUrlEncoded.kt:90) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.URLUtilsKt.appendUrlFullPath(URLUtils.kt:101) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.URLUtilsKt.getFullPath(URLUtils.kt:79) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.http.Url.toString(URLBuilder.kt:169) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.convertToOkHttpRequest(OkHttpEngine.kt:183) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.client.engine.okhttp.OkHttpEngineKt.access$convertToOkHttpRequest(OkHttpEngine.kt:1) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.client.engine.okhttp.OkHttpEngine.execute(OkHttpEngine.kt:71) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at io.ktor.client.engine.HttpClientEngine$executeWithinCallContext$2.invokeSuspend(HttpClientEngine.kt:85) ~[mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [mirai-core-all-2.10.0-RC2.jar:2.10.0-RC2]
```
**使用方法**

1. None

**额外说明**

None

**Comment by DreamVoid** [comment]
首先连我自己都不知道这部分报错会从哪里引发，因此我无法使用try来捕获。
那么你能提供解决方案吗
